# Generated by Django 3.2.25 on 2024-04-22 12:35

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('features', '0064_fix_feature_help_text_typo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureExternalResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('type', models.CharField(choices=[('GITHUB_ISSUE', 'GitHub Issue'), ('GITHUB_PR', 'GitHub PR')], max_length=20)),
                ('metadata', models.TextField(null=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_resources', to='features.feature')),
            ],
            options={
                'ordering': ('id',),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='featureexternalresource',
            constraint=models.UniqueConstraint(fields=('feature', 'url'), name='unique_feature_url_constraint'),
        ),
    ]
