# Generated by Django 3.2.25 on 2024-04-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_external_resources', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='featureexternalresource',
            index=models.Index(fields=['type'], name='feature_ext_type_2b2068_idx'),
        ),
    ]
