# Generated by Django 3.2.16 on 2023-01-13 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environments', '0027_auto_20230106_0626'),
        ('projects', '0016_soft_delete_projects'),
        ('organisations', '0038_soft_delete_organisations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.CharField(max_length=255)),
                ('resource', models.IntegerField(choices=[(1, 'Flags'), (2, 'Identities'), (3, 'Traits'), (4, 'Environment Document')])),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environments.environment')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
