# Generated by Django 3.2.16 on 2023-01-16 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('features', '0048_add_master_api_key_to_historical_records'),
        ('environments', '0027_auto_20230106_0626'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.feature')),
            ],
        ),
        migrations.CreateModel(
            name='APIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.CharField(max_length=255)),
                ('resource', models.IntegerField(choices=[(1, 'Flags'), (2, 'Identities'), (3, 'Traits'), (4, 'Environment Document')])),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environments.environment')),
            ],
        ),
    ]
