# Generated by Django 3.2.23 on 2024-01-02 16:35

from django.db import migrations, models
from core.migration_helpers import PostgresOnlyRunSQL


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('app_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureevaluationraw',
            name='identity_identifier',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='featureevaluationraw',
                    name='feature_name',
                    field=models.CharField(db_index=True, max_length=2000),
                ),
            ],
            database_operations=[
                PostgresOnlyRunSQL(
                    'CREATE INDEX CONCURRENTLY "app_analytics_featureevaluationraw_feature_name_idx" ON "app_analytics_featureevaluationraw" ("feature_name");',
                    reverse_sql='DROP INDEX CONCURRENTLY "app_analytics_featureevaluationraw_feature_name_idx";',
                )
            ],
        ),
    ]
