# Generated by Django 3.2.16 on 2023-01-13 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0038_soft_delete_organisations'),
        ('projects', '0016_soft_delete_projects'),
        ('environments', '0027_auto_20230106_0626'),
        ('app_analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Analytics',
            new_name='APIUsage',
        ),
    ]
