# Generated by Django 3.2.23 on 2024-01-02 16:35

from django.db import migrations, models
from core.migration_helpers import PostgresOnlyRunSQL


class Migration(migrations.Migration):
    """
    This migration class used to include the addition of the index that now lives
    in 0003_add_feature_name_index. The reason for this can be attributed to the
    discussion here: https://github.com/Flagsmith/flagsmith/issues/3425
    """

    dependencies = [
        ('app_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureevaluationraw',
            name='identity_identifier',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='featureevaluationraw',
            name='enabled_when_evaluated',
            field=models.BooleanField(null=True, default=None),
        ),
    ]
