# Generated by Django 3.2.16 on 2023-01-16 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiusage',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterIndexTogether(
            name='apiusage',
            index_together={('environment_id', 'created_date')},
        ),
        migrations.RemoveField(
            model_name='apiusage',
            name='created_at',
        ),
    ]
