# Generated by Django 3.2.16 on 2023-01-13 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0048_add_master_api_key_to_historical_records'),
        ('app_analytics', '0002_rename_analytics_apiusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.feature')),
            ],
        ),
    ]
