# Generated by Django 3.2.23 on 2024-02-15 18:33

from django.db import migrations, models

from core.migration_helpers import PostgresOnlyRunSQL


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("app_analytics", "0002_featureevaluationraw_identifier_and_index_feature"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="featureevaluationraw",
                    name="feature_name",
                    field=models.CharField(db_index=True, max_length=2000),
                ),
            ],
            database_operations=[
                PostgresOnlyRunSQL(
                    'CREATE INDEX CONCURRENTLY IF NOT EXISTS "app_analytics_featureevaluationraw_feature_name_idx" ON "app_analytics_featureevaluationraw" ("feature_name");',
                    reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS "app_analytics_featureevaluationraw_feature_name_idx";',
                )
            ],
        ),
    ]
