# Generated by Django 3.2.16 on 2023-01-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_analytics', '0002_auto_20230116_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIUsageByDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment_id', models.PositiveIntegerField()),
                ('resource', models.IntegerField(choices=[(1, 'Flags'), (2, 'Identities'), (3, 'Traits'), (4, 'Environment Document')])),
                ('total_count', models.PositiveIntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='APIUsageRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.CharField(max_length=255)),
                ('resource', models.IntegerField(choices=[(1, 'Flags'), (2, 'Identities'), (3, 'Traits'), (4, 'Environment Document')])),
            ],
            options={
                'index_together': {('environment_id', 'created_at')},
            },
        ),
        migrations.DeleteModel(
            name='APIUsage',
        ),
    ]
