# Generated by Django 3.2.16 on 2023-01-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_analytics', '0003_auto_20230116_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIUsageBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment_id', models.PositiveIntegerField()),
                ('resource', models.IntegerField(choices=[(1, 'Flags'), (2, 'Identities'), (3, 'Traits'), (4, 'Environment Document')])),
                ('total_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bucket_size', models.PositiveIntegerField(help_text='Bucket size in minutes')),
            ],
        ),
        migrations.DeleteModel(
            name='APIUsageByDay',
        ),
        migrations.CreateModel(
            name='APIUsageByDay',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app_analytics.apiusagebucket',),
        ),
    ]
