# Generated by Django 3.2.25 on 2024-07-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_analytics', '0003_add_feature_name_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiusageraw',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
