# Generated by Django 3.2.16 on 2023-01-13 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_analytics', '0003_featureevaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiusage',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='apiusage',
            name='project',
        ),
    ]
