# Generated by Django 3.2.25 on 2024-07-29 10:01

from django.db import migrations, models

from core.migration_helpers import PostgresOnlyRunSQL


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ("app_analytics", "0004_apiusageraw_count"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="featureevaluationraw",
                    index=models.Index(
                        fields=["created_at"],
                        name="f_evaluation_created_at_idx",
                    ),
                )
            ],
            database_operations=[
                PostgresOnlyRunSQL(
                    'CREATE INDEX CONCURRENTLY IF NOT EXISTS "f_evaluation_created_at_idx" ON "app_analytics_featureevaluationraw" ("created_at");',
                    reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS "f_evaluation_created_at_idx"',
                )
            ],
        )
    ]
