# Generated by Django 4.2.21 on 2025-06-16 16:55

# import django.contrib.postgres.fields.hstore
# from django.contrib.postgres.operations import HStoreExtension

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("app_analytics", "0005_featureevaluationraw_created_at_idx"),
    ]

    operations = [
        # # The extension usage is annulated by the subsequent migration.
        # # To avoid the operational overhead of enabling it in some environments,
        # # we do not create it here anymore.
        # # However, leave it commented out for reference/history.
        # HStoreExtension(),
        migrations.AddField(
            model_name="apiusagebucket",
            name="labels",
            # This field is now a JSONField instead of HStoreField.
            # field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="apiusageraw",
            name="labels",
            # This field is now a JSONField instead of HStoreField.
            # field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="featureevaluationbucket",
            name="labels",
            # This field is now a JSONField instead of HStoreField.
            # field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="featureevaluationraw",
            name="labels",
            # This field is now a JSONField instead of HStoreField.
            # field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
            field=models.JSONField(default=dict),
        ),
    ]
