# Generated by Django 3.2.16 on 2023-01-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_analytics', '0005_alter_apiusagebucket_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureEvaluationBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=2000)),
                ('environment_id', models.PositiveIntegerField()),
                ('total_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField()),
                ('bucket_size', models.PositiveIntegerField(help_text='Bucket size in minutes')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureEvaluationRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=2000)),
                ('environment_id', models.PositiveIntegerField()),
                ('evaluation_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FeatureEvaluation',
        ),
        migrations.DeleteModel(
            name='APIUsageByDay',
        ),
    ]
