# Generated by Django 4.2.22 on 2025-07-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_analytics", "0006_add_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiusagebucket",
            name="labels",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="apiusageraw",
            name="labels",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="featureevaluationbucket",
            name="labels",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="featureevaluationraw",
            name="labels",
            field=models.JSONField(default=dict),
        ),
    ]
