# Generated by Django 5.2.9 on 2025-12-31 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_analytics", "0006_add_labels"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="apiusageraw",
            new_name="app_analyti_environ_b61cad_idx",
            old_fields=("environment_id", "created_at"),
        ),
    ]
