# Generated by Django 5.2.15 on 2026-06-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_analytics", "0008_labels_jsonb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiusagebucket",
            name="created_at",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="featureevaluationbucket",
            name="created_at",
            field=models.DateTimeField(db_index=True),
        ),
    ]
