# Generated by Django 5.2.17 on 2026-09-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_analytics", "0008_labels_jsonb"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiusagebucket",
            name="host",
            field=models.CharField(default="", max_length=255),
        ),
    ]
