# Generated by Django 5.2.17 on 2026-09-05 02:32

from datetime import timedelta

from django.db import migrations, models
from django.utils import timezone


def delete_buckets_the_rollup_may_recompute(apps, schema_editor):  # type: ignore[no-untyped-def]
    # Buckets created before the `host` column existed hold the window's
    # whole count under host "". The rollup recomputes the last hour of
    # windows on every run, and a recomputed window now gets one row per
    # host next to the old row, counting the window twice. Delete the rows
    # the rollup can still reach; its next run rebuilds them from raw data.
    APIUsageBucket = apps.get_model("app_analytics", "APIUsageBucket")
    APIUsageBucket.objects.using(schema_editor.connection.alias).filter(
        created_at__gte=timezone.now() - timedelta(hours=2)
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("app_analytics", "0008_labels_jsonb"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiusagebucket",
            name="host",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.RunPython(
            delete_buckets_the_rollup_may_recompute, migrations.RunPython.noop
        ),
    ]
