# Generated by Django 3.2.13 on 2022-06-21 15:28

from django.db import migrations, models
import uuid

from core.migration_helpers import AddDefaultUUIDs


class Migration(migrations.Migration):

    dependencies = [
        ("amplitude", "0003_amplitudeconfiguration_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amplitudeconfiguration",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
