# Generated by Django 3.2.18 on 2023-02-28 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0028_add_use_mv_v2_evaluation'),
        ('amplitude', '0004_make_uuid_not_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amplitudeconfiguration',
            name='environment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='amplitude_config', to='environments.environment'),
        ),
    ]
