# Generated by Django 3.2.20 on 2023-07-27 13:04

from django.db import migrations, models
from django.db.models import Q


def add_default_base_url(apps, schema_editor):
    amplitude_configuration_model = apps.get_model(
        "amplitude", "AmplitudeConfiguration"
    )

    # Note that we're updating the existing items to point to
    # api.amplitude.com (rather than api2) to maintain existing
    # behaviour for these integrations.
    amplitude_configuration_model.objects.filter(
        Q(base_url__isnull=True) | Q(base_url="")
    ).update(base_url="https://api.amplitude.com")


class Migration(migrations.Migration):
    dependencies = [
        ("amplitude", "0005_amplitudeconfiguration_deleted_at"),
    ]

    operations = [
        migrations.RunPython(
            add_default_base_url, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="amplitudeconfiguration",
            name="base_url",
            field=models.URLField(default="https://api2.amplitude.com"),
        ),
    ]
