# Generated by Django 5.2.16 on 2026-08-07 11:54

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("amplitude", "0006_add_default_base_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amplitudeconfiguration",
            name="base_url",
            field=core.fields.NoSSRFURLField(default="https://api2.amplitude.com"),
        ),
    ]
