# Generated by Django 2.2.24 on 2021-12-17 03:26

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0010_auto_20211208_1050'),
        ('environments', '0015_auto_20200916_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slack_config', to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='SlackEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(help_text='Id of the slack channel to post messages to', max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_environment', to='environments.Environment')),
                ('slack_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='env_config', to='slack.SlackConfiguration')),
            ],
            options={
                'unique_together': {('slack_configuration', 'environment')},
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
