# Generated by Django 3.2.18 on 2023-02-28 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_soft_delete_projects'),
        ('slack', '0002_add_uuid_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackconfiguration',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='slack_config', to='projects.project'),
        ),
    ]
