# Generated by Django 3.2.18 on 2023-02-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0002_add_uuid_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackconfiguration',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
    ]
