# Generated by Django 3.2.23 on 2024-01-31 21:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0020_add_environment_feature_state_version_logic'),
        ('organisations', '0049_subscription_billing_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('installation_id', models.CharField(max_length=100)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_config', to='organisations.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GithubRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('repository_owner', models.CharField(max_length=100)),
                ('repository_name', models.CharField(max_length=100)),
                ('github_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_config', to='github.githubconfiguration')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_project', to='projects.project')),
            ],
            options={
                'unique_together': {('github_configuration', 'project', 'repository_owner', 'repository_name', 'deleted_at')},
            },
        ),
    ]
