# Generated by Django 3.2.25 on 2024-04-12 14:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0022_add_stale_flags_threshold_to_project'),
        ('organisations', '0052_create_hubspot_organisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('installation_id', models.CharField(max_length=100)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_config', to='organisations.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GithubRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('repository_owner', models.CharField(max_length=100)),
                ('repository_name', models.CharField(max_length=100)),
                ('github_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_config', to='github.githubconfiguration')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_project', to='projects.project')),
            ],
        ),
        migrations.AddConstraint(
            model_name='githubrepository',
            constraint=models.UniqueConstraint(fields=('github_configuration', 'project', 'repository_owner', 'repository_name'), name='unique_repository_data'),
        ),
    ]
