# Generated by Django 3.2.25 on 2024-05-01 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0052_create_hubspot_organisation'),
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubconfiguration',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_config', to='organisations.organisation'),
        ),
        migrations.AddConstraint(
            model_name='githubconfiguration',
            constraint=models.UniqueConstraint(fields=('organisation', 'installation_id'), name='unique_github_config_data'),
        ),
    ]
