# Generated by Django 3.2.25 on 2024-05-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0002_auto_20240502_1949"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="githubconfiguration",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="githubrepository",
            options={"ordering": ("id",)},
        ),
        migrations.RemoveConstraint(
            model_name="githubrepository",
            name="unique_repository_data",
        ),
        migrations.AddConstraint(
            model_name="githubrepository",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=(
                    "github_configuration",
                    "project",
                    "repository_owner",
                    "repository_name",
                ),
                name="unique_repository_data",
            ),
        ),
    ]
