# Generated by Django 3.2.25 on 2024-05-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0002_auto_20240502_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubconfiguration',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('INVALID_INSTALLATION_ID', 'Installation ID invalid')], default='ACTIVE', max_length=25),
        ),
    ]
