# Generated by Django 3.2.25 on 2024-08-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0003_auto_20240528_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepository',
            name='tagging_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
