# Generated by Django 2.2.17 on 2021-01-18 20:26

import app.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0024_organisation_feature_analytics'),
        ('invites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation'),
        ),
        migrations.CreateModel(
            name='InviteLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(default=app.utils.create_hash, max_length=100, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='DateCreated')),
                ('role', models.CharField(default='USER', max_length=50)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Datetime that the invite link will cease to be active. Leave blank to enable indefinitely.', null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
