# Generated by Django 3.2.12 on 2022-03-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0002_auto_20210118_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='role',
            field=models.CharField(choices=[], default='USER', max_length=50),
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='role',
            field=models.CharField(choices=[], default='USER', max_length=50),
        ),
    ]
