# Generated by Django 3.2.13 on 2022-05-13 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0003_auto_20220323_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='frontend_base_url',
        ),
    ]
