# Generated by Django 3.2.15 on 2022-10-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_userpermissiongroup_is_default'),
        ('invites', '0005_add_uuid_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='permission_groups',
            field=models.ManyToManyField(blank=True, to='users.UserPermissionGroup'),
        ),
    ]
