# Generated by Django 3.2.15 on 2022-10-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_ffadminuser_marketing_consent_given'),
        ('invites', '0005_add_uuid_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='permission_groups',
            field=models.ManyToManyField(to='users.UserPermissionGroup'),
        ),
        migrations.AddField(
            model_name='invitelink',
            name='permission_groups',
            field=models.ManyToManyField(to='users.UserPermissionGroup'),
        ),
    ]
