# Generated by Django 2.2.10 on 2020-02-21 21:26

from django.db import migrations


def add_edit_feature_permission(apps, schema_editor):
    PermissionModel = apps.get_model('permissions', 'PermissionModel')

    PermissionModel.objects.get_or_create(
        key='EDIT_FEATURE',
        type='PROJECT',
        defaults={
            'description': 'Ability to edit features in the given project (includes editing segments).'
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_edit_feature_permission, reverse_code=lambda *args: None)
    ]
