# Generated by Django 3.2.14 on 2022-07-12 15:32

from django.db import migrations

from permissions.models import PROJECT_PERMISSION_TYPE


def add_manage_segments_permission(apps, schema_editor):
    permission_model_class = apps.get_model("permissions", "permissionmodel")
    permission_model_class.objects.create(
        key="MANAGE_SEGMENTS",
        description="Ability to manage segments in the given project.",
        type=PROJECT_PERMISSION_TYPE,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0005_orphan_permission_cleanup"),
    ]

    operations = [
        migrations.RunPython(
            add_manage_segments_permission, reverse_code=migrations.RunPython.noop
        )
    ]
