# Generated by Django 4.2.15 on 2024-09-13 16:18
from common.projects.permissions import MANAGE_TAGS  # type: ignore[import-untyped]
from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

from permissions.models import PROJECT_PERMISSION_TYPE


def add_manage_tags_permission(
    apps: Apps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    permission_model_class = apps.get_model("permissions", "permissionmodel")
    permission_model_class.objects.get_or_create(
        key=MANAGE_TAGS,
        description="Allows the user to manage tags in the given project.",
        type=PROJECT_PERMISSION_TYPE,
    )


def reverse(
    apps: Apps, schema_editor: BaseDatabaseSchemaEditor
) -> None:  # pragma: no cover
    permission_model_class = apps.get_model("permissions", "permissionmodel")
    permission_model_class.objects.filter(key=MANAGE_TAGS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0009_move_view_audit_log_permission"),
    ]

    operations = [
        migrations.RunPython(add_manage_tags_permission, reverse_code=reverse),
    ]
