# Generated by Django on 2025-12-29

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

from permissions.models import PROJECT_PERMISSION_TYPE

# NOTE: These constants should eventually be added to the flagsmith-common package
# For now, they're defined here locally until the external package is updated
MANAGE_BUCKETS = "MANAGE_BUCKETS"
VIEW_BUCKET = "VIEW_BUCKET"


def add_bucket_permissions(
    apps: Apps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    permission_model_class = apps.get_model("permissions", "permissionmodel")

    permission_model_class.objects.get_or_create(
        key=MANAGE_BUCKETS,
        defaults={
            "description": "Allows the user to create, update, and delete buckets in the project.",
            "type": PROJECT_PERMISSION_TYPE,
        },
    )

    permission_model_class.objects.get_or_create(
        key=VIEW_BUCKET,
        defaults={
            "description": "Allows the user to view buckets in the project.",
            "type": PROJECT_PERMISSION_TYPE,
        },
    )


def reverse(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    permission_model_class = apps.get_model("permissions", "permissionmodel")
    permission_model_class.objects.filter(
        key__in=[MANAGE_BUCKETS, VIEW_BUCKET]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0010_add_manage_tags_permission"),
    ]

    operations = [
        migrations.RunPython(add_bucket_permissions, reverse_code=reverse),
    ]
