# Build Assets
FROM node:12 AS build

RUN mkdir /srv/bt && chown node:node /srv/bt

USER node

WORKDIR /srv/bt

COPY --chown=node:node . .

RUN npm install --quiet
ENV ENV prod
ENV STATIC_ASSET_CDN_URL=/
RUN npm run bundle


# Set up runtime container
FROM node:12 AS production

RUN apt-get update
RUN apt-get install -y openjdk-8-jdk
RUN wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_85.0.4183.102-1_amd64.deb
RUN apt install -y ./google-chrome*.deb -f
RUN apt-get clean

USER node

WORKDIR /srv/bt
COPY --from=build --chown=node:node /srv/bt/ .

ENV ENV=prod

EXPOSE 8080

CMD ["node",  "./server/index.js"]