# Build Assets
FROM node:12 AS build

RUN mkdir /srv/bt && chown node:node /srv/bt

USER node

WORKDIR /srv/bt

COPY --chown=node:node . .

RUN npm install --quiet
ENV ENV prod
RUN npm run bundle


# Set up runtime container
FROM node:12 AS production

RUN apt-get update
RUN apt-get install -y openjdk-8-jdk
ARG CHROMEURL='https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_96.0.4664.110-1_amd64.deb'
RUN wget -q $CHROMEURL
RUN apt install -y ./google-chrome*.deb -f
RUN apt-get clean

USER node

WORKDIR /srv/bt
COPY --from=build --chown=node:node /srv/bt/ .

ENV ENV=prod

EXPOSE 8080

CMD ["node",  "./api/index.js"]
