# Generated by Django 3.2.20 on 2023-07-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0002_soft_delete_api_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterapikey',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
