# Generated by Django 3.2.23 on 2023-12-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launch_darkly', '0002_importrequest_unique_project_ld_project_key_status_result_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicallaunchdarklyimportrequest',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical launch darkly import request', 'verbose_name_plural': 'historical launch darkly import requests'},
        ),
        migrations.AddField(
            model_name='historicallaunchdarklyimportrequest',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicallaunchdarklyimportrequest',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
