# Generated by Django 3.2.20 on 2023-11-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launch_darkly', '0003_history_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallaunchdarklyimportrequest',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
