# Generated by Django 3.2.15 on 2022-10-13 16:05

from django.db import migrations

from core.migration_helpers import PostgresOnlyRunSQL


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("environments", "0022_environment_description"),
        ("identities", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterIndexTogether(
                    name="identity",
                    index_together={("environment", "created_date")},
                )
            ],
            database_operations=[
                PostgresOnlyRunSQL(
                    'CREATE INDEX CONCURRENTLY IF NOT EXISTS "environments_identity_environment_id_created_date_idx" '
                    'ON "environments_identity" ("environment_id", "created_date");'
                )
            ],
        )
    ]
