# Generated by Django 4.2.22 on 2025-09-08 23:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identities", "0002_alter_identity_index_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identity",
            name="identifier",
            field=models.CharField(
                max_length=2000,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Identifier can only contain unicode letters, numbers, and the symbols: ! # $ %% & * + / = ? ^ _ ` { } | ~ @ . -",
                        regex="^[\\w!#$%&*+/=?^_`{}|~@.\\-]+$",
                    )
                ],
            ),
        ),
    ]
