# Generated by Django 4.2.24 on 2025-09-17 16:24

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ("identities", "0003_sanitized_identifiers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identity",
            name="identifier",
            field=models.CharField(
                max_length=2000,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Identifier can only contain unicode letters, numbers, spaces and the symbols: ! # $ %% & * + / = ? ^ _ ` { } | ~ @ . -",
                        regex=re.compile("^[\\w !#$%&*+/=?^_`{}|~@.\\-]+$"),
                    )
                ],
            ),
        ),
    ]
