# Generated by Django 4.2.22 on 2025-09-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identities", "0004_allow_spaces_in_identifiers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identity",
            name="identifier",
            field=models.CharField(max_length=2000),
        ),
    ]
