# Generated by Django 5.2.9 on 2025-12-31 15:29
from common.migrations.helpers import PostgresOnlyRunSQL
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("identities", "0005_revert_sanitized_identifiers"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name="identity",
                    new_name="environment_environ_341dc9_idx",
                    old_fields=("environment", "created_date"),
                ),
            ],
            database_operations=[
                PostgresOnlyRunSQL(
                    'ALTER INDEX "environments_identity_environment_id_created_date_idx" RENAME TO "environment_environ_341dc9_idx"',
                    reverse_sql='ALTER INDEX "environment_environ_341dc9_idx" RENAME TO "environments_identity_environment_id_created_date_idx"'
                )
            ],
        )
    ]
