# Generated by Django 5.2.9 on 2025-12-31 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("identities", "0005_revert_sanitized_identifiers"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="identity",
            new_name="environment_environ_341dc9_idx",
            old_fields=("environment", "created_date"),
        ),
    ]
