# Generated by Django 5.2.16 on 2026-08-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identities", "0006_rename_environment_created_date_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="identity",
            name="system_traits",
            field=models.JSONField(default=dict),
        ),
    ]
