# Generated by Django 5.2.17 on 2026-09-14 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("features", "0067_add_feature_state_mv_hashing_salt"),
        ("segments", "0032_add_segment_rules_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="SegmentFlagReference",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition_json_path", models.TextField()),
                (
                    "prerequisite_feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segment_references",
                        to="features.feature",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flag_references",
                        to="segments.segment",
                    ),
                ),
            ],
        ),
    ]
