// Auto-generated by compare-visual-regression.ts — do not edit
import { test, expect } from '@playwright/test'
import * as fs from 'fs'

test.describe('Visual Regression', () => {

  test('change.request.test.pw.ts / change requests list', async () => {
    const screenshot = fs.readFileSync('/Users/kyle/flagsmith/frontend/e2e/visual-regression-screenshots/change-request-test-pw-ts--change-requests-list.png')
    expect(screenshot).toMatchSnapshot('change-request-test-pw-ts--change-requests-list.png', {
      maxDiffPixels: 300,
      threshold: 0.02,
    })
  })

  test('environment.test.pw.ts / environment created', async () => {
    const screenshot = fs.readFileSync('/Users/kyle/flagsmith/frontend/e2e/visual-regression-screenshots/environment-test-pw-ts--environment-created.png')
    expect(screenshot).toMatchSnapshot('environment-test-pw-ts--environment-created.png', {
      maxDiffPixels: 300,
      threshold: 0.02,
    })
  })

  test('flag.tests.pw.ts / features archived filter', async () => {
    const screenshot = fs.readFileSync('/Users/kyle/flagsmith/frontend/e2e/visual-regression-screenshots/flag-tests-pw-ts--features-archived-filter.png')
    expect(screenshot).toMatchSnapshot('flag-tests-pw-ts--features-archived-filter.png', {
      maxDiffPixels: 300,
      threshold: 0.02,
    })
  })

  test('flag.tests.pw.ts / features list production', async () => {
    const screenshot = fs.readFileSync('/Users/kyle/flagsmith/frontend/e2e/visual-regression-screenshots/flag-tests-pw-ts--features-list-production.png')
    expect(screenshot).toMatchSnapshot('flag-tests-pw-ts--features-list-production.png', {
      maxDiffPixels: 300,
      threshold: 0.02,
    })
  })

  test('flag.tests.pw.ts / features list', async () => {
    const screenshot = fs.readFileSync('/Users/kyle/flagsmith/frontend/e2e/visual-regression-screenshots/flag-tests-pw-ts--features-list.png')
    expect(screenshot).toMatchSnapshot('flag-tests-pw-ts--features-list.png', {
      maxDiffPixels: 300,
      threshold: 0.02,
    })
  })

  test('flag.tests.pw.ts / login', async () => {
    const screenshot = fs.readFileSync('/Users/kyle/flagsmith/frontend/e2e/visual-regression-screenshots/flag-tests-pw-ts--login.png')
    expect(screenshot).toMatchSnapshot('flag-tests-pw-ts--login.png', {
      maxDiffPixels: 300,
      threshold: 0.02,
    })
  })

  test('flag.tests.pw.ts / project list', async () => {
    const screenshot = fs.readFileSync('/Users/kyle/flagsmith/frontend/e2e/visual-regression-screenshots/flag-tests-pw-ts--project-list.png')
    expect(screenshot).toMatchSnapshot('flag-tests-pw-ts--project-list.png', {
      maxDiffPixels: 300,
      threshold: 0.02,
    })
  })

  test('initialise.tests.pw.ts / create organisation', async () => {
    const screenshot = fs.readFileSync('/Users/kyle/flagsmith/frontend/e2e/visual-regression-screenshots/initialise-tests-pw-ts--create-organisation.png')
    expect(screenshot).toMatchSnapshot('initialise-tests-pw-ts--create-organisation.png', {
      maxDiffPixels: 300,
      threshold: 0.02,
    })
  })

  test('initialise.tests.pw.ts / signup form', async () => {
    const screenshot = fs.readFileSync('/Users/kyle/flagsmith/frontend/e2e/visual-regression-screenshots/initialise-tests-pw-ts--signup-form.png')
    expect(screenshot).toMatchSnapshot('initialise-tests-pw-ts--signup-form.png', {
      maxDiffPixels: 300,
      threshold: 0.02,
    })
  })

  test('organisation.test.pw.ts / organisation settings', async () => {
    const screenshot = fs.readFileSync('/Users/kyle/flagsmith/frontend/e2e/visual-regression-screenshots/organisation-test-pw-ts--organisation-settings.png')
    expect(screenshot).toMatchSnapshot('organisation-test-pw-ts--organisation-settings.png', {
      maxDiffPixels: 300,
      threshold: 0.02,
    })
  })

  test('project.test.pw.ts / new project features', async () => {
    const screenshot = fs.readFileSync('/Users/kyle/flagsmith/frontend/e2e/visual-regression-screenshots/project-test-pw-ts--new-project-features.png')
    expect(screenshot).toMatchSnapshot('project-test-pw-ts--new-project-features.png', {
      maxDiffPixels: 300,
      threshold: 0.02,
    })
  })

  test('roles.test.pw.ts / users and permissions', async () => {
    const screenshot = fs.readFileSync('/Users/kyle/flagsmith/frontend/e2e/visual-regression-screenshots/roles-test-pw-ts--users-and-permissions.png')
    expect(screenshot).toMatchSnapshot('roles-test-pw-ts--users-and-permissions.png', {
      maxDiffPixels: 300,
      threshold: 0.02,
    })
  })

  test('segment.test.pw.ts / feature identity overrides', async () => {
    const screenshot = fs.readFileSync('/Users/kyle/flagsmith/frontend/e2e/visual-regression-screenshots/segment-test-pw-ts--feature-identity-overrides.png')
    expect(screenshot).toMatchSnapshot('segment-test-pw-ts--feature-identity-overrides.png', {
      maxDiffPixels: 300,
      threshold: 0.02,
    })
  })

  test('segment.test.pw.ts / identity traits', async () => {
    const screenshot = fs.readFileSync('/Users/kyle/flagsmith/frontend/e2e/visual-regression-screenshots/segment-test-pw-ts--identity-traits.png')
    expect(screenshot).toMatchSnapshot('segment-test-pw-ts--identity-traits.png', {
      maxDiffPixels: 300,
      threshold: 0.02,
    })
  })

  test('segment.test.pw.ts / segments list', async () => {
    const screenshot = fs.readFileSync('/Users/kyle/flagsmith/frontend/e2e/visual-regression-screenshots/segment-test-pw-ts--segments-list.png')
    expect(screenshot).toMatchSnapshot('segment-test-pw-ts--segments-list.png', {
      maxDiffPixels: 300,
      threshold: 0.02,
    })
  })

  test('versioning.tests.pw.ts / versioning enabled', async () => {
    const screenshot = fs.readFileSync('/Users/kyle/flagsmith/frontend/e2e/visual-regression-screenshots/versioning-tests-pw-ts--versioning-enabled.png')
    expect(screenshot).toMatchSnapshot('versioning-tests-pw-ts--versioning-enabled.png', {
      maxDiffPixels: 300,
      threshold: 0.02,
    })
  })
})
