# Generated by Django 3.2.23 on 2024-01-11 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('features', '0062_alter_feature_segment_unique_together'),
        ('identities', '0002_alter_identity_index_together'),
        ('multivariate', '0007_alter_boolean_values'),
        ('environments', '0033_add_environment_feature_state_version_logic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionEventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_event_types', to='environments.environment')),
            ],
        ),
        migrations.CreateModel(
            name='SplitTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_count', models.PositiveIntegerField()),
                ('conversion_count', models.PositiveIntegerField()),
                ('pvalue', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversion_event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_tests', to='split_testing.conversioneventtype')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_tests', to='environments.environment')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_tests', to='features.feature')),
                ('multivariate_feature_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='multivariate.multivariatefeatureoption')),
            ],
        ),
        migrations.CreateModel(
            name='ConversionEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_events', to='environments.environment')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_events', to='identities.identity')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_events', to='split_testing.conversioneventtype')),
            ],
        ),
        migrations.AddConstraint(
            model_name='splittest',
            constraint=models.UniqueConstraint(fields=('conversion_event_type', 'feature', 'multivariate_feature_option'), name='unique_cet_feature_mvfo'),
        ),
        migrations.AddConstraint(
            model_name='conversioneventtype',
            constraint=models.UniqueConstraint(fields=('environment', 'name'), name='unique_environment_name'),
        ),
    ]
