# Generated by Django 3.2.16 on 2023-01-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_processor', '0005_update_conditional_index_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='run_every',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
