# Generated by Django 3.2.16 on 2023-02-17 14:09

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('task_processor', '0006_task_run_every'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_for', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('task_identifier', models.CharField(max_length=200)),
                ('serialized_args', models.TextField(blank=True, null=True)),
                ('serialized_kwargs', models.TextField(blank=True, null=True)),
                ('run_every', models.DurationField()),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='run_every',
        ),
        migrations.AddConstraint(
            model_name='recurringtask',
            constraint=models.UniqueConstraint(fields=('task_identifier', 'run_every'), name='unique_run_every_tasks'),
        ),
    ]
