# Generated by Django 3.2.16 on 2023-02-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_processor', '0006_task_run_every'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('completed', False), ('num_failures', 0), ('run_every__isnull', False)), fields=('task_identifier', 'run_every'), name='unique_run_every_tasks'),
        ),
    ]
