# Generated by Django 3.2.18 on 2023-04-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_processor', '0006_auto_20230221_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtask',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
