# Generated by Django 3.2.16 on 2023-02-19 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_processor', '0007_auto_20230217_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringtask',
            name='scheduled_for',
        ),
        migrations.CreateModel(
            name='RecurringTaskRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(blank=True, choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure')], db_index=True, max_length=50, null=True)),
                ('error_details', models.TextField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_runs', to='task_processor.recurringtask')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
