# Generated by Django 3.2.18 on 2023-04-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_processor', '0008_add_get_task_to_process_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtask',
            name='first_run_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
