# Generated by Django 2.2.16 on 2020-09-16 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environments', '0014_auto_20200916_0953'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Identity',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('identifier', models.CharField(max_length=2000)),
                        ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='DateCreated')),
                        ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='environments.Environment')),
                    ],
                    options={
                        'verbose_name_plural': 'Identities',
                        'ordering': ['id'],
                        'unique_together': {('environment', 'identifier')},
                    },
                ),
            ],
            # migrated from environments app which simply renames the table
            database_operations=[]
        )
    ]
