# Generated by Django 4.2.21 on 2025-06-03 22:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins  # type: ignore[import-untyped]
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("environments", "0037_add_uuid_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="SentryChangeTrackingConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("base_url", models.URLField(null=True)),
                ("api_key", models.CharField(max_length=100)),
                ("webhook_url", models.URLField()),
                (
                    "secret",
                    models.CharField(
                        max_length=60,
                        validators=[
                            django.core.validators.MinLengthValidator(10),
                        ],
                    ),
                ),
                (
                    "environment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentry_change_tracking_configuration",
                        to="environments.environment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
