# Generated by Django 5.2.16 on 2026-08-07 11:54

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sentry", "0001_sentry_change_tracking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sentrychangetrackingconfiguration",
            name="base_url",
            field=core.fields.NoSSRFURLField(null=True),
        ),
        migrations.AlterField(
            model_name="sentrychangetrackingconfiguration",
            name="webhook_url",
            field=core.fields.NoSSRFURLField(),
        ),
    ]
