# Generated by Django 2.2.16 on 2020-09-16 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Trait',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True,
                                                serialize=False, verbose_name='ID')),
                        ('trait_key', models.CharField(max_length=200)),
                        ('value_type', models.CharField(blank=True,
                                                        choices=[('int', 'Integer'),
                                                                 ('unicode', 'String'),
                                                                 ('bool', 'Boolean'),
                                                                 ('float', 'Float')],
                                                        default='unicode',
                                                        max_length=10, null=True)),
                        ('boolean_value', models.NullBooleanField()),
                        ('integer_value', models.IntegerField(blank=True, null=True)),
                        ('string_value',
                         models.CharField(blank=True, max_length=2000, null=True)),
                        ('float_value', models.FloatField(blank=True, null=True)),
                        ('created_date', models.DateTimeField(auto_now_add=True,
                                                              verbose_name='DateCreated')),
                        ('identity',
                         models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='identity_traits',
                                           to='identities.Identity')),
                    ],
                    options={
                        'verbose_name_plural': 'User Traits',
                        'ordering': ['id'],
                        'unique_together': {('trait_key', 'identity')},
                        'db_table': 'environments_trait'
                    },
                ),
            ],
            database_operations=[]
        )
    ]
