# Generated by Django 3.2.19 on 2023-06-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='boolean_value',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
