# Generated by Django 5.2.17 on 2026-10-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traits", "0002_alter_trait_boolean_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="trait",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
