# Generated by Django 4.2.22 on 2025-08-12 21:38

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0027_add_create_project_level_change_requests_permission"),
    ]

    operations = [
        migrations.CreateModel(
            name="VCSFeatureFlagCodeReferences",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repository_url", models.URLField()),
                ("revision", models.CharField(max_length=100)),
                ("code_references", models.JSONField(default=list)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_references",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        models.Func(
                            models.F("code_references"),
                            models.Value("$[*].name"),
                            function="jsonb_path_query_array",
                        ),
                        name="code_references_feature_name",
                    )
                ],
            },
        ),
    ]
