# Generated by Django 4.2.22 on 2025-08-14 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0027_add_create_project_level_change_requests_permission"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlagCodeReferencesScan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repository_url", models.URLField()),
                (
                    "vcs_provider",
                    models.CharField(
                        choices=[("github", "GitHub")], default="github", max_length=50
                    ),
                ),
                ("revision", models.CharField(max_length=100)),
                ("code_references", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_references",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
