# Generated by Django 4.2.22 on 2025-08-14 16:51

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("code_references", "0001_code_references"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="featureflagcodereferencesscan",
            index=django.contrib.postgres.indexes.GinIndex(
                models.Func(
                    models.F("code_references"),
                    models.Value("$[*].feature_name"),
                    function="jsonb_path_query_array",
                ),
                name="code_references_feature_name",
            ),
        ),
    ]
