# Generated by Django 5.2.12 on 2026-03-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_references', '0002_add_project_repo_created_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflagcodereferencesscan',
            name='vcs_provider',
            field=models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab')], default='github', max_length=50),
        ),
    ]
