# Generated by Django 5.2.13 on 2026-04-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("code_references", "0002_add_project_repo_created_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featureflagcodereferencesscan",
            name="vcs_provider",
            field=models.CharField(
                choices=[("github", "GitHub"), ("gitlab", "GitLab")],
                default="github",
                max_length=50,
            ),
        ),
    ]
