# Generated by Django 2.2.25 on 2022-01-17 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environments', '0016_webhook_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('secret', models.CharField(blank=True, max_length=255)),
                ('environment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_config', to='environments.Environment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
