# Generated by Django 3.2.12 on 2022-03-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookconfiguration',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
