# Generated by Django 3.2.19 on 2023-06-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0003_webhookconfiguration_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookconfiguration',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
