# Generated by Django 5.2.16 on 2026-08-07 11:54

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webhook", "0004_alter_webhookconfiguration_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhookconfiguration",
            name="url",
            field=core.fields.NoSSRFURLField(),
        ),
    ]
