# Generated by Django 3.2.18 on 2023-03-21 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0033_ffadminuser_sign_up_type'),
        ('permissions', '0007_add_invite_users_and_manage_user_groups_org_permissions'),
        ('environments', '0028_add_use_mv_v2_evaluation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0039_subscription_deleted_at'),
        ('projects', '0016_soft_delete_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('admin', models.BooleanField(default=False)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organisations.organisation')),
                ('permissions', models.ManyToManyField(blank=True, to='permissions.PermissionModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userrole', to='organisation_roles.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoleProjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.BooleanField(default=False)),
                ('permissions', models.ManyToManyField(blank=True, to='permissions.PermissionModel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='rolepermission', to='projects.project')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation_roles.role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoleEnvironmentPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.BooleanField(default=False)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='rolepermission', to='environments.environment')),
                ('permissions', models.ManyToManyField(blank=True, to='permissions.PermissionModel')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation_roles.role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userpermissiongroup')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouprole', to='organisation_roles.role')),
            ],
        ),
    ]
