# Generated by Django 3.2.18 on 2023-03-17 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permissions', '0007_add_invite_users_and_manage_user_groups_org_permissions'),
        ('organisations', '0039_subscription_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organisations.organisation')),
                ('permissions', models.ManyToManyField(blank=True, to='permissions.PermissionModel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
