# Generated by Django 3.2.18 on 2023-03-26 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation_roles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='admin',
        ),
    ]
