# Generated by Django 3.2.18 on 2023-03-30 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0007_add_invite_users_and_manage_user_groups_org_permissions'),
        ('organisations', '0039_subscription_deleted_at'),
        ('organisation_roles', '0002_remove_role_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.CreateModel(
            name='RoleOrganisationPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='rolepermission', to='organisations.organisation')),
                ('permissions', models.ManyToManyField(blank=True, to='permissions.PermissionModel')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation_roles.role')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
