# Generated by Django 5.2.14 on 2026-05-28 11:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0029_bump_default_project_limits"),
    ]

    operations = [
        migrations.CreateModel(
            name="AzureDevOpsConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("organisation_url", models.URLField(max_length=300)),
                ("personal_access_token", models.CharField(max_length=300)),
                ("labeling_enabled", models.BooleanField(default=False)),
                ("tagging_enabled", models.BooleanField(default=False)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="azure_devops_config",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AzureDevOpsServiceHook",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("ado_project_id", models.UUIDField()),
                ("ado_project_name", models.CharField(max_length=200)),
                ("event_type", models.CharField(max_length=64)),
                ("subscription_id", models.UUIDField()),
                ("secret", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_hooks",
                        to="azure_devops.azuredevopsconfiguration",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("configuration", "ado_project_id", "event_type"),
                        name="unique_azure_devops_service_hook_per_event",
                    )
                ],
            },
        ),
    ]
