# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('created_date', models.DateTimeField(auto_now_add=True,
                                                      verbose_name='DateCreated')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                   related_name='projects',
                                                   to='organisations.Organisation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
