# Generated by Django 2.2.24 on 2021-12-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_enable_dynamo_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='enable_dynamo_db',
            field=models.BooleanField(default=False, help_text='If true will sync environment data with dynamodb and allow access to dynamodb identities'),
        ),
    ]
