# Generated by Django 3.2.20 on 2023-07-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0018_add_unique_permission_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="max_features_allowed",
            field=models.IntegerField(
                default=400, help_text="Max features allowed for this project"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="max_segments_allowed",
            field=models.IntegerField(
                default=100, help_text="Max segments allowed for this project"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="max_segments_overrides_allowed",
            field=models.IntegerField(
                default=100,
                help_text="Max segments overrides allowed for any (one) environment within this project",
            ),
        ),
    ]
