# Generated by Django 3.2.23 on 2023-12-07 12:06
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

from projects.models import Project, IdentityOverridesStorageType


def add_defaults(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    project_model_class = apps.get_model("projects", "project")

    project_model_class.objects.all().update(
        identity_overrides_storage_type=IdentityOverridesStorageType.IDENTITY_RECORD
    )


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0020_add_environment_feature_state_version_logic"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="identity_overrides_storage_type",
            field=models.CharField(
                choices=[
                    ("Identity Record", "Identity Record"),
                    ("Flagsmith Overrides", "Flagsmith Overrides"),
                ],
                default=None,
                max_length=50,
                null=True,
            ),
        ),
        migrations.RunPython(add_defaults, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="project",
            name="identity_overrides_storage_type",
            field=models.CharField(
                choices=[
                    ("Identity Record", "Identity Record"),
                    ("Flagsmith Overrides", "Flagsmith Overrides"),
                ],
                default="Identity Record",
                max_length=50,
            ),
        ),
    ]
