# Generated by Django 3.2.23 on 2023-12-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_add_environment_feature_state_version_logic'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stale_flags_limit_days',
            field=models.IntegerField(default=30, help_text='Number of days without modification in any environment before a flag is considered stale.'),
        ),
    ]
