# Generated by Django 3.2.23 on 2023-12-07 12:33
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

from projects.models import IdentityOverridesStorageType


def apply_defaults(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    apps.get_model("projects", "Project").objects.all().update(
        identity_overrides_storage_type=IdentityOverridesStorageType.IDENTITY_RECORD
    )


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0020_add_environment_feature_state_version_logic"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="identity_overrides_storage_type",
            field=models.CharField(
                choices=[
                    ("IDENTITY_RECORD", "Identity Record"),
                    ("FLAGSMITH_OVERRIDES", "Flagsmith Overrides"),
                ],
                default=None,
                max_length=50,
                null=True,
            ),
        ),
        migrations.RunPython(apply_defaults, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="project",
            name="identity_overrides_storage_type",
            field=models.CharField(
                choices=[
                    ("IDENTITY_RECORD", "Identity Record"),
                    ("FLAGSMITH_OVERRIDES", "Flagsmith Overrides"),
                ],
                default="IDENTITY_RECORD",
                max_length=50,
            ),
        ),
    ]
