# Generated by Django 3.2.23 on 2023-12-07 12:33
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

from projects.models import EdgeV2MigrationStatus


def apply_defaults(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    apps.get_model("projects", "Project").objects.all().update(
        identity_overrides_v2_migration_status=EdgeV2MigrationStatus.NOT_STARTED
    )


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0020_add_environment_feature_state_version_logic"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="identity_overrides_v2_migration_status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Not Started"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETE", "Complete"),
                ],
                default=None,
                max_length=50,
                null=True,
            ),
        ),
        migrations.RunPython(apply_defaults, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="project",
            name="identity_overrides_v2_migration_status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Not Started"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETE", "Complete"),
                ],
                default="NOT_STARTED",
                max_length=50,
            ),
        ),
    ]
