# Generated by Django 3.2.23 on 2023-12-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_add_identity_overrides_migration_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='identity_overrides_migration_status',
            new_name='identity_overrides_v2_migration_status',
        ),
    ]
