# Generated by Django 3.2.23 on 2023-12-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_add_identity_overrides_migration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='identity_overrides_v2_migration_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete')], default='COMPLETE', max_length=50),
        ),
    ]
