# Generated by Django 3.2.24 on 2024-02-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_add_stale_flags_threshold_to_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='identity_overrides_v2_migration_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete')], default='COMPLETE', max_length=50),
        ),
    ]
