# Generated by Django 3.2.25 on 2024-05-10 16:53

# sqlmigrate output:
# BEGIN;
# --
# -- Custom state/database change combination
# --
# COMMIT;

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0022_add_stale_flags_threshold_to_project"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameField(
                    model_name="project",
                    old_name="identity_overrides_v2_migration_status",
                    new_name="edge_v2_migration_status",
                ),
                migrations.AlterField(
                    model_name="project",
                    name="edge_v2_migration_status",
                    field=models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETE", "Complete"),
                        ],
                        default="NOT_STARTED",
                        max_length=50,
                        db_column="identity_overrides_v2_migration_status",
                    ),
                ),
            ],
            database_operations=[
                migrations.AlterField(
                    model_name="project",
                    name="identity_overrides_v2_migration_status",
                    field=models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETE", "Complete"),
                        ],
                        default="NOT_STARTED",
                        max_length=50,
                        db_column="identity_overrides_v2_migration_status",
                    ),
                )
            ],
        )
    ]
