# Generated by Django 3.2.25 on 2024-05-03 01:52

# sqlmigrate output:
# BEGIN;
# --
# -- Add field edge_v2_migration_read_capacity_budget to project
# --
# ALTER TABLE "projects_project" ADD COLUMN "edge_v2_migration_read_capacity_budget" integer NULL;
# --
# -- Alter field edge_v2_migration_status on project
# --
# COMMIT;

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0023_rename_identity_overrides_migration_status_keeping_db_column",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="edge_v2_migration_read_capacity_budget",
            field=models.IntegerField(
                default=None,
                help_text="[Edge V2 migration] Read capacity budget override. If project migration was finished with `INCOMPLETE` status, you can set it to a higher value than `EDGE_V2_MIGRATION_READ_CAPACITY_BUDGET` setting before restarting the migration.",
                null=True,
                blank=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="edge_v2_migration_status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Not Started"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETE", "Complete"),
                    ("INCOMPLETE", "Incomplete (identity overrides skipped)"),
                ],
                default="NOT_STARTED",
                help_text="[Edge V2 migration] Project migration status. Set to `IN_PROGRESS` to trigger migration start.",
                max_length=50,
                db_column="identity_overrides_v2_migration_status",
            ),
        ),
    ]
