# Generated by Django 4.2.15 on 2024-09-17 14:07

from common.projects.permissions import (
    APPROVE_PROJECT_LEVEL_CHANGE_REQUESTS,
    MANAGE_PROJECT_LEVEL_CHANGE_REQUESTS,
    PROJECT_PERMISSIONS,
)
from django.db import migrations

from permissions.models import PROJECT_PERMISSION_TYPE


def remove_default_project_permissions(apps, schema_model):  # pragma: no cover
    PermissionModel = apps.get_model("permissions", "PermissionModel")
    PermissionModel.objects.get(key=MANAGE_PROJECT_LEVEL_CHANGE_REQUESTS).delete()
    PermissionModel.objects.get(key=APPROVE_PROJECT_LEVEL_CHANGE_REQUESTS).delete()


def insert_default_project_permissions(apps, schema_model):
    PermissionModel = apps.get_model("permissions", "PermissionModel")

    manage_description = "Ability to manage change requests associated with a project."
    approve_description = "Ability to approve project level change requests."

    PermissionModel.objects.get_or_create(
        key=MANAGE_PROJECT_LEVEL_CHANGE_REQUESTS,
        type=PROJECT_PERMISSION_TYPE,
        defaults={"description": manage_description},
    )
    PermissionModel.objects.get_or_create(
        key=APPROVE_PROJECT_LEVEL_CHANGE_REQUESTS,
        type=PROJECT_PERMISSION_TYPE,
        defaults={"description": approve_description},
    )


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0024_add_project_edge_v2_migration_read_capacity_budget"),
    ]

    operations = [
        migrations.RunPython(
            insert_default_project_permissions,
            reverse_code=remove_default_project_permissions,
        ),
    ]
