# Generated by Django 4.2.15 on 2024-09-17 14:07

from common.projects.permissions import (  
    CREATE_PROJECT_LEVEL_CHANGE_REQUESTS
)
from django.db import migrations
from django.apps.registry import Apps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

from permissions.models import PROJECT_PERMISSION_TYPE


def remove_default_project_permissions(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:  # pragma: no cover
    PermissionModel = apps.get_model("permissions", "PermissionModel")
    PermissionModel.objects.get(key=CREATE_PROJECT_LEVEL_CHANGE_REQUESTS).delete()


def insert_default_project_permissions(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None: 
    PermissionModel = apps.get_model("permissions", "PermissionModel")

    description = "Ability to create project level change requests."

    PermissionModel.objects.get_or_create(
        key=CREATE_PROJECT_LEVEL_CHANGE_REQUESTS,
        type=PROJECT_PERMISSION_TYPE,
        defaults={"description": description},
    )


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0026_add_change_request_approval_limit_to_projects"),
    ]

    operations = [
        migrations.RunPython(
            insert_default_project_permissions,
            reverse_code=remove_default_project_permissions,
        ),
    ]
