# Generated by Django 5.2.11 on 2026-03-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0027_add_create_project_level_change_requests_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="enforce_feature_owners",
            field=models.BooleanField(
                default=False,
                help_text="Require at least one user or group owner when creating a feature.",
            ),
        ),
    ]
