# Generated by Django 5.2.13 on 2026-04-24 08:28

from django.db import migrations, models


def bump_project_limits(apps, schema_editor):  # type: ignore[no-untyped-def]
    Project = apps.get_model("projects", "Project")
    Project.objects.filter(max_features_allowed__lt=1000).update(
        max_features_allowed=1000
    )
    Project.objects.filter(max_segments_allowed__lt=500).update(
        max_segments_allowed=500
    )
    Project.objects.filter(max_segment_overrides_allowed__lt=2000).update(
        max_segment_overrides_allowed=2000
    )


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0028_add_enforce_feature_owners_to_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="max_features_allowed",
            field=models.IntegerField(
                default=1000, help_text="Max features allowed for this project"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="max_segment_overrides_allowed",
            field=models.IntegerField(
                default=2000,
                help_text="Max segments overrides allowed for any (one) environment within this project",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="max_segments_allowed",
            field=models.IntegerField(
                default=500, help_text="Max segments allowed for this project"
            ),
        ),
        migrations.RunPython(
            bump_project_limits, reverse_code=migrations.RunPython.noop
        ),
    ]
