# Generated by Django 5.2.16 on 2026-08-07 11:54

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("segment", "0006_set_base_url_to_default_again"),
    ]

    operations = [
        migrations.AlterField(
            model_name="segmentconfiguration",
            name="base_url",
            field=core.fields.NoSSRFURLField(null=True),
        ),
    ]
