# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_ffadminuser_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ffadminuser',
            name='organisation',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='users',
                                    to='api.Organisation'),
        ),
    ]
