# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 16:59
from __future__ import unicode_literals

from django.db import migrations

import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_auto_20180518_1655"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="ffadminuser",
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
    ]
