# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180522_0931'),
        ('users', '0008_auto_20180522_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='ffadminuser',
            name='organisations',
            field=models.ManyToManyField(blank=True, related_name='users', to='api.Organisation'),
        ),
    ]
