# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180522_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ffadminuser',
            name='organisation',
        ),
    ]
