# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_invite_frontend_base_url'),
        ('organisations', '0001_initial')
    ]

    operations = [
        migrations.AlterField(
            model_name='ffadminuser',
            name='organisations',
            field=models.ManyToManyField(blank=True, related_name='users',
                                         to='organisations.Organisation'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='organisations.Organisation'),
        ),
    ]
