# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 13:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20180524_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='invited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to=settings.AUTH_USER_MODEL),
        ),
    ]
