# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-22 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_invite_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ffadminuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
