# Generated by Django 2.2.10 on 2020-02-16 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20191122_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ffadminuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.CreateModel(
            name='UserPermissionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_groups', to='organisations.Organisation')),
                ('users', models.ManyToManyField(related_name='permission_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
