# Generated by Django 2.2.24 on 2021-12-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20210223_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='ffadminuser',
            name='is_subscribed',
            field=models.BooleanField(default=False, help_text='Determines whether the user is subscribed to the mailing list or not'),
        ),
    ]
