# Generated by Django 2.2.25 on 2022-01-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20210223_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='ffadminuser',
            name='has_agreed_to_marketing',
            field=models.BooleanField(default=False, help_text='Determines whether the user is has aggreg or not'),
        ),
    ]
