# Generated by Django 3.2.20 on 2023-08-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_add_user_permission_group_membership_through_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='ffadminuser',
            name='last_password_reset_email_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ffadminuser',
            name='num_of_password_reset_emails_sent',
            field=models.IntegerField(default=0),
        ),
    ]
