# Generated by Django 3.2.25 on 2024-08-12 14:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_create_hubspot_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='ffadminuser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
