# Generated by Django 4.2.16 on 2024-11-05 10:49

from pathlib import Path
from django.db import migrations, models


def _get_ffadminuser_table_name() -> str:
    from users.models import FFAdminUser

    return FFAdminUser._meta.db_table


_ffadminuser_table_name = _get_ffadminuser_table_name()


parent_dir = Path(__file__).parent.resolve()

with open(parent_dir / "sql/0039_ffadminuser_first_name_v2.sql") as f:
    sql_forwards = f.read().format(ffadminuser_table_name=_ffadminuser_table_name)

with open(parent_dir / "sql/0039_ffadminuser_first_name_v2_reverse.sql") as f:
    sql_reverse = f.read().format(ffadminuser_table_name=_ffadminuser_table_name)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0038_create_hubspot_tracker"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="ffadminuser",
                    name="first_name",
                ),
                migrations.AddField(
                    model_name="ffadminuser",
                    name="first_name",
                    field=models.CharField(
                        db_column="first_name_v2",
                        max_length=150,
                        verbose_name="first name",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=sql_forwards,
                    reverse_sql=sql_reverse,
                )
            ],
        )
    ]
