# Generated by Django 4.2.16 on 2024-11-04 17:09
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0038_create_hubspot_tracker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ffadminuser",
            name="first_name",
            field=models.CharField(max_length=150, verbose_name="first name"),
        ),
    ]
