"""
This migration exists because 0039 was retrospectively fixed to prevent locking issues
on the users table. This migration ensures that:

 1. in environments where 0039 was run before the fix was added, the new column is
    correctly added to the database to match what the ORM expects and the data
    is correctly migrted to the new column.
 2. in environments where 0039 was run after the fix was added, nothing happens.

Note that we only need to care about Postgres databases here because we did not release
the bad migration for 0039 in a format that can be consumed by oracle / mysql.
"""

# Generated by Django 4.2.16 on 2024-11-12 18:05
import logging

from django.db import migrations

from core.migration_helpers import PostgresOnlyRunSQL

forwards_sql = """
DO
$do$
BEGIN
   IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='users_ffadminuser' and column_name='first_name_v2') THEN
      ALTER TABLE "users_ffadminuser" ADD COLUMN "first_name_v2" VARCHAR(150) NOT NULL DEFAULT '';
      UPDATE "users_ffadminuser" SET "first_name_v2" = "first_name"; 
   END IF;
END
$do$
"""


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0039_alter_ffadminuser_first_name"),
    ]

    operations = [
        PostgresOnlyRunSQL(forwards_sql, reverse_sql=""),
    ]
