# Generated by Django 4.2.18 on 2025-05-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0039_alter_ffadminuser_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ffadminuser",
            name="marketing_consent_given",
            field=models.BooleanField(
                default=True,
                help_text="Determines whether the user has agreed to receive marketing mails",
            ),
        ),
    ]
