# Generated by Django 4.2.21 on 2025-06-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0040_default_marketing_consent_given_true"),
    ]

    operations = [
        migrations.AddField(
            model_name="ffadminuser",
            name="onboarding",
            field=models.TextField(blank=True, null=True),
        ),
    ]
