# Generated by Django 4.2.22 on 2025-06-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0041_add_onboarding_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="hubspottracker",
            name="utm_campaign",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="hubspottracker",
            name="utm_content",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="hubspottracker",
            name="utm_medium",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="hubspottracker",
            name="utm_source",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="hubspottracker",
            name="utm_term",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
