# Generated by Django 4.2.22 on 2025-06-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0042_add_utm_fields_to_hubspottracker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hubspottracker",
            name="hubspot_cookie",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
