# Generated by Django 4.2.22 on 2025-07-30 17:42
import structlog
from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.models import F


logger = structlog.get_logger()


def remove_users_from_groups(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    user_permission_group_membership_model = apps.get_model("users", "UserPermissionGroupMembership")
    queryset = user_permission_group_membership_model.objects.exclude(
        ffadminuser__organisations=F("userpermissiongroup__organisation")
    )
    logger.info("Removing orphan group memberships.", num_orphan_memberships=queryset.count())
    queryset.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0043_make_hubspot_cookie_optional"),
    ]

    operations = [
        migrations.RunPython(remove_users_from_groups, reverse_code=migrations.RunPython.noop),
    ]
