# Generated by Django 5.2.9 on 2025-12-31 15:38
# Note: This migration is a no-op, and just adds the `through_fields` attribute
# seemingly needed by the state in django5


from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0044_remove_users_from_groups_in_orgs_they_do_not_belong_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpermissiongroup",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="permission_groups",
                through="users.UserPermissionGroupMembership",
                through_fields=["userpermissiongroup", "ffadminuser"],  # type: ignore[arg-type]
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
