# Generated by Django 4.2.16 on 2024-11-05 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organisations", "0058_update_audit_and_history_limits_in_sub_cache"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationLicence",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField(blank=True)),
                (
                    "organisation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licence",
                        to="organisations.organisation",
                    ),
                ),
            ],
        ),
    ]
