# Generated by Django 5.2.16 on 2026-08-04 04:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("environments", "0038_add_first_evaluated_fields"),
        ("segments", "0030_add_default_to_segment_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cohort",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("csv", "CSV")], default="csv", max_length=50
                    ),
                ),
                ("version", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cohorts",
                        to="environments.environment",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cohorts",
                        to="segments.segment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CohortMembership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=2000)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending_add", "Pending add"),
                            ("applied", "Applied"),
                            ("pending_remove", "Pending remove"),
                        ],
                        default="pending_add",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="cohorts.cohort",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["cohort", "state"],
                        name="cohorts_coh_cohort__a03158_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cohort", "identifier"),
                        name="unique_cohort_membership_identifier",
                    )
                ],
            },
        ),
    ]
