# Generated by Django 5.2.16 on 2026-08-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cohorts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cohort",
            name="deletion_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
