# Generated by Django 5.2.16 on 2026-08-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cohorts", "0003_cohort_sync_key"),
        ("environments", "0039_use_no_ssrf_url_field"),
        ("segments", "0032_add_segment_rules_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="cohort",
            name="external_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cohort",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("csv", "CSV"),
                    ("amplitude", "Amplitude"),
                    ("mixpanel", "Mixpanel"),
                ],
                default="csv",
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="cohort",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True), ("external_id__isnull", False)
                ),
                fields=("environment", "source_type", "external_id"),
                name="unique_active_cohort_per_source_external_id",
            ),
        ),
    ]
