# Feature state types
FEATURE_SEGMENT = "FEATURE_SEGMENT"
IDENTITY = "IDENTITY"
ENVIRONMENT = "ENVIRONMENT"

# Feature state statuses
COMMITTED = "COMMITTED"
DRAFT = "DRAFT"

# Tag filtering strategy
UNION = "UNION"
INTERSECTION = "INTERSECTION"

STALE_FLAGS_TAG_LABEL = "Stale"
