# Feature state types
FEATURE_SEGMENT = "FEATURE_SEGMENT"
IDENTITY = "IDENTITY"
ENVIRONMENT = "ENVIRONMENT"

# Feature state statuses
COMMITTED = "COMMITTED"
DRAFT = "DRAFT"

# Tag filtering strategy
UNION = "UNION"
INTERSECTION = "INTERSECTION"

MAX_32_BIT_INTEGER = 2_147_483_647
