# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 15:41
from __future__ import unicode_literals

import app.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('created_date', models.DateTimeField(auto_now_add=True,
                                                      verbose_name='DateCreated')),
                ('api_key', models.CharField(default=app.utils.create_hash, max_length=100,
                                             unique=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='environments', to='projects.Project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('identifier', models.CharField(max_length=2000)),
                ('created_date', models.DateTimeField(auto_now_add=True,
                                                      verbose_name='DateCreated')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                  related_name='identities',
                                                  to='environments.Environment')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': 'Identities',
            },
        ),
    ]
