# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-09 00:14
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("environments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="environment",
            name="project",
            field=models.ForeignKey(
                help_text="Changing the project selected will remove all previous Feature States for the previously associated projects Features that are related to this Environment. New default Feature States will be created for the new selected projects Features for this Environment.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="environments",
                to="projects.Project",
            ),
        ),
    ]
