# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0002_auto_20180809_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='webhook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='webhooks_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
