# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0004_auto_20181026_1438'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='identity',
            unique_together=set([('environment', 'identifier')]),
        ),
    ]
