# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-27 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0006_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='environment',
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
