# Generated by Django 2.2.10 on 2020-02-20 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
        ('environments', '0010_auto_20200219_2343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnvironmentPermission',
        ),
        migrations.AlterField(
            model_name='userenvironmentpermission',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='userpermission', to='environments.Environment'),
        ),
        migrations.AlterField(
            model_name='userenvironmentpermission',
            name='permissions',
            field=models.ManyToManyField(to='permissions.PermissionModel'),
        ),
        migrations.AlterField(
            model_name='userpermissiongroupenvironmentpermission',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='grouppermission', to='environments.Environment'),
        ),
        migrations.AlterField(
            model_name='userpermissiongroupenvironmentpermission',
            name='permissions',
            field=models.ManyToManyField(to='permissions.PermissionModel'),
        ),
        migrations.CreateModel(
            name='EnvironmentPermission',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('permissions.permissionmodel',),
        ),
    ]
