# Generated by Django 2.2.25 on 2022-01-11 17:52

from django.db import migrations, models
import django.db.models.deletion
import environments.api_keys


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0015_auto_20200916_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='api_key',
            field=models.CharField(default=environments.api_keys.generate_client_api_key, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='EnvironmentAPIKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=environments.api_keys.generate_server_api_key, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='environments.Environment')),
            ],
        ),
    ]
