# Generated by Django 2.2.24 on 2021-12-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0015_auto_20200916_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='secret',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
