# Generated by Django 3.2.12 on 2022-03-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0017_add_environment_api_key_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='minimum_change_request_approvals',
            field=models.IntegerField(null=True),
        ),
    ]
