# Generated by Django 3.2.12 on 2022-05-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0018_add_minimum_change_request_approvals_to_environment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='minimum_change_request_approvals',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
