# Generated by Django 3.2.13 on 2022-06-22 15:52

from django.db import migrations, models
import uuid

from core.migration_helpers import AddDefaultUUIDs


class Migration(migrations.Migration):

    dependencies = [
        ("environments", "0019_allow_blank_minimum_change_request_approvals"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhook",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(
            AddDefaultUUIDs("environments", "webhook"),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="webhook",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
