# Generated by Django 3.2.14 on 2022-07-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0021_environment_allow_client_traits'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='description',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
    ]
