# Generated by Django 3.2.16 on 2022-11-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0023_environment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
    ]
