# Generated by Django 3.2.16 on 2022-12-01 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import environments.api_keys
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_soft_delete_projects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_keys', '0002_soft_delete_api_keys'),
        ('environments', '0024_soft_delete_environments'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEnvironment',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('name', models.CharField(max_length=2000)),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='DateCreated')),
                ('description', models.TextField(blank=True, max_length=20000, null=True)),
                ('api_key', models.CharField(db_index=True, default=environments.api_keys.generate_client_api_key, max_length=100)),
                ('minimum_change_request_approvals', models.IntegerField(blank=True, null=True)),
                ('webhooks_enabled', models.BooleanField(default=False, help_text='DEPRECATED FIELD.')),
                ('webhook_url', models.URLField(blank=True, help_text='DEPRECATED FIELD.', null=True)),
                ('allow_client_traits', models.BooleanField(default=True, help_text='Allows clients using the client API key to set traits.')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Tracks changes to self and related entities, e.g. FeatureStates.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('master_api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_keys.masterapikey')),
                ('project', models.ForeignKey(blank=True, db_constraint=False, help_text='Changing the project selected will remove all previous Feature States for the previously associated projects Features that are related to this Environment. New default Feature States will be created for the new selected projects Features for this Environment.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project')),
            ],
            options={
                'verbose_name': 'historical environment',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
