# Generated by Django 3.2.16 on 2022-12-11 15:56
from django.db import migrations, models
from django.db.models import Subquery, OuterRef

# from django.db.models import F


def copy_hide_disabled_flags_config_from_project(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    Environment = apps.get_model("environments", "Environment")
    Environment.objects.all().update(
        hide_disabled_flags=Subquery(
            Environment.objects.filter(pk=OuterRef("pk")).values(
                "project__hide_disabled_flags"
            )[:1]
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ("environments", "0024_auto_20221206_0601"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="hide_disabled_flags",
            field=models.BooleanField(
                default=False,
                help_text="If true will exclude flags from SDK which are disabled. NOTE: This will override the project setting.",
            ),
        ),
        migrations.RunPython(
            copy_hide_disabled_flags_config_from_project,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
