# Generated by Django 3.2.16 on 2023-01-05 03:01

from django.db.models import Subquery, OuterRef
from django.db import migrations, models


def copy_hide_disabled_flags_config_from_project(apps, schema_editor):
    Environment = apps.get_model("environments", "Environment")
    Environment.objects.all().update(
        hide_disabled_flags=Subquery(
            Environment.objects.filter(pk=OuterRef("pk")).values(
                "project__hide_disabled_flags"
            )[:1]
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ("environments", "0026_add_auditable_base_class_to_environment_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="hide_disabled_flags",
            field=models.BooleanField(
                default=False,
                help_text="If true will exclude flags from SDK which are disabled. NOTE: For this to work you must enable hide_disabled flags for the project",
            ),
        ),
        migrations.AddField(
            model_name="historicalenvironment",
            name="hide_disabled_flags",
            field=models.BooleanField(
                default=False,
                help_text="If true will exclude flags from SDK which are disabled. NOTE: For this to work you must enable hide_disabled flags for the project",
            ),
        ),
        migrations.RunPython(
            copy_hide_disabled_flags_config_from_project,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
