# Generated by Django 3.2.16 on 2023-02-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0027_auto_20230106_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='use_mv_v2_evaluation',
            field=models.BooleanField(default=False, help_text='Enable this to have consistent multivariate evaluations across all SDKs. '),
        ),
        migrations.AddField(
            model_name='historicalenvironment',
            name='use_mv_v2_evaluation',
            field=models.BooleanField(default=False, help_text='Enable this to have consistent multivariate evaluations across all SDKs. '),
        ),
    ]
