# Generated by Django 3.2.18 on 2023-05-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("environments", "0029_auto_20230314_0443"),
    ]

    operations = [
        migrations.AlterField(
            model_name="environment",
            name="hide_sensitive_data",
            field=models.BooleanField(
                default=False,
                help_text="If true, will hide sensitive data(e.g: traits, description etc) from the SDK endpoints",
            ),
        ),
        migrations.AlterField(
            model_name="historicalenvironment",
            name="hide_sensitive_data",
            field=models.BooleanField(
                default=False,
                help_text="If true, will hide sensitive data(e.g: traits, description etc) from the SDK endpoints",
            ),
        ),
    ]
