# Generated by Django 3.2.19 on 2023-06-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0030_auto_20230518_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
