# Generated by Django 3.2.19 on 2023-06-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0031_alter_webhook_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='use_v2_feature_versioning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalenvironment',
            name='use_v2_feature_versioning',
            field=models.BooleanField(default=False),
        ),
    ]
