# Generated by Django 3.2.23 on 2023-11-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0032_rename_use_mv_v2_evaluation_to_use_in_percentage_split_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='use_v2_feature_versioning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalenvironment',
            name='use_v2_feature_versioning',
            field=models.BooleanField(default=False),
        ),
    ]
