# Generated by Django 3.2.20 on 2023-10-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0032_rename_use_mv_v2_evaluation_to_use_in_percentage_split_evaluation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalenvironment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical environment', 'verbose_name_plural': 'historical environments'},
        ),
        migrations.AlterField(
            model_name='historicalenvironment',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
