# Generated by Django 3.2.25 on 2024-05-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0034_alter_environment_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='is_creating',
            field=models.BooleanField(default=False, help_text='Attribute used to indicate when an environment is still being created (via clone for example)'),
        ),
        migrations.AddField(
            model_name='historicalenvironment',
            name='is_creating',
            field=models.BooleanField(default=False, help_text='Attribute used to indicate when an environment is still being created (via clone for example)'),
        ),
    ]
