# Generated by Django 3.2.25 on 2024-08-13 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0034_alter_environment_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentTraitMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trait_key', models.CharField(max_length=200)),
                ('is_searchable', models.BooleanField(default=False)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trait_meta_items', to='environments.environment')),
            ],
        ),
    ]
