# Generated by Django 4.2.15 on 2024-10-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("environments", "0035_add_use_identity_overrides_in_local_eval"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="is_creating",
            field=models.BooleanField(
                default=False,
                help_text="Attribute used to indicate when an environment is still being created (via clone for example)",
            ),
        ),
        migrations.AddField(
            model_name="historicalenvironment",
            name="is_creating",
            field=models.BooleanField(
                default=False,
                help_text="Attribute used to indicate when an environment is still being created (via clone for example)",
            ),
        ),
    ]
