# Generated by Django 3.2.23 on 2024-11-27 08:46

from django.db import migrations, models
import uuid

from core.migration_helpers import AddDefaultUUIDs


class Migration(migrations.Migration):
    dependencies = [
        ("environments", "0036_add_is_creating_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="uuid",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(
            AddDefaultUUIDs("environments", "environment"),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="environment",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
