# Generated by Django 5.2.16 on 2026-07-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("environments", "0037_add_uuid_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="first_evaluated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the environment's flags were first evaluated by an SDK.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="environment",
            name="first_evaluated_sdk_label",
            field=models.CharField(
                blank=True,
                help_text="SDK that first evaluated the environment's flags.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalenvironment",
            name="first_evaluated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the environment's flags were first evaluated by an SDK.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalenvironment",
            name="first_evaluated_sdk_label",
            field=models.CharField(
                blank=True,
                help_text="SDK that first evaluated the environment's flags.",
                max_length=100,
                null=True,
            ),
        ),
    ]
