# Generated by Django 5.2.16 on 2026-08-07 11:54

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("environments", "0038_add_first_evaluated_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhook",
            name="url",
            field=core.fields.NoSSRFURLField(),
        ),
    ]
