HUBSPOT_COOKIE_NAME = "hubspotutk"
HUBSPOT_PORTAL_ID = "143451822"
HUBSPOT_FORM_ID = "562ee023-fb3f-4645-a217-4d8c9b4e45be"
HUBSPOT_ROOT_FORM_URL = "https://api.hsforms.com/submissions/v3/integration/submit"
HUBSPOT_API_LEAD_SOURCE_SELF_HOSTED = "self-hosted"
HUBSPOT_ACTIVE_SUBSCRIPTION_SELF_HOSTED = "free-opensource"
