# Generated by Django 4.2.15 on 2024-09-03 09:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0024_add_project_edge_v2_migration_read_capacity_budget"),
        ("organisations", "0056_create_organisation_breached_grace_period"),
        ("grafana", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameModel(
                    old_name="GrafanaConfiguration",
                    new_name="GrafanaProjectConfiguration",
                ),
                migrations.AlterModelTable(
                    name="grafanaprojectconfiguration",
                    table="grafana_grafanaconfiguration",
                ),
            ]
        ),
        migrations.CreateModel(
            name="GrafanaOrganisationConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("base_url", models.URLField(null=True)),
                ("api_key", models.CharField(max_length=100)),
                (
                    "organisation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grafana_config",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
