# Generated by Django 5.2.16 on 2026-08-07 11:54

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grafana", "0002_add_grafana_organisation_configuration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grafanaorganisationconfiguration",
            name="base_url",
            field=core.fields.NoSSRFURLField(null=True),
        ),
        migrations.AlterField(
            model_name="grafanaprojectconfiguration",
            name="base_url",
            field=core.fields.NoSSRFURLField(null=True),
        ),
    ]
