# Generated by Django 2.2.13 on 2020-07-14 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0009_auto_20200714_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDogConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField()),
                ('api_key', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_dog_config', to='projects.Project')),
            ],
        ),
    ]
