# Generated by Django 2.2.14 on 2020-07-16 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datadog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadogconfiguration',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_dog_config', to='projects.Project'),
        ),
    ]
