# Generated by Django 3.2.23 on 2023-11-29 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environments', '0033_add_environment_feature_state_version_logic'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('SKIP', 'Skip'), ('OVERWRITE_DESTRUCTIVE', 'Overwrite Destructive')], max_length=50)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('PROCESSING', 'Processing'), ('FAILED', 'Failed')], default='PROCESSING', max_length=50)),
                ('data', models.CharField(max_length=1000000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_exports', to='environments.environment')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=1000000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_imports', to='environments.environment')),
            ],
        ),
    ]
