# Generated by Django 3.2.23 on 2023-12-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features_import_export', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureexport',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('PROCESSING', 'Processing'), ('FAILED', 'Failed')], default='PROCESSING', max_length=50),
        ),
        migrations.AlterField(
            model_name='featureexport',
            name='data',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
    ]
