# Generated by Django 3.2.23 on 2023-12-12 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features_import_export', '0002_status_and_data_featureexport'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlagsmithOnFlagsmithFeatureExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature_export', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagsmith_on_flagsmith', to='features_import_export.featureexport')),
            ],
        ),
    ]
