# Generated by Django 3.2.25 on 2024-04-04 17:07

from django.db import migrations, models

from features.import_export.constants import (
    MAX_FEATURE_EXPORT_SIZE,
    MAX_FEATURE_IMPORT_SIZE,
)


class Migration(migrations.Migration):

    dependencies = [
        ("features_import_export", "0003_flagsmithonflagsmithfeatureexport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featureexport",
            name="data",
            field=models.TextField(
                blank=True, max_length=MAX_FEATURE_EXPORT_SIZE, null=True
            ),
        ),
        migrations.AlterField(
            model_name="featureimport",
            name="data",
            field=models.TextField(max_length=MAX_FEATURE_IMPORT_SIZE),
        ),
    ]
