# Generated by Django 3.2.23 on 2024-03-04 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('features', '0062_alter_feature_segment_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('type', models.TextField()),
                ('status', models.TextField(null=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='features.feature')),
            ],
            options={
                'ordering': ('id',),
                'unique_together': {('url',)},
            },
        ),
    ]
