# Generated by Django 3.2.23 on 2024-01-29 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0020_add_environment_feature_state_version_logic'),
        ('features', '0062_alter_feature_segment_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('type', models.TextField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='FeatureExternalResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featureexternalresources', to='external_resources.externalresources')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.feature')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='externalresources',
            name='feature_external_resource',
            field=models.ManyToManyField(blank=True, through='external_resources.FeatureExternalResources', to='features.Feature'),
        ),
        migrations.AddField(
            model_name='externalresources',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_resource', to='projects.project'),
        ),
        migrations.AlterUniqueTogether(
            name='externalresources',
            unique_together={('url', 'project')},
        ),
    ]
