# Generated by Django 3.2.23 on 2024-01-29 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('external_resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='externalresources',
            unique_together={('url',)},
        ),
    ]
