# Generated by Django 3.2.24 on 2024-02-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalresources',
            name='status',
            field=models.TextField(null=True),
        ),
    ]
