# Generated by Django 3.2.25 on 2024-04-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalresources',
            name='status',
            field=models.CharField(choices=[('1', 'open'), ('2', 'closed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='externalresources',
            name='type',
            field=models.CharField(choices=[('1', 'github')], max_length=20),
        ),
    ]
