# Generated by Django 3.2.23 on 2024-01-31 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_resources', '0002_alter_externalresources_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalresources',
            name='resources_id',
            field=models.TextField(null=True),
        ),
    ]
