# Generated by Django 3.2.25 on 2024-04-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_resources', '0002_auto_20240408_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalresources',
            name='type',
            field=models.CharField(choices=[('1', 'Github PR'), ('2', 'Github Issue')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='externalresources',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='externalresources',
            constraint=models.UniqueConstraint(fields=('url',), name='unique_url_constraint'),
        ),
    ]
