# Generated by Django 3.2.23 on 2024-01-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_resources', '0003_externalresources_resources_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalresources',
            name='resources_id',
            field=models.TextField(),
        ),
    ]
