# Generated by Django 2.2.15 on 2020-09-14 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permissions', '0002_auto_20200221_2126'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0027_ffadminuser_github_user_id'),
        ('environments', '0013_auto_20200914_0911'),
    ]

    operations = [
        # split the database operations since we're moving the model from environments app
        # to do so, we simply rename the table in migration 0013 of the environments app and
        # update the state here
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='UserPermissionGroupEnvironmentPermission',
                    fields=[
                        ('id',
                         models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('admin', models.BooleanField(default=False)),
                        ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                          related_query_name='grouppermission',
                                                          to='environments.Environment')),
                        ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                    to='users.UserPermissionGroup')),
                        ('permissions', models.ManyToManyField(blank=True, to='permissions.PermissionModel')),
                    ],
                    options={
                        'abstract': False,
                    },
                ),
                migrations.CreateModel(
                    name='UserEnvironmentPermission',
                    fields=[
                        ('id',
                         models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('admin', models.BooleanField(default=False)),
                        ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                          related_query_name='userpermission',
                                                          to='environments.Environment')),
                        ('permissions', models.ManyToManyField(blank=True, to='permissions.PermissionModel')),
                        ('user',
                         models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'abstract': False,
                    },
                ),
            ],
            database_operations=[]
        ),
        migrations.CreateModel(
            # Proxy model don't need state / db splitting out
            name='EnvironmentPermissionModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('permissions.permissionmodel',),
        ),
    ]
