# Generated by Django 3.2.18 on 2023-06-19 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0039_subscription_deleted_at'),
        ('organisation_permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorganisationpermission',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='userpermission', to='organisations.organisation'),
        ),
        migrations.AlterField(
            model_name='userpermissiongrouporganisationpermission',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='grouppermission', to='organisations.organisation'),
        ),
    ]
