# Generated by Django 3.2.18 on 2023-06-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation_permissions', '0002_add_related_query_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userorganisationpermission',
            constraint=models.UniqueConstraint(fields=('user', 'organisation'), name='unique_user_organisation_permission'),
        ),
        migrations.AddConstraint(
            model_name='userpermissiongrouporganisationpermission',
            constraint=models.UniqueConstraint(fields=('group', 'organisation'), name='unique_group_organisation_permission'),
        ),
    ]
