name: Task Processor Deploy to ECS
description: Deploy the Flagsmith Task Processor to ECS

inputs:
  aws_access_key_id:
    description: The AWS access key ID to use for deploying to ECS.
    required: true
  aws_secret_access_key:
    description: The AWS secret access key to use for deploying to ECS.
    required: true
  aws_ecs_cluster_name:
    description: The name of the ECS cluster to deploy to.
    required: true
  aws_ecs_service_name:
    description: The name of the ECS service to deploy to.
    required: true
  aws_task_definitions_directory_path:
    description: The local path in the repository to the json file containing the task definition template
    required: true
  api_ecr_image_url:
    description: The ECR URL of the latest API image.
    required: true

runs:
  using: composite

  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        aws-region: eu-west-2

    - name: Fill in the new image ID in the Amazon ECS Task Processor task definition
      id: task-def-task-processor
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ inputs.aws_task_definitions_directory_path }}/ecs-task-definition-task-processor.json
        container-name: flagsmith-task-processor
        image: ${{ inputs.api_ecr_image_url }}

    - name: Deploy Amazon ECS Task Processor task definition
      id: deploy-task-processor-task-def
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        cluster: ${{ inputs.aws_ecs_cluster_name }}
        service: ${{ inputs.aws_ecs_service_name }}
        task-definition: ${{ steps.task-def-task-processor.outputs.task-definition }}

    - name: Wait for service to be stable
      run:
        aws ecs wait services-stable --cluster ${{ inputs.aws_ecs_cluster_name }} --services ${{
        inputs.aws_ecs_service_name }}
      shell: bash

    - name: Verify correct version is running
      shell: bash
      run: |
        EXPECTED_TASK_DEF=${{ steps.deploy-task-processor-task-def.outputs.task-definition-arn }}
        RUNNING_TASK_DEF=$(aws ecs describe-services \
          --cluster ${{ inputs.aws_ecs_cluster_name }} \
          --services ${{ inputs.aws_ecs_service_name }} \
          --query 'services[0].deployments[?status==`PRIMARY`].taskDefinition' \
          --output text)
        if [[ "$RUNNING_TASK_DEF" == "$EXPECTED_TASK_DEF" && ]]; then
          exit 0
        else
          echo "Task definition mismatch detected"
          echo "Expected: $EXPECTED_TASK_DEF"
          echo "Task Processor running: $RUNNING_TASK_DEF"
          exit 1
        fi
