# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environments', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('created_date', models.DateTimeField(auto_now_add=True,
                                                      verbose_name='DateCreated')),
                ('initial_value', models.CharField(default=None, max_length=2000, null=True)),
                ('description', models.TextField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='features', to='projects.Project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FeatureState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('enabled', models.BooleanField()),
                ('value', models.CharField(max_length=2000, null=True)),
                ('environment', models.ForeignKey(null=True,
                                                  on_delete=django.db.models.deletion.CASCADE,
                                                  related_name='feature_states',
                                                  to='environments.Environment')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='feature_states',
                                              to='features.Feature')),
                ('identity', models.ForeignKey(default=None, null=True,
                                               on_delete=django.db.models.deletion.CASCADE,
                                               related_name='identity_features',
                                               to='environments.Identity')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='featurestate',
            unique_together=set([('feature', 'environment', 'identity')]),
        ),
    ]
