# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureStateValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Integer', 'Integer'), ('String', 'String'), ('Boolean', 'Boolean')], default='String', max_length=10)),
                ('boolean_value', models.NullBooleanField()),
                ('integer_value', models.IntegerField(null=True)),
                ('string_value', models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='featurestate',
            name='value',
        ),
        migrations.AddField(
            model_name='featurestatevalue',
            name='feature_state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feature_state_value', to='features.FeatureState'),
        ),
    ]
