# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 12:59
from __future__ import unicode_literals

from django.db import migrations


def delete_existing_non_unique_features(apps, schema_editor):
    feature_model = apps.get_model("features", "Feature")
    for feature in feature_model.objects.all():
        clashing_features = feature_model.objects.filter(name__iexact=feature.name,
                                                         project=feature.project)
        if clashing_features.count() > 1:
            i = 0
            for clashing_feature in clashing_features:
                suffix = "_" + str(i)
                clashing_feature.name = clashing_feature.name + suffix if i > 0 else clashing_feature.name
                clashing_feature.save()
                i += 1


def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('features', '0003_auto_20180601_1038'),
    ]

    operations = [
        migrations.RunPython(delete_existing_non_unique_features,
                             reverse_migration),
        migrations.AlterUniqueTogether(
            name='feature',
            unique_together=set([('name', 'project')]),
        ),
    ]
