# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-09 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0008_auto_20180608_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='project',
            field=models.ForeignKey(help_text='Changing the project selected will remove previous Feature States for the previously associated projects Environments that are related to this Feature. New default Feature States will be created for the new selected projects Environments for this Feature.', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='projects.Project'),
        ),
    ]
