# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-16 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0009_auto_20180809_0014'),
        ('features', '0009_auto_20180815_1011'),
    ]

    operations = [
    ]
