# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-16 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0014_auto_20190607_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurestate',
            name='feature_segment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_states', to='features.FeatureSegment'),
        ),
        migrations.AddField(
            model_name='historicalfeaturestate',
            name='feature_segment',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='features.FeatureSegment'),
        ),
        migrations.AlterField(
            model_name='featuresegment',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_segments', to='features.Feature'),
        ),
    ]
