# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-16 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0007_auto_20190827_1528'),
        ('features', '0015_auto_20190916_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuresegment',
            name='value',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='featuresegment',
            name='value_type',
            field=models.CharField(blank=True, choices=[('int', 'Integer'), ('unicode', 'String'), ('bool', 'Boolean')], max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='featurestate',
            unique_together=set([('feature', 'environment', 'identity'), ('feature', 'environment', 'feature_segment')]),
        ),
    ]
