# Generated by Django 2.2.17 on 2021-01-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0024_auto_20200917_1032'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='featurestate',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='featurestate',
            constraint=models.UniqueConstraint(condition=models.Q(identity__isnull=True), fields=('environment', 'feature', 'feature_segment'), name='unique_for_feature_segment'),
        ),
        migrations.AddConstraint(
            model_name='featurestate',
            constraint=models.UniqueConstraint(condition=models.Q(feature_segment__isnull=True), fields=('environment', 'feature', 'identity'), name='unique_for_identity'),
        ),
        migrations.AddConstraint(
            model_name='featurestate',
            constraint=models.UniqueConstraint(condition=models.Q(('feature_segment__isnull', True), ('identity__isnull', True)), fields=('environment', 'feature'), name='unique_for_environment'),
        ),
    ]
