# Generated by Django 2.2.17 on 2021-01-10 12:35

from django.db import migrations


def enable_all_remote_config_feature_states(apps, schema_editor):
    FeatureState = apps.get_model('features', 'FeatureState')

    # update all existing remote config feature states to maintain current
    # functionality when hiding disabled flags since we've now merged flags
    # and remote config feature states.
    FeatureState.objects.filter(feature__type="CONFIG").update(enabled=True)


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0024_auto_20200917_1032'),
    ]

    operations = [
        migrations.RunPython(
            enable_all_remote_config_feature_states, reverse_code=reverse
        )
    ]
