# Generated by Django 2.2.17 on 2021-02-15 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0025_alter_unique_constraints_for_feature_states'),
        ('features', '0026_auto_20210110_1300'),
    ]

    operations = [
    ]
