# Generated by Django 2.2.23 on 2021-06-25 13:11

from django.db import migrations

from features.feature_types import CONFIG, FLAG, STANDARD


def update_feature_type(apps, schema_editor):
    Feature = apps.get_model("features", "Feature")
    Feature.objects.filter(type__in=[FLAG, CONFIG]).update(type=STANDARD)


def reverse(apps, schema_editor):
    # we cannot accurately determine which should be flags, configs or standard so we
    # just ignore the reverse path for now.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0031_merge_20210409_1621"),
    ]

    operations = [
        migrations.RunPython(update_feature_type, reverse_code=lambda *args: None)
    ]
