# Generated by Django 2.2.24 on 2021-09-19 11:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("features", "0032_update_feature_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="owners",
            field=models.ManyToManyField(
                related_name="owned_features", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
