# Generated by Django 2.2.24 on 2021-09-30 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0033_feature_owners"),
        ("features", "0033_auto_20210918_1048"),
    ]

    operations = []
