# Generated by Django 2.2.25 on 2022-01-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0035_auto_20211109_0603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='featurestate',
            name='disable_overrides',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalfeaturestate',
            name='disable_overrides',
            field=models.BooleanField(default=False),
        ),
    ]
