# Generated by Django 3.2.12 on 2022-03-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0035_auto_20211109_0603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ('id',)},
        ),
    ]
