# Generated by Django 3.2.12 on 2022-02-17 17:14

from django.db import migrations, models
from django.contrib.postgres.operations import (
    RemoveIndexConcurrently,
    AddIndexConcurrently,
)
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0036_remove_existing_constraints"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feature",
            options={"ordering": ("id",)},
        ),
        migrations.AddField(
            model_name="featurestate",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="featurestate",
            name="live_from",
            field=models.DateTimeField(null=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="featurestate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="featurestate",
            name="version",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="historicalfeaturestate",
            name="created_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, editable=False
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalfeaturestate",
            name="live_from",
            field=models.DateTimeField(null=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalfeaturestate",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, editable=False
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalfeaturestate",
            name="version",
            field=models.IntegerField(default=1),
        ),
    ]
