# Generated by Django 3.2.12 on 2022-03-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0036_alter_feature_options'),
        ('features', '0038_remove_old_versions_and_drafts'),
    ]

    operations = [
    ]
