# Generated by Django 3.2.12 on 2022-04-05 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0039_allow_null_version'),
        ('features', '0039_merge_20220329_1252'),
    ]

    operations = [
    ]
