# Generated by Django 3.2.12 on 2022-03-25 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
        ('features', '0039_allow_null_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurestate',
            name='change_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_states', to='workflows.changerequest'),
        ),
        migrations.AddField(
            model_name='historicalfeaturestate',
            name='change_request',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflows.changerequest'),
        ),
    ]
