# Generated by Django 3.2.13 on 2022-06-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0041_merge_20220406_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='type',
            field=models.CharField(blank=True, default='STANDARD', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfeature',
            name='type',
            field=models.CharField(blank=True, default='STANDARD', max_length=50, null=True),
        ),
    ]
