# Generated by Django 3.2.13 on 2022-07-01 10:52
import uuid

from django.db import migrations, models

from core.migration_helpers import AddDefaultUUIDs


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0045_add_uuid_field_to_feature_state_value'),
    ]

    operations = [
        migrations.AddField(
            model_name="featuresegment",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(
            AddDefaultUUIDs("features", "featuresegment"),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="featuresegment",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
