# Generated by Django 3.2.13 on 2022-07-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0046_add_uuid_field_to_feature_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='type',
            field=models.CharField(blank=True, default='STANDARD', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalfeature',
            name='type',
            field=models.CharField(blank=True, default='STANDARD', max_length=50),
        ),
    ]
