# Generated by Django 3.2.16 on 2023-01-16 15:28

from django.db import migrations


_drop_index_sql = 'DROP INDEX "lowercase_feature_name";'

_forward_sql = f'{_drop_index_sql} CREATE UNIQUE INDEX "lowercase_feature_name" ON "features_feature" (lower(name), project_id) WHERE deleted_at IS NULL;'
_reverse_sql = f'{_drop_index_sql} CREATE UNIQUE INDEX "lowercase_feature_name" ON "features_feature" (lower(name), project_id);'


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("features", "0049_safe_delete_feature_models"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="feature", unique_together=set()),
        migrations.SeparateDatabaseAndState(
            state_operations=[],
            database_operations=[
                migrations.RunSQL(_forward_sql, reverse_sql=_reverse_sql),
            ],
        ),
    ]
