# Generated by Django 3.2.17 on 2023-02-10 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0002_soft_delete_api_keys'),
        ('features', '0051_permanently_delete_soft_deleted_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalfeaturestatevalue',
            name='master_api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_keys.masterapikey'),
        ),
    ]
