# Generated by Django 3.2.17 on 2023-02-16 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0019_add_audit_to_condition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_keys', '0002_soft_delete_api_keys'),
        ('environments', '0027_auto_20230106_0626'),
        ('features', '0054_add_missing_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFeatureSegment',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('_enabled', models.BooleanField(db_column='enabled', default=False, help_text='Deprecated in favour of using FeatureStateValue.')),
                ('_value', models.CharField(blank=True, db_column='value', help_text='Deprecated in favour of using FeatureStateValue.', max_length=2000, null=True)),
                ('_value_type', models.CharField(blank=True, choices=[('int', 'Integer'), ('unicode', 'String'), ('bool', 'Boolean')], db_column='value_type', help_text='Deprecated in favour of using FeatureStateValue.', max_length=50, null=True)),
                ('priority', models.PositiveIntegerField(db_index=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('environment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='environments.environment')),
                ('feature', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='features.feature')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('master_api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_keys.masterapikey')),
                ('segment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='segments.segment')),
            ],
            options={
                'verbose_name': 'historical feature segment',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
