# Generated by Django 3.2.18 on 2023-03-03 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0055_add_feature_segment_audit_log_for_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurestate',
            name='change_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_states', to='workflows_core.changerequest'),
        ),
    ]
