# Generated by Django 3.2.18 on 2023-06-28 11:47

from django.db import migrations
from features.feature_types import MULTIVARIATE, STANDARD


def fix_feature_type(apps, schema_editor):
    Feature = apps.get_model("features", "Feature")
    Feature.objects.filter(type=STANDARD, multivariate_options__isnull=False).update(
        type=MULTIVARIATE
    )


class Migration(migrations.Migration):
    dependencies = [
        ("features", "0058_alter_boolean_values"),
        ("multivariate", "0007_alter_boolean_values"),
    ]

    operations = [
        migrations.RunPython(fix_feature_type, reverse_code=migrations.RunPython.noop),
    ]
