# Generated by Django 3.2.20 on 2023-10-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_add_user_permission_group_membership_through_model'),
        ('features', '0059_fix_feature_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='group_owners',
            field=models.ManyToManyField(blank=True, related_name='owned_features', to='users.UserPermissionGroup'),
        ),
    ]
