# Generated by Django 3.2.20 on 2023-08-30 13:14

from django.db import migrations, models
import django.db.models.deletion


def delete_feature_states_without_environment(apps, schema_editor):
    FeatureState = apps.get_model("features", "FeatureState")
    FeatureState.objects.filter(environment=None).delete()


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        (
            "environments",
            "0032_rename_use_mv_v2_evaluation_to_use_in_percentage_split_evaluation",
        ),
        ("features", "0059_fix_feature_type"),
    ]

    operations = [
        migrations.RunPython(
            delete_feature_states_without_environment,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="featurestate",
            name="environment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feature_states",
                to="environments.environment",
            ),
        ),
    ]
