# Generated by Django 3.2.23 on 2023-11-21 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feature_versioning', '0001_add_environment_feature_state_version_logic'),
        ('environments', '0033_add_environment_feature_state_version_logic'),
        ('segments', '0019_add_audit_to_condition'),
        ('features', '0060_feature_group_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuresegment',
            name='environment_feature_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_segments', to='feature_versioning.environmentfeatureversion'),
        ),
        migrations.AddField(
            model_name='featurestate',
            name='environment_feature_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_states', to='feature_versioning.environmentfeatureversion'),
        ),
        migrations.AddField(
            model_name='historicalfeaturesegment',
            name='environment_feature_version',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='feature_versioning.environmentfeatureversion'),
        ),
        migrations.AddField(
            model_name='historicalfeaturestate',
            name='environment_feature_version',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='feature_versioning.environmentfeatureversion'),
        ),
    ]
