# Generated by Django 3.2.23 on 2023-11-21 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0032_rename_use_mv_v2_evaluation_to_use_in_percentage_split_evaluation'),
        ('features', '0060_feature_group_owners'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=1000000)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='DateCreated')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_exports', to='environments.environment')),
            ],
        ),
    ]
