# Generated by Django 3.2.20 on 2023-11-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0060_history_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalfeature',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfeaturesegment',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfeaturestate',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfeaturestatevalue',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
