# Generated by Django 3.2.23 on 2023-11-21 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0032_rename_use_mv_v2_evaluation_to_use_in_percentage_split_evaluation'),
        ('features', '0061_featureexport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureexport',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_imports', to='environments.environment'),
        ),
        migrations.CreateModel(
            name='FeatureImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('SKIP', 'Skip'), ('OVERWRITE', 'Overwrite')], max_length=50)),
                ('data', models.CharField(max_length=1000000)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='DateCreated')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_exports', to='environments.environment')),
            ],
        ),
    ]
