# Generated by Django 3.2.23 on 2023-12-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0062_alter_feature_segment_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalfeature',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical feature', 'verbose_name_plural': 'historical features'},
        ),
        migrations.AlterModelOptions(
            name='historicalfeaturesegment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical feature segment', 'verbose_name_plural': 'historical feature segments'},
        ),
        migrations.AlterModelOptions(
            name='historicalfeaturestate',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical feature state', 'verbose_name_plural': 'historical feature states'},
        ),
        migrations.AlterModelOptions(
            name='historicalfeaturestatevalue',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical feature state value', 'verbose_name_plural': 'historical feature state values'},
        ),
        migrations.AddField(
            model_name='historicalfeature',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfeaturesegment',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfeaturestate',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfeaturestatevalue',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfeature',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalfeaturesegment',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalfeaturestate',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalfeaturestatevalue',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
