# Generated by Django 3.2.24 on 2024-03-07 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows_core', '0009_prevent_cascade_delete_from_user_delete'),
        ('features', '0064_fix_feature_help_text_typo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurestate',
            name='change_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_states', to='workflows_core.changerequest'),
        ),
    ]
