# Generated by Django 4.2.27 on 2025-12-29 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("buckets", "0001_initial"),
        ("features", "0065_make_feature_value_size_configurable"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="bucket",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional bucket for organizing features within a project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="features",
                to="buckets.bucket",
            ),
        ),
        migrations.AddField(
            model_name="historicalfeature",
            name="bucket",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Optional bucket for organizing features within a project",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="buckets.bucket",
            ),
        ),
    ]
