# Generated by Django 5.2.15 on 2026-06-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0066_constrain_feature_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="featurestate",
            name="mv_hashing_salt",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalfeaturestate",
            name="mv_hashing_salt",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
