# Generated by Django 5.2.16 on 2026-08-07 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0067_add_feature_state_mv_hashing_salt"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="is_creating",
            field=models.BooleanField(
                default=False,
                help_text="Attribute used to indicate when a feature is still being created, and its initial feature states are not yet guaranteed to exist",
            ),
        ),
    ]
