# Generated by Django 5.2.13 on 2026-05-11 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0029_bump_default_project_limits"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlagdProjectConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flagd_configuration",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "flagd project configuration",
                "verbose_name_plural": "flagd project configurations",
            },
        ),
    ]
