# Maintain a list of permissions here
VIEW_ENVIRONMENT = "VIEW_ENVIRONMENT"
UPDATE_FEATURE_STATE = "UPDATE_FEATURE_STATE"
MANAGE_IDENTITIES = "MANAGE_IDENTITIES"
VIEW_IDENTITIES = "VIEW_IDENTITIES"
CREATE_CHANGE_REQUEST = "CREATE_CHANGE_REQUEST"
APPROVE_CHANGE_REQUEST = "APPROVE_CHANGE_REQUEST"
MANAGE_SEGMENT_OVERRIDES = "MANAGE_SEGMENT_OVERRIDES"

TAG_SUPPORTED_PERMISSIONS = [UPDATE_FEATURE_STATE]
