# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180518_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ffadminuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
