# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180518_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ffadminuser',
            options={'ordering': ['id']},
        ),
    ]
