# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180522_0931'),
        ('users', '0007_invite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together=set([('email', 'organisation')]),
        ),
    ]
