# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-09 00:14
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_invite_invited_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ffadminuser',
            options={'ordering': ['id'], 'verbose_name': 'Feature flag admin user'},
        ),
        migrations.AlterField(
            model_name='ffadminuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='DateCreated'),
        ),
    ]
