# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20180910_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invite',
            options={'ordering': ['organisation', 'date_created']},
        ),
        migrations.AlterField(
            model_name='invite',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='organisations.Organisation'),
        ),
    ]
