# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-23 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20190918_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='role',
            field=models.CharField(default='USER', max_length=50),
        ),
    ]
