# Generated by Django 2.2.12 on 2020-05-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20200509_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='ffadminuser',
            name='google_user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
