# Generated by Django 2.2.17 on 2021-01-13 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_ffadminuser_github_user_id'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='Invite',
                ),
            ],
        ),
    ]
