# Generated by Django 2.2.17 on 2020-12-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_ffadminuser_github_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invite",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
