# Generated by Django 2.2.17 on 2021-02-23 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_delete_invite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpermissiongroup',
            options={'ordering': ('id',)},
        ),
    ]
