# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segmentcondition',
            name='segment',
        ),
        migrations.AddField(
            model_name='segment',
            name='rules',
            field=models.TextField(default={}),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SegmentCondition',
        ),
    ]
