# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0003_segment_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('EQUAL', 'Exactly Equal'), ('GREATER_THAN', 'Greater than'), ('LESS_THAN', 'Less than')], max_length=500)),
                ('property', models.CharField(max_length=1000)),
                ('value', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SegmentRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ALL', 'all'), ('ANY', 'any'), ('NONE', 'none')], max_length=50)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='segments.SegmentRule')),
            ],
        ),
        migrations.RemoveField(
            model_name='segment',
            name='rules',
        ),
        migrations.AddField(
            model_name='segmentrule',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='segments.Segment'),
        ),
        migrations.AddField(
            model_name='condition',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='segments.SegmentRule'),
        ),
    ]
