# Generated by Django 2.2.17 on 2021-02-23 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0007_auto_20190906_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='segment',
            options={'ordering': ('id',)},
        ),
    ]
