# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_auto_20180530_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurestate',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='featurestate',
            name='identity',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identity_features', to='environments.Identity'),
        ),
        migrations.AlterField(
            model_name='featurestatevalue',
            name='integer_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='featurestatevalue',
            name='string_value',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='featurestatevalue',
            name='type',
            field=models.CharField(blank=True, choices=[('int', 'Integer'), ('unicode', 'String'), ('bool', 'Boolean')], default='unicode', max_length=10, null=True),
        ),
    ]
