# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0005_auto_20190529_1426'),
        ('features', '0012_auto_20190424_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurestate',
            name='segment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segment_features', to='segments.Segment'),
        ),
        migrations.AddField(
            model_name='historicalfeaturestate',
            name='segment',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='segments.Segment'),
        ),
    ]
