# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-07 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0005_auto_20190529_1426'),
        ('features', '0012_auto_20190424_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Feature')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_segments', to='segments.Segment')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='featuresegment',
            unique_together=set([('feature', 'segment'), ('feature', 'priority')]),
        ),
    ]
