# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0005_auto_20190529_1426'),
        ('environments', '0005_auto_20181128_1013'),
        ('features', '0013_auto_20190529_1426'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='featurestate',
            unique_together=set([('feature', 'environment', 'identity'), ('feature', 'environment', 'segment')]),
        ),
    ]
