# Generated by Django 2.2.12 on 2020-06-07 10:05
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0012_auto_20200504_1322'),
        ('segments', '0007_auto_20190906_1416'),
        ('features', '0016_auto_20190916_1717'),
    ]

    operations = [
        # first, add the field, allowing null values
        migrations.AddField(
            model_name='featuresegment',
            name='environment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_segments', to='environments.Environment'),
        ),
        migrations.AlterUniqueTogether(
            name='featuresegment',
            unique_together={('feature', 'environment', 'priority'), ('feature', 'environment', 'segment')},
        ),
    ]
