# Generated by Django 2.2.13 on 2020-06-07 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0018_auto_20200607_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuresegment',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_segments', to='environments.Environment'),
        ),
    ]
