# Generated by Django 2.2.16 on 2020-09-16 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0023_auto_20200717_1515'),
    ]

    operations = [
        # this migration was generated by moving the identity mode from environments
        # to environments.identities so we only need to update the state, not the db
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='featurestate',
                    name='identity',
                    field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identity_features', to='identities.Identity'),
                ),
                migrations.AlterField(
                    model_name='historicalfeaturestate',
                    name='identity',
                    field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='identities.Identity'),
                ),
            ],
            database_operations=[]
        )
    ]
