# Generated by Django 2.2.16 on 2020-09-18 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0024_auto_20200917_1032'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='featurestatevalue',
                    name='feature_state',
                ),
                migrations.RemoveField(
                    model_name='historicalfeaturestate',
                    name='environment',
                ),
                migrations.RemoveField(
                    model_name='historicalfeaturestate',
                    name='feature',
                ),
                migrations.RemoveField(
                    model_name='historicalfeaturestate',
                    name='feature_segment',
                ),
                migrations.RemoveField(
                    model_name='historicalfeaturestate',
                    name='history_user',
                ),
                migrations.RemoveField(
                    model_name='historicalfeaturestate',
                    name='identity',
                ),
                migrations.RemoveField(
                    model_name='historicalfeaturestatevalue',
                    name='feature_state',
                ),
                migrations.RemoveField(
                    model_name='historicalfeaturestatevalue',
                    name='history_user',
                ),
                migrations.DeleteModel(
                    name='FeatureState',
                ),
                migrations.DeleteModel(
                    name='FeatureStateValue',
                ),
                migrations.DeleteModel(
                    name='HistoricalFeatureState',
                ),
                migrations.DeleteModel(
                    name='HistoricalFeatureStateValue',
                ),
            ],
            database_operations=[]
        )
    ]
