# Generated by Django 2.2.17 on 2021-01-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0025_enable_all_remote_config_feature_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfeature',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
