# Generated by Django 2.2.17 on 2021-02-16 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0027_merge_20210215_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={},
        ),
    ]
