# Generated by Django 2.2.17 on 2021-03-05 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0028_auto_20210216_1600'),
        ('features', '0029_auto_20210223_2106'),
    ]

    operations = [
    ]
