# Generated by Django 3.2.16 on 2023-02-16 02:40

from django.db import migrations, models
import django.db.models.deletion
import metadata.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0038_soft_delete_organisations'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('int', 'Integer'), ('str', 'String'), ('bool', 'Boolean'), ('url', 'Url'), ('multiline_str', 'Multiline String')], default='str', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
            ],
            options={
                'unique_together': {('name', 'organisation')},
            },
        ),
        migrations.CreateModel(
            name='MetadataModelField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.metadatafield')),
            ],
            options={
                'unique_together': {('field', 'content_type')},
            },
        ),
        migrations.CreateModel(
            name='MetadataModelFieldRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('object_id', metadata.fields.GenericObjectID()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('model_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_required_for', to='metadata.metadatamodelfield')),
            ],
            options={
                'unique_together': {('content_type', 'object_id', 'model_field')},
            },
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('object_id', metadata.fields.GenericObjectID()),
                ('field_value', models.TextField(max_length=2000)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('model_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.metadatamodelfield')),
            ],
            options={
                'unique_together': {('model_field', 'content_type', 'object_id')},
            },
        ),
    ]
