# Generated by Django 3.2.16 on 2022-12-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='field_data',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterUniqueTogether(
            name='metadata',
            unique_together={('field', 'content_type', 'object_id')},
        ),
    ]
