# Generated by Django 4.2.18 on 2025-04-09 10:24

from django.db import migrations
import metadata.fields


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metadatamodelfieldrequirement",
            name="object_id",
            field=metadata.fields.GenericObjectID(null=True),
        ),
    ]
