# Generated by Django 5.2.11 on 2026-02-16 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0001_initial"),
        ("organisations", "0058_update_audit_and_history_limits_in_sub_cache"),
        ("projects", "0027_add_create_project_level_change_requests_permission"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="metadatafield",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="metadatafield",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
            ),
        ),
        migrations.AddConstraint(
            model_name="metadatafield",
            constraint=models.UniqueConstraint(
                condition=models.Q(("project__isnull", True)),
                fields=("name", "organisation"),
                name="unique_org_level_metadata_field",
            ),
        ),
        migrations.AddConstraint(
            model_name="metadatafield",
            constraint=models.UniqueConstraint(
                condition=models.Q(("project__isnull", False)),
                fields=("name", "organisation", "project"),
                name="unique_project_level_metadata_field",
            ),
        ),
    ]
