# Generated by Django 3.2.16 on 2022-12-30 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('metadata', '0002_auto_20221228_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadata',
            old_name='field',
            new_name='model_field',
        ),
        migrations.AlterUniqueTogether(
            name='metadata',
            unique_together={('model_field', 'content_type', 'object_id')},
        ),
    ]
