# Generated by Django 3.2.16 on 2023-01-02 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0037_add_default_subscription_to_existing_organisations'),
        ('metadata', '0003_auto_20221230_0327'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metadatafield',
            unique_together={('name', 'organisation')},
        ),
    ]
