# Generated by Django 5.2.15 on 2026-07-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="integrationhealthrecord",
            index=models.Index(
                fields=["content_type", "object_id", "-created_at"],
                name="common_inte_content_bd807d_idx",
            ),
        ),
    ]
