# Generated by Django 5.2.16 on 2026-08-07 11:54

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gitlab", "0003_gitlabconfiguration_labeling_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gitlabconfiguration",
            name="gitlab_instance_url",
            field=core.fields.NoSSRFURLField(),
        ),
    ]
