# Generated by Django 3.2.25 on 2024-05-31 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_keys", "0003_masterapikey_is_admin"),
        ("feature_versioning", "0001_add_environment_feature_state_version_logic"),
    ]

    operations = [
        migrations.AddField(
            model_name="environmentfeatureversion",
            name="created_by_api_key",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_environment_feature_versions",
                to="api_keys.masterapikey",
            ),
        ),
        migrations.AddField(
            model_name="environmentfeatureversion",
            name="published_by_api_key",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_environment_feature_versions",
                to="api_keys.masterapikey",
            ),
        ),
        migrations.AddField(
            model_name="historicalenvironmentfeatureversion",
            name="created_by_api_key",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="api_keys.masterapikey",
            ),
        ),
        migrations.AddField(
            model_name="historicalenvironmentfeatureversion",
            name="published_by_api_key",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="api_keys.masterapikey",
            ),
        ),
    ]
