# Generated by Django 3.2.23 on 2023-12-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_versioning', '0001_add_environment_feature_state_version_logic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalenvironmentfeatureversion',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical environment feature version', 'verbose_name_plural': 'historical environment feature versions'},
        ),
        migrations.RemoveField(
            model_name='historicalenvironmentfeatureversion',
            name='uuid',
        ),
        migrations.AddField(
            model_name='historicalenvironmentfeatureversion',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalenvironmentfeatureversion',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
