# Generated by Django 3.2.20 on 2023-08-23 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows_core', '0008_remove_redundant_column'),
        ('feature_versioning', '0001_add_environment_feature_state_version_logic'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentfeatureversion',
            name='change_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='environment_feature_versions', to='workflows_core.changerequest'),
        ),
        migrations.AddField(
            model_name='historicalenvironmentfeatureversion',
            name='change_request',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflows_core.changerequest'),
        ),
    ]
