# Generated by Django 3.2.25 on 2024-06-12 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows_core", "0009_prevent_cascade_delete_from_user_delete"),
        ("feature_versioning", "0002_add_api_key_for_creation_and_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="environmentfeatureversion",
            name="change_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="environment_feature_versions",
                to="workflows_core.changerequest",
            ),
        ),
    ]
