# Generated by Django 3.2.25 on 2024-06-25 17:09

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0064_fix_feature_help_text_typo'),
        ('workflows_core', '0009_prevent_cascade_delete_from_user_delete'),
        ('feature_versioning', '0003_cascade_delete_versions_on_cr_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionChangeSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('feature_states_to_create', models.TextField(help_text='JSON blob describing the feature states that should be created when the change request is published', null=True)),
                ('feature_states_to_update', models.TextField(help_text='JSON blob describing the feature states that should be updated when the change request is published', null=True)),
                ('segment_ids_to_delete_overrides', models.TextField(help_text='JSON blob describing the segment overrides for whichthe segment overrides should be deleted when the change request is published', null=True)),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_sets', to='workflows_core.changerequest')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.feature')),
            ],
            options={
                'permissions': (('can_undelete', 'Can undelete this object'),),
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
