# Generated by Django 4.2.22 on 2025-07-01 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("release_pipelines_core", "0001_add_release_pipelines"),
        (
            "feature_versioning",
            "0005_fix_scheduled_fs_data_issue_caused_by_enabling_versioning",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="environmentfeatureversion",
            name="pipeline_stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="environment_feature_versions",
                to="release_pipelines_core.pipelinestage",
            ),
        ),
        migrations.AddField(
            model_name="historicalenvironmentfeatureversion",
            name="pipeline_stage",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="release_pipelines_core.pipelinestage",
            ),
        ),
        migrations.AddConstraint(
            model_name="environmentfeatureversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("published_at__isnull", True)),
                fields=("feature", "environment", "pipeline_stage"),
                name="unique_feature_environment_stage_unpublished",
            ),
        ),
    ]
