# Generated by Django 4.2.21 on 2025-05-20 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("release_pipelines_core", "0001_wip_release_pipeline"),
        (
            "feature_versioning",
            "0005_fix_scheduled_fs_data_issue_caused_by_enabling_versioning",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="environmentfeatureversion",
            name="pipeline_stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="environment_feature_versions",
                to="release_pipelines_core.pipelinestage",
            ),
        ),
        migrations.AddField(
            model_name="historicalenvironmentfeatureversion",
            name="pipeline_stage",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="release_pipelines_core.pipelinestage",
            ),
        ),
    ]
