# Generated by Django 4.2.22 on 2025-07-30 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("segments", "0027_historicalsegmentrule"),
        ("feature_versioning", "0006_add_pipeline_stage_to_envfeatureversion"),
    ]

    operations = [
        migrations.AddField(
            model_name="environmentfeatureversion",
            name="rollout_segment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="environment_feature_versions",
                to="segments.segment",
            ),
        ),
        migrations.AddField(
            model_name="environmentfeatureversion",
            name="rollout_segment_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalenvironmentfeatureversion",
            name="rollout_segment",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="segments.segment",
            ),
        ),
        migrations.AddField(
            model_name="historicalenvironmentfeatureversion",
            name="rollout_segment_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
