# Generated by Django 4.2.21 on 2025-06-03 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("feature_versioning", "0006_wip_release_pipeline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="versionchangeset",
            name="environment_feature_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="version_change_sets",
                to="feature_versioning.environmentfeatureversion",
            ),
        ),
    ]
