# Generated by Django 4.2.22 on 2025-08-06 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("release_pipelines_core", "0002_add_phased_rollout"),
        ("feature_versioning", "0006_add_pipeline_stage_to_envfeatureversion"),
    ]

    operations = [
        migrations.AddField(
            model_name="environmentfeatureversion",
            name="phased_rollout_state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="environment_feature_versions",
                to="release_pipelines_core.phasedrolloutstate",
            ),
        ),
        migrations.AddField(
            model_name="historicalenvironmentfeatureversion",
            name="phased_rollout_state",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="release_pipelines_core.phasedrolloutstate",
            ),
        ),
    ]
