# Generated by Django 5.2.16 on 2026-07-23 11:41

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("api_keys", "0004_add_created_by"),
        ("environments", "0037_add_uuid_field"),
        ("feature_versioning", "0007_add_phased_rollout"),
        ("features", "0067_add_feature_state_mv_hashing_salt"),
        ("release_pipelines_core", "0003_add_created_at"),
        ("workflows_core", "0012_alter_changerequest_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="environmentfeatureversion",
            index=models.Index(
                condition=models.Q(
                    ("deleted_at__isnull", True), ("published_at__isnull", False)
                ),
                fields=["feature", "-created_at"],
                name="efv_feature_published_created",
            ),
        ),
        AddIndexConcurrently(
            model_name="environmentfeatureversion",
            index=models.Index(
                condition=models.Q(
                    ("deleted_at__isnull", True), ("published_at__isnull", False)
                ),
                fields=["environment", "feature", "-created_at"],
                name="efv_env_feature_pub_created",
            ),
        ),
    ]
