# Generated by Django 5.2.16 on 2026-07-23 11:41

from django.db import migrations, models

from core.migration_helpers import PostgresOnlyRunSQL


class Migration(migrations.Migration):
    atomic = False

    # The auto-generated cross-app dependencies (workflows_core, features,
    # etc.) are intentionally trimmed to the previous migration only: the
    # indexes need nothing beyond the model state from this app, and extra
    # dependency edges reorder the global migration plan, breaking
    # `Migrator.apply_initial_migration` prefix truncation in migration tests.
    dependencies = [
        ("feature_versioning", "0007_add_phased_rollout"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="environmentfeatureversion",
                    index=models.Index(
                        condition=models.Q(
                            ("deleted_at__isnull", True),
                            ("published_at__isnull", False),
                        ),
                        fields=["feature", "-created_at"],
                        name="efv_feature_published_created",
                    ),
                ),
                migrations.AddIndex(
                    model_name="environmentfeatureversion",
                    index=models.Index(
                        condition=models.Q(
                            ("deleted_at__isnull", True),
                            ("published_at__isnull", False),
                        ),
                        fields=["environment", "feature", "-created_at"],
                        name="efv_env_feature_pub_created",
                    ),
                ),
            ],
            database_operations=[
                PostgresOnlyRunSQL(
                    'CREATE INDEX CONCURRENTLY IF NOT EXISTS "efv_feature_published_created" '
                    'ON "feature_versioning_environmentfeatureversion" '
                    '("feature_id", "created_at" DESC) '
                    'WHERE ("deleted_at" IS NULL AND "published_at" IS NOT NULL);',
                    reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS "efv_feature_published_created";',
                ),
                PostgresOnlyRunSQL(
                    'CREATE INDEX CONCURRENTLY IF NOT EXISTS "efv_env_feature_pub_created" '
                    'ON "feature_versioning_environmentfeatureversion" '
                    '("environment_id", "feature_id", "created_at" DESC) '
                    'WHERE ("deleted_at" IS NULL AND "published_at" IS NOT NULL);',
                    reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS "efv_env_feature_pub_created";',
                ),
            ],
        ),
    ]
