# Generated by Django 5.2.16 on 2026-08-07 11:54

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mixpanel", "0003_mixpanelconfiguration_deleted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mixpanelconfiguration",
            name="base_url",
            field=core.fields.NoSSRFURLField(null=True),
        ),
    ]
