# Generated by Django 3.2.13 on 2022-06-22 15:13

from django.db import migrations, models
import uuid

from core.migration_helpers import AddDefaultUUIDs


class Migration(migrations.Migration):

    dependencies = [
        ("datadog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datadogconfiguration",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.RunPython(
            AddDefaultUUIDs("datadog", "datadogconfiguration"),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="datadogconfiguration",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
