# Generated by Django 3.2.18 on 2023-02-28 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_soft_delete_projects'),
        ('datadog', '0002_add_uuid_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadogconfiguration',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_dog_config', to='projects.project'),
        ),
    ]
