# Generated by Django 3.2.23 on 2024-01-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadog', '0003_datadogconfiguration_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadogconfiguration',
            name='use_custom_source',
            field=models.BooleanField(default=False),
        ),
    ]
