# Generated by Django 5.2.16 on 2026-08-07 11:54

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datadog", "0004_add_use_custom_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datadogconfiguration",
            name="base_url",
            field=core.fields.NoSSRFURLField(),
        ),
    ]
