# Generated by Django 4.2.17 on 2025-01-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trench", "0003_auto_20190213_2330"),
    ]

    operations = [
        migrations.AddField(
            model_name="mfamethod",
            name="created_at",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="mfamethod",
            name="updated_at",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
