# Generated by Django 2.2.10 on 2020-02-24 21:06

from django.db import migrations


def delete_edit_feature_permission(apps, schema_editor):
    ProjectPermissionModel = apps.get_model('projects', 'ProjectPermissionModel')

    ProjectPermissionModel.objects.filter(key='EDIT_FEATURE').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200221_2317'),
    ]

    operations = [
        migrations.RunPython(delete_edit_feature_permission, lambda *args: None)
    ]
