# Generated by Django 2.2.14 on 2020-07-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200504_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='datadog_api_base_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='datadog_api_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
