# Generated by Django 5.2.13 on 2026-05-08 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("environments", "0037_add_uuid_field"),
        ("segments", "0030_add_default_to_segment_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="SegmentMembership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField()),
                ("last_synced_at", models.DateTimeField()),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="environments.environment",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="segments.segment",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("segment", "environment"),
                        name="segment_membership_unique_segment_environment",
                    )
                ],
            },
        ),
    ]
