# Generated by Django 5.2.13 on 2026-05-03 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("environments", "0037_add_uuid_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="Atom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("trait", "trait"),
                            ("identifier", "identifier"),
                            ("identity_key", "identity_key"),
                            ("environment_name", "environment_name"),
                        ],
                        max_length=32,
                    ),
                ),
                ("property", models.CharField(max_length=1000)),
                ("operator", models.CharField(max_length=64)),
                ("operand_canonical", models.TextField(blank=True, null=True)),
                ("segment_key", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segment_membership_atoms",
                        to="environments.environment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AtomBitmap",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blob", models.BinaryField()),
                ("cardinality", models.PositiveBigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "atom",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bitmap",
                        to="segment_membership.atom",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="atom",
            index=models.Index(
                fields=["environment", "kind", "property"],
                name="segment_mem_environ_347049_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="atom",
            constraint=models.UniqueConstraint(
                fields=(
                    "environment",
                    "kind",
                    "property",
                    "operator",
                    "operand_canonical",
                    "segment_key",
                ),
                name="segment_membership_atom_uniq",
            ),
        ),
    ]
