# Generated by Django 5.2.15 on 2026-06-27 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0058_update_audit_and_history_limits_in_sub_cache"),
        ("segment_membership", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SegmentMembershipSeed",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seeded_at", models.DateTimeField(null=True)),
                (
                    "organisation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="organisations.organisation",
                    ),
                ),
            ],
        ),
    ]
