# Generated by Django 5.2.16 on 2026-07-24 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0029_bump_default_project_limits"),
        ("segment_membership", "0002_segment_membership_seed"),
    ]

    operations = [
        migrations.CreateModel(
            name="SegmentMembershipRefreshState",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identity_watermark", models.DateTimeField(null=True)),
                ("last_refreshed_at", models.DateTimeField()),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
