#!/bin/sh

set -e
# Run checks in api folder
echo "Starting pre-commit in 'api' folder:"
cd api
pre-commit run

# Run checks in frontend folder
echo "Starting pre-commit in 'frontend' folder:"
cd ../frontend
.husky/pre-commit

# Run checks in docs folder
echo "Starting pre-commit in 'docs' folder:"
cd ../docs
npm run prettier:fix
