# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-17 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180514_1622'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='identityfeature',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='identityfeature',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='identityfeature',
            name='identity',
        ),
        migrations.AddField(
            model_name='featurestate',
            name='identity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identityfeatures', to='api.Identity'),
        ),
        migrations.AlterField(
            model_name='featurestate',
            name='environment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featurestates', to='api.Environment'),
        ),
        migrations.AlterUniqueTogether(
            name='featurestate',
            unique_together=set([('feature', 'environment', 'identity')]),
        ),
        migrations.DeleteModel(
            name='IdentityFeature',
        ),
    ]
