# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180522_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='initial_value',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
    ]
