# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20180522_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
