# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20180525_1436'),
        ('environments', '0001_initial')
    ]

    operations = [
        migrations.RemoveField(
            model_name='environment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='environment',
        ),
        migrations.AlterField(
            model_name='featurestate',
            name='environment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_states', to='environments.Environment'),
        ),
        migrations.AlterField(
            model_name='featurestate',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_states', to='api.Feature'),
        ),
        migrations.AlterField(
            model_name='featurestate',
            name='identity',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identity_features', to='environments.Identity'),
        ),
        migrations.DeleteModel(
            name='Environment',
        ),
        migrations.DeleteModel(
            name='Identity',
        ),
    ]
