FLAGSMITH_CLI_CLIENT_ID = "flagsmith-cli"

SCOPE_MCP = "mcp"
SCOPE_ADMIN_API = "admin-api"

FIRST_PARTY_CLIENT_IDS = frozenset({FLAGSMITH_CLI_CLIENT_ID})
FIRST_PARTY_SCOPES = frozenset({SCOPE_ADMIN_API})
THIRD_PARTY_SCOPES = frozenset({SCOPE_MCP})
