# Reusable app definition
x-app: &app
  image: ${DOCKER_IMAGE:-local/flagsmith/flagsmith}:${DOCKER_TAG:-latest}
  build:
    context: ../../
    target: oss-unified
    args:
      POETRY_VERSION: 2.1.1
      INSTALL_DEV_DEPENDENCIES: true
  depends_on:
    default-database:
      condition: service_healthy
    task-processor-database:
      condition: service_healthy
  environment:
    # LOG_LEVEL: DEBUG
    DATABASE_URL: postgres://postgres@default-database:5432/postgres
    DEBUG: true
    DJANGO_SETTINGS_MODULE: app.settings.local
    TASK_PROCESSOR_DATABASE_URL: postgres://postgres@task-processor-database:5432/postgres
    TASK_PROCESSOR_DATABASES: task_processor
  volumes:
    # - ?:/app:rw,cached  # Application directory

services:
  api:
    <<: *app
    command: migrate-and-serve
    ports:
      - 8000:8000

  # TODO
  task-processor:
    <<: *app
    command: run-task-processor

  default-database:
    image: postgres:15.5-alpine
    volumes:
      - ../../.local/default-database:/var/lib/postgresql/data:rw,cached
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: pg_isready -Upostgres
      interval: 1s
      timeout: 30s

  task-processor-database:
    image: postgres:15.5-alpine
    volumes:
      - ../../.local/task-processor-database:/var/lib/postgresql/data:rw,cached
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: pg_isready -Upostgres
      interval: 1s
      timeout: 30s
