# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-24 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SegmentCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait_key', models.CharField(max_length=200)),
                ('condition_type', models.CharField(choices=[('ExactMatch', 'ExactMatch'), ('GreaterThan', 'GreaterThan'), ('LessThan', 'LessThan')], default='ExactMatch', max_length=20)),
                ('match_value', models.TextField(blank=True, null=True)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_conditions', to='segments.Segment')),
            ],
        ),
    ]
