# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('segments', '0002_auto_20190515_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='projects.Project'),
            preserve_default=False,
        ),
    ]
