# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-28 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0005_auto_20190529_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentrule',
            name='type',
            field=models.CharField(choices=[('ALL', 'all'), ('ANY', 'any'), ('NONE', 'none'), ('PERCENTAGE_SPLIT', 'Percentage split')], max_length=50),
        ),
    ]
