# Generated by Django 3.2.13 on 2022-06-20 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20211208_1050'),
        ('segments', '0008_auto_20210223_1603'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='segment',
            unique_together={('name', 'project')},
        ),
    ]
