# Generated by Django 3.2.13 on 2022-06-22 15:42

from django.db import migrations, models
import uuid

from core.migration_helpers import AddDefaultUUIDs


class Migration(migrations.Migration):

    dependencies = [
        ("segments", "0009_add_unique_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="condition",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(
            AddDefaultUUIDs("segments", "condition"),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="condition",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="segment",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(
            AddDefaultUUIDs("segments", "segment"),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="segment",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="segmentrule",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(
            AddDefaultUUIDs("segments", "segmentrule"),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="segmentrule",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
