# Generated by Django 3.2.14 on 2022-08-17 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0047_prevent_null_feature_type'),
        ('segments', '0010_add_uuid_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='features.feature'),
        ),
    ]
