# Generated by Django 3.2.16 on 2023-02-07 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0016_add_historical_records_to_segment'),
    ]

    operations = [
    ]
