# Generated by Django 3.2.25 on 2024-06-10 15:31
from pathlib import Path

import django.db.models.deletion
from django.db import migrations, models

parent_dir = Path(__file__).parent.resolve()

with open(parent_dir / "sql/0023_add_versioning_to_segments.sql") as f:
    segment_versioning_sql_forwards = f.read()

with open(parent_dir / "sql/0023_add_versioning_to_segments_reverse.sql") as f:
    segment_versioning_sql_reverse = f.read()


class Migration(migrations.Migration):
    dependencies = [
        ("segments", "0022_add_soft_delete_to_segment_rules_and_conditions"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsegment",
            name="version",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="historicalsegment",
            name="version_of",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="segments.segment",
            ),
        ),
        migrations.AddField(
            model_name="segment",
            name="version",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="segment",
            name="version_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versioned_segments",
                to="segments.segment",
            ),
        ),
        migrations.RunSQL(
            sql=segment_versioning_sql_forwards,
            reverse_sql=segment_versioning_sql_reverse,
        ),
    ]
