# Generated by Django 3.2.25 on 2024-07-09 10:41
from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def set_default_segment_version(
    apps: Apps,
    schema_editor: BaseDatabaseSchemaEditor,
) -> None:
    segment_model_class = apps.get_model("segments", "Segment")
    segment_model_class.objects.filter(version__isnull=True).update(version=1)


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0024_add_timestamps_to_segments'),
    ]

    operations = [
        migrations.RunPython(set_default_segment_version, reverse_code=migrations.RunPython.noop),
    ]
