# Generated by Django 3.2.25 on 2024-07-18 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows_core", "0009_prevent_cascade_delete_from_user_delete"),
        ("segments", "0026_add_change_requests_to_segments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="segment",
            name="change_request",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="workflows_core.changerequest",
            ),
        ),
    ]
