# Generated by Django 4.2.22 on 2025-08-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Update condition.property to be non-nullable.

    Only conditions of operator PERCENTAGE_SPLIT have empty `property` values,
    according to this query:

    ```sql
    select c.operator, count(*) from segments_condition c where c.property is null or c.property !~ '\S' group by 1;
    ```

    The Flagsmith engine can now do percentage split upon any property, so we
    default empty `property` values to `"$.identity.key"` because that's the
    old behavior for PERCENTAGE_SPLIT conditions.
    """

    dependencies = [
        ("segments", "0027_historicalsegmentrule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="condition",
            name="property",
            field=models.CharField(default="$.identity.key", max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalcondition",
            name="property",
            field=models.CharField(default="$.identity.key", max_length=1000),
            preserve_default=False,
        ),
    ]
