# Generated by Django 4.2.17 on 2025-01-08 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("segments", "0027_historicalsegmentrule"),
    ]

    operations = [
        migrations.AddField(
            model_name="condition",
            name="version_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="versioned_conditions",
                to="segments.condition",
            ),
        ),
        migrations.AddField(
            model_name="historicalcondition",
            name="version_of",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="segments.condition",
            ),
        ),
        migrations.AddField(
            model_name="segmentrule",
            name="version_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="versioned_rules",
                to="segments.segmentrule",
            ),
        ),
        migrations.AddField(
            model_name="historicalsegmentrule",
            name="version_of",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="segments.segmentrule",
            ),
        ),
    ]
