# Generated by Django 4.2.22 on 2025-08-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("segments", "0027_historicalsegmentrule"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsegment",
            name="is_system_segment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="segment",
            name="is_system_segment",
            field=models.BooleanField(default=False),
        ),
    ]
