# Generated by Django 4.2.22 on 2025-08-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("segments", "0028_condition_property_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsegment",
            name="is_system_segment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="segment",
            name="is_system_segment",
            field=models.BooleanField(default=False),
        ),
    ]
