# Generated by Django 4.2.22 on 2025-07-11 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("segments", "0028_segment_first_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="condition",
            name="version_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revisions",
                to="segments.condition",
            ),
        ),
        migrations.AddField(
            model_name="historicalcondition",
            name="version_of",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="segments.condition",
            ),
        ),
        migrations.AddField(
            model_name="historicalsegmentrule",
            name="version_of",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="segments.segmentrule",
            ),
        ),
        migrations.AddField(
            model_name="segmentrule",
            name="version_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revisions",
                to="segments.segmentrule",
            ),
        ),
        migrations.AlterField(
            model_name="segment",
            name="version_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revisions",
                to="segments.segment",
            ),
        ),
    ]
