# Generated by Django 4.2.22 on 2025-11-11 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("segments", "0029_add_is_system_segment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsegment",
            name="version",
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name="segment",
            name="version",
            field=models.IntegerField(default=1, null=True),
        ),
    ]
