# Generated by Django 5.2.16 on 2026-08-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("segments", "0030_add_default_to_segment_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsegment",
            name="managed_by",
            field=models.CharField(
                blank=True, choices=[("cohort", "Cohort")], default="", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="segment",
            name="managed_by",
            field=models.CharField(
                blank=True, choices=[("cohort", "Cohort")], default="", max_length=50
            ),
        ),
    ]
