# Generated by Django 4.2.22 on 2025-11-11 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("segments", "0030_add_default_to_segment_version"),
    ]

    operations = [
        # Set version_of to NULL for canonical segments (where version_of_id = id).
        # This follows the same pattern as migration 0023 which originally set
        # version_of_id = id. Like that migration, this may block during deployment
        # depending on the number of canonical segments in the database.
        migrations.RunSQL(
            sql="UPDATE segments_segment SET version_of_id = NULL WHERE version_of_id = id;",
            reverse_sql="UPDATE segments_segment SET version_of_id = id WHERE version_of_id IS NULL;",
        ),
    ]
