# Generated by Django 5.2.16 on 2026-08-07 15:09
import typing

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

SegmentRule = dict[str, typing.Any]

BATCH_SIZE = 500


def backfill_segment_rules_data(
    apps: Apps, _: BaseDatabaseSchemaEditor | None = None
) -> None:
    Segment = apps.get_model("segments", "Segment")
    SegmentRule = apps.get_model("segments", "SegmentRule")
    Condition = apps.get_model("segments", "Condition")

    rules = SegmentRule.objects.filter(deleted_at__isnull=True).only(
        "segment_id", "rule_id", "type"
    )
    conditions = Condition.objects.filter(deleted_at__isnull=True).only(
        "rule_id", "property", "operator", "value", "description"
    )

    segments = Segment.objects.filter(
        id=models.F("version_of"),  # Means "current version"
        deleted_at__isnull=True,
    ).only("id").prefetch_related(
        models.Prefetch("rules", rules, to_attr="live_rules"),
        models.Prefetch("live_rules__conditions", conditions, to_attr="live_conditions"),
        models.Prefetch("live_rules__rules", rules, to_attr="live_rules"),
        models.Prefetch("live_rules__live_rules__conditions", conditions, to_attr="live_conditions"),
        models.Prefetch("live_rules__live_rules__rules", rules, to_attr="live_rules"),  # Empty almost all cases
    ).order_by("id")

    last_id = 0  # don't leroy jenkins local memory
    while segments_chunk := list(segments.filter(id__gt=last_id)[:BATCH_SIZE]):
        for segment in segments_chunk:
            segment.rules_data = _rasterise_segment_rules(segment)
        Segment.objects.bulk_update(segments_chunk, fields=["rules_data"])
        last_id = segments_chunk[-1].id


def nullify_segment_rules_data(
    apps: Apps, _: BaseDatabaseSchemaEditor | None = None
) -> None:
    Segment = apps.get_model("segments", "Segment")
    Segment.objects.filter(rules_data__isnull=False).update(rules_data=None)


def _rasterise_segment_rules(obj: typing.Any) -> list[SegmentRule]:
    return [
        {
            "type": rule.type,
            "conditions": [
                {
                    "property": condition.property,
                    "operator": condition.operator,
                    "value": condition.value,
                    "description": condition.description,
                }
                for condition in (
                    rule.live_conditions
                    if hasattr(rule, "live_conditions")  # We only prefetch two levels deep
                    else rule.conditions.filter(deleted_at__isnull=True)
                )
            ],
            "rules": _rasterise_segment_rules(rule),
        }
        for rule in (
            obj.live_rules
            if hasattr(obj, "live_rules")  # We only prefetch two levels deep
            else obj.rules.filter(deleted_at__isnull=True)
        )
    ]


class Migration(migrations.Migration):

    dependencies = [
        ("segments", "0030_add_default_to_segment_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsegment",
            name="rules_data",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="segment",
            name="rules_data",
            field=models.JSONField(null=True),
        ),
        migrations.RunPython(
            code=backfill_segment_rules_data,
            reverse_code=nullify_segment_rules_data,
        ),
    ]
