# Generated by Django 5.2.16 on 2026-08-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("segments", "0030_add_default_to_segment_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsegment",
            name="rules_data",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="segment",
            name="rules_data",
            field=models.JSONField(null=True),
        ),
    ]
