# Generated by Django 5.2.17 on 2026-10-08 11:06

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

MANAGED_BY_CHOICES = [
    ("", "Unmanaged"),
    ("cohort", "Cohort"),
    ("dependency", "Flag dependency"),
    ("experiment", "Experiment"),
    ("release_pipeline", "Gradual rollout"),
]
SYSTEM_SEGMENT_OWNERS = ["dependency", "experiment", "release_pipeline"]


def backfill_system_segment_managed_by(
    apps: Apps, _: BaseDatabaseSchemaEditor | None = None
) -> None:
    Segment = apps.get_model("segments", "Segment")
    Experiment = apps.get_model("experimentation", "Experiment")
    PhasedRolloutState = apps.get_model("release_pipelines_core", "PhasedRolloutState")

    # Includes soft-deleted segments, and revisions, which copy their names.
    unmanaged_system_segments = Segment.objects.filter(
        is_system_segment=True, managed_by=""
    )

    # Owners point at their segments, but a segment can outlive its owner, and
    # a change request could have renamed it. Match on either.
    unmanaged_system_segments.filter(
        models.Q(
            id__in=Experiment.objects.filter(
                rollout_segment__isnull=False
            ).values("rollout_segment_id")
        )
        | models.Q(feature__isnull=True, name__regex=r"^experiment-\d+-rollout$")
    ).update(managed_by="experiment")

    unmanaged_system_segments.filter(
        models.Q(
            id__in=PhasedRolloutState.objects.filter(
                rollout_segment__isnull=False
            ).values("rollout_segment_id")
        )
        | models.Q(feature__isnull=False, name="rollout_segment")
    ).update(managed_by="release_pipeline")

    unmanaged_system_segments.filter(
        # `{feature}-depends-on-{prerequisite}` since #8632,
        # `{feature}-dependencies-{environment key}` before.
        models.Q(name__contains="-depends-on-")
        | models.Q(name__regex=r"-dependencies-[A-Za-z0-9]+$"),
        feature__isnull=False,
    ).update(managed_by="dependency")


def reset_system_segment_managed_by(
    apps: Apps, _: BaseDatabaseSchemaEditor | None = None
) -> None:
    Segment = apps.get_model("segments", "Segment")
    Segment.objects.filter(managed_by__in=SYSTEM_SEGMENT_OWNERS).update(managed_by="")


class Migration(migrations.Migration):

    dependencies = [
        ("segments", "0032_add_segment_rules_data"),
        ("experimentation", "0016_add_delivery_connections_db_view_and_status"),
        ("release_pipelines_core", "0003_add_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsegment",
            name="managed_by",
            field=models.CharField(
                blank=True, choices=MANAGED_BY_CHOICES, default="", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="segment",
            name="managed_by",
            field=models.CharField(
                blank=True, choices=MANAGED_BY_CHOICES, default="", max_length=50
            ),
        ),
        migrations.RunPython(
            code=backfill_system_segment_managed_by,
            reverse_code=reset_system_segment_managed_by,
        ),
    ]
