# Generated by Django 2.2.14 on 2020-09-30 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environments', '0015_auto_20200916_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmplitudeConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='DateCreated')),
                ('environment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='amplitude_config', to='environments.Environment')),
            ],
        ),
    ]
