EVENT_NAMES_LIMIT = 500
EVENT_NAMES_CACHE_SECONDS = 300
CUSTOMER_EVENT_STATS_CACHE_SECONDS = 60
CUSTOMER_EVENT_NAMES_FAILURE_CACHE_SECONDS = 60

VERIFY_TIMEOUT_SECONDS = 5
EVENT_NAMES_TIMEOUT_SECONDS = 15
BACKGROUND_QUERY_TIMEOUT_SECONDS = 120

MISSING_EVENTS_TABLE_DETAIL = (
    "Events table not found in the configured database. Run the setup SQL to create it."
)
