# Generated by Django 3.2.13 on 2022-06-20 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20211208_1050'),
        ('tags', '0003_allow_null_tag_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('project', 'label')},
        ),
    ]
