# Generated by Django 3.2.23 on 2023-12-06 15:11
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def mark_permanent_tags_as_permanent(
    apps: Apps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    tag_model_class = apps.get_model("tags", "Tag")
    tag_model_class.objects.filter(
        label__in=["permanent", "protected", "donotdelete"]
    ).update(is_permanent=True)


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0004_add_uuid_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="is_permanent",
            field=models.BooleanField(
                default=False,
                help_text="When applied to a feature, it means this feature should be excluded from stale flags logic.",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="is_system_tag",
            field=models.BooleanField(
                default=False,
                help_text="Indicates that a tag was created by the system, not the user.",
            ),
        ),
        migrations.RunPython(
            mark_permanent_tags_as_permanent, reverse_code=migrations.RunPython.noop
        ),
    ]
