# Generated by Django 3.2.13 on 2022-06-22 16:13

from django.db import migrations, models
import uuid

from core.migration_helpers import AddDefaultUUIDs


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0004_add_unique_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(
            AddDefaultUUIDs("tags", "tag"),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="tag",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
