# Generated by Django 4.2.17 on 2025-01-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0007_alter_tag_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="type",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("STALE", "Stale"),
                    ("GITHUB", "Github"),
                    ("UNHEALTHY", "Unhealthy"),
                ],
                default="NONE",
                help_text="Field used to provide a consistent identifier for the FE and API to use for business logic.",
                max_length=100,
            ),
        ),
    ]
