name: Run E2E tests
description: Run the E2E tests against an environment

inputs:
  e2e_test_token:
    description: The authentication token used for E2E test endpoints.
    required: true
  slack_token:
    description: The slack authentication token.
    required: true
  environment:
    description: The value of the ENV environment variable to use for npm run env.
    required: true
  tests:
    description: The space separated list of E2E tests to be executed.
    required: false

runs:
  using: composite

  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        cache: npm
        node-version-file: frontend/.nvmrc
        cache-dependency-path: frontend/package-lock.json

    - name: NPM Install
      working-directory: frontend
      run: |
        npm ci
      shell: bash

    - name: Test with Chromedriver
      uses: nick-fields/retry@v3
      with:
        shell: bash
        command: |
          cd frontend
          node -v
          npm run env
          npm run test -- ${{ inputs.tests }}
        max_attempts: 2
        retry_on: error
        timeout_minutes: 10
      env:
        E2E_TEST_TOKEN: ${{ inputs.e2e_test_token }}
        SLACK_TOKEN: ${{ inputs.slack_token }}
        STATIC_ASSET_CDN_URL: /
        ENV: ${{ inputs.environment }}
        GITHUB_ACTION_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
