# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-22 15:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('environments', '0003_auto_20180925_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTrait',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('trait_key', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='DateCreated')),
                ('updated_date', models.DateTimeField(blank=True, editable=False, verbose_name='DateUpdate')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('identity', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='environments.Identity')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical trait',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTraitValue',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('int', 'Integer'), ('unicode', 'String'), ('bool', 'Boolean')], default='unicode', max_length=10, null=True)),
                ('boolean_value', models.NullBooleanField()),
                ('integer_value', models.IntegerField(blank=True, null=True)),
                ('string_value', models.CharField(blank=True, max_length=2000, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical trait value',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait_key', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='DateCreated')),
                ('updated_date', models.DateTimeField(auto_now_add=True, verbose_name='DateUpdate')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_traits', to='environments.Identity')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': 'User Traits',
            },
        ),
        migrations.CreateModel(
            name='TraitValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('int', 'Integer'), ('unicode', 'String'), ('bool', 'Boolean')], default='unicode', max_length=10, null=True)),
                ('boolean_value', models.NullBooleanField()),
                ('integer_value', models.IntegerField(blank=True, null=True)),
                ('string_value', models.CharField(blank=True, max_length=2000, null=True)),
                ('trait', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trait_value', to='environments.Trait')),
            ],
        ),
        migrations.AddField(
            model_name='historicaltraitvalue',
            name='trait',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='environments.Trait'),
        ),
        migrations.AlterUniqueTogether(
            name='trait',
            unique_together=set([('trait_key', 'identity')]),
        ),
    ]
