# Generated by Django 2.2.10 on 2020-02-19 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0024_auto_20200216_1924'),
        ('environments', '0008_webhook'),
        ('permissions', '0001_initial')
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentPermission',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='environment',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='DEPRECATED FIELD.', null=True),
        ),
        migrations.AlterField(
            model_name='environment',
            name='webhooks_enabled',
            field=models.BooleanField(default=False, help_text='DEPRECATED FIELD.'),
        ),
        migrations.CreateModel(
            name='UserPermissionGroupEnvironmentPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.BooleanField(default=False)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environments.Environment')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserPermissionGroup')),
                ('permissions', models.ManyToManyField(to='permissions.PermissionModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserEnvironmentPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.BooleanField(default=False)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environments.Environment')),
                ('permissions', models.ManyToManyField(to='permissions.PermissionModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
