# Generated by Django 2.2.15 on 2020-09-14 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0012_auto_20200504_1322'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='userenvironmentpermission',
                    name='environment',
                ),
                migrations.RemoveField(
                    model_name='userenvironmentpermission',
                    name='permissions',
                ),
                migrations.RemoveField(
                    model_name='userenvironmentpermission',
                    name='user',
                ),
                migrations.RemoveField(
                    model_name='userpermissiongroupenvironmentpermission',
                    name='environment',
                ),
                migrations.RemoveField(
                    model_name='userpermissiongroupenvironmentpermission',
                    name='group',
                ),
                migrations.RemoveField(
                    model_name='userpermissiongroupenvironmentpermission',
                    name='permissions',
                ),
                migrations.DeleteModel(
                    name='UserEnvironmentPermission',
                ),
                migrations.DeleteModel(
                    name='UserPermissionGroupEnvironmentPermission',
                ),
            ],
            database_operations=[
                # table names obtained by running sqlmigrate environment_permissions 0001
                migrations.AlterModelTable(
                    name='UserEnvironmentPermission',
                    table='environment_permissions_userenvironmentpermission'
                ),
                migrations.AlterModelTable(
                    name='UserPermissionGroupEnvironmentPermission',
                    table='environment_permissions_userpermissiongroupenvironmentpermi5008'
                )
            ]
        ),
        # EnvironmentPermissionModel is a proxy model so doesn't need splitting out
        migrations.DeleteModel(
            name='EnvironmentPermissionModel',
        ),
    ]
