# Generated by Django 2.2.14 on 2020-07-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0012_auto_20200504_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='amplitude_api_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
