# Generated by Django 2.2.16 on 2020-09-16 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0013_auto_20200914_0911'),
        ('environments', '0013_auto_20200619_1321'),
    ]

    operations = [
    ]
