# Generated by Django 2.2.16 on 2020-09-17 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0001_initial'),
        ('environments', '0013_auto_20200619_1321'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='identity',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='identity',
                    name='environment',
                ),
                migrations.RemoveField(
                    model_name='userenvironmentpermission',
                    name='environment',
                ),
                migrations.RemoveField(
                    model_name='userenvironmentpermission',
                    name='permissions',
                ),
                migrations.RemoveField(
                    model_name='userenvironmentpermission',
                    name='user',
                ),
                migrations.RemoveField(
                    model_name='userpermissiongroupenvironmentpermission',
                    name='environment',
                ),
                migrations.RemoveField(
                    model_name='userpermissiongroupenvironmentpermission',
                    name='group',
                ),
                migrations.RemoveField(
                    model_name='userpermissiongroupenvironmentpermission',
                    name='permissions',
                ),
                migrations.DeleteModel(
                    name='EnvironmentPermissionModel',
                ),
                migrations.AlterField(
                    model_name='historicaltrait',
                    name='identity',
                    field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                            on_delete=django.db.models.deletion.DO_NOTHING,
                                            related_name='+', to='identities.Identity'),
                ),
                migrations.AlterField(
                    model_name='trait',
                    name='identity',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            related_name='identity_traits',
                                            to='identities.Identity'),
                ),
                migrations.DeleteModel(
                    name='Identity',
                ),
                migrations.DeleteModel(
                    name='UserEnvironmentPermission',
                ),
                migrations.DeleteModel(
                    name='UserPermissionGroupEnvironmentPermission',
                ),
            ],
            database_operations=[]
        )
    ]
