# Generated by Django 2.2.16 on 2020-09-16 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0024_auto_20200916_0953'),
        ('environments', '0013_auto_20200914_0911'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='identity',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='identity',
                    name='environment',
                ),
                migrations.AlterField(
                    model_name='historicaltrait',
                    name='identity',
                    field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='identities.Identity'),
                ),
                migrations.AlterField(
                    model_name='trait',
                    name='identity',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_traits', to='identities.Identity'),
                ),
                migrations.DeleteModel(
                    name='Identity',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Identity',
                    table='identities_identity'
                )
            ]
        )
    ]
