# Generated by Django 2.2.16 on 2020-09-16 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0014_merge_20200916_1115'),
        ('environments', '0014_auto_20200916_0953'),
    ]

    operations = [
    ]
