module.exports = [
  {
    'day': '2025-07-28',
    'environment_document': 42924,
    'flags': 1424,
    'identities': 9533,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': null,
    },
    'traits': 24,
  },
  {
    'day': '2025-07-28',
    'environment_document': 0,
    'flags': 3000,
    'identities': 5000,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'flagsmith-js-sdk/9.3.0',
    },
    'traits': 12,
  },
  {
    'day': '2025-07-28',
    'environment_document': 0,
    'flags': 1100,
    'identities': 2000,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'python-client/3.2.1',
    },
    'traits': 120,
  },
  {
    'day': '2025-07-29',
    'environment_document': 81477,
    'flags': 5779,
    'identities': 29031,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': null,
    },
    'traits': 163,
  },
  {
    'day': '2025-07-29',
    'environment_document': 0,
    'flags': 577,
    'identities': 2900,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'flagsmith-js-sdk/9.3.0',
    },
    'traits': 163,
  },
  {
    'day': '2025-07-29',
    'environment_document': 0,
    'flags': 577,
    'identities': 2934,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'python-client/3.2.1',
    },
    'traits': 163,
  },
  {
    'day': '2025-07-30',
    'environment_document': 79628,
    'flags': 6555,
    'identities': 34084,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': null,
    },
    'traits': 142,
  },
  {
    'day': '2025-07-30',
    'environment_document': 0,
    'flags': 4555,
    'identities': 24084,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'python-client/3.2.1',
    },
    'traits': 170,
  },
  {
    'day': '2025-07-30',
    'environment_document': 0,
    'flags': 2555,
    'identities': 14084,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'flagsmith-js-sdk/9.3.0',
    },
    'traits': 10,
  },
  {
    'day': '2025-07-31',
    'environment_document': 0,
    'flags': 1743,
    'identities': 13998,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'flagsmith-js-sdk/9.3.0',
    },
    'traits': 67,
  },
  {
    'day': '2025-07-31',
    'environment_document': 0,
    'flags': 3743,
    'identities': 23998,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'python-client/3.2.1',
    },
    'traits': 37,
  },
  {
    'day': '2025-07-31',
    'environment_document': 76618,
    'flags': 6743,
    'identities': 33998,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': null,
    },
    'traits': 67,
  },
  {
    'day': '2025-08-01',
    'environment_document': 68093,
    'flags': 3780,
    'identities': 21087,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': null,
    },
    'traits': 22,
  },
  {
    'day': '2025-08-01',
    'environment_document': 0,
    'flags': 1780,
    'identities': 1087,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'flagsmith-js-sdk/9.3.0',
    },
    'traits': 12,
  },
  {
    'day': '2025-08-01',
    'environment_document': 0,
    'flags': 4780,
    'identities': 3087,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'python-client/3.2.1',
    },
    'traits': 12,
  },
  {
    'day': '2025-08-02',
    'environment_document': 54228,
    'flags': 1775,
    'identities': 2065,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': null,
    },
    'traits': 3,
  },
  {
    'day': '2025-08-02',
    'environment_document': 0,
    'flags': 775,
    'identities': 1065,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'flagsmith-js-sdk/9.3.0',
    },
    'traits': 3,
  },
  {
    'day': '2025-08-02',
    'environment_document': 0,
    'flags': 2775,
    'identities': 3065,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'python-client/3.2.1',
    },
    'traits': 3,
  },
  {
    'day': '2025-08-03',
    'environment_document': 56264,
    'flags': 1644,
    'identities': 3015,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': null,
    },
    'traits': 12,
  },
  {
    'day': '2025-08-03',
    'environment_document': 0,
    'flags': 644,
    'identities': 2015,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'flagsmith-js-sdk/9.3.0',
    },
    'traits': 12,
  },
  {
    'day': '2025-08-03',
    'environment_document': 0,
    'flags': 2644,
    'identities': 4015,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'python-client/3.2.1',
    },
    'traits': 12,
  },
  {
    'day': '2025-08-04',
    'environment_document': 66153,
    'flags': 3915,
    'identities': 21010,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': null,
    },
    'traits': 56,
  },
  {
    'day': '2025-08-04',
    'environment_document': 0,
    'flags': 2915,
    'identities': 11010,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'flagsmith-js-sdk/9.3.0',
    },
    'traits': 56,
  },
  {
    'day': '2025-08-04',
    'environment_document': 0,
    'flags': 4915,
    'identities': 31010,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'python-client/3.2.1',
    },
    'traits': 56,
  },
  {
    'day': '2025-08-05',
    'environment_document': 91259,
    'flags': 7664,
    'identities': 38603,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': null,
    },
    'traits': 114,
  },
  {
    'day': '2025-08-05',
    'environment_document': 0,
    'flags': 6664,
    'identities': 28603,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'flagsmith-js-sdk/9.3.0',
    },
    'traits': 114,
  },
  {
    'day': '2025-08-05',
    'environment_document': 0,
    'flags': 8664,
    'identities': 48603,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'python-client/3.2.1',
    },
    'traits': 114,
  },
  {
    'day': '2025-08-06',
    'environment_document': 78650,
    'flags': 2851,
    'identities': 17805,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': null,
    },
    'traits': 121,
  },
  {
    'day': '2025-08-06',
    'environment_document': 0,
    'flags': 1851,
    'identities': 7805,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'flagsmith-js-sdk/9.3.0',
    },
    'traits': 121,
  },
  {
    'day': '2025-08-06',
    'environment_document': 0,
    'flags': 3851,
    'identities': 27805,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'python-client/3.2.1',
    },
    'traits': 121,
  },
  {
    'day': '2025-08-07',
    'environment_document': 77559,
    'flags': 7983,
    'identities': 36117,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': null,
    },
    'traits': 44,
  },
  {
    'day': '2025-08-07',
    'environment_document': 0,
    'flags': 6983,
    'identities': 26117,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'flagsmith-js-sdk/9.3.0',
    },
    'traits': 44,
  },
  {
    'day': '2025-08-07',
    'environment_document': 0,
    'flags': 8983,
    'identities': 46117,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'python-client/3.2.1',
    },
    'traits': 44,
  },
  {
    'day': '2025-08-08',
    'environment_document': 69316,
    'flags': 4053,
    'identities': 17304,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': null,
    },
    'traits': 26,
  },
  {
    'day': '2025-08-08',
    'environment_document': 0,
    'flags': 3053,
    'identities': 7304,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'flagsmith-js-sdk/9.3.0',
    },
    'traits': 26,
  },
  {
    'day': '2025-08-08',
    'environment_document': 0,
    'flags': 5053,
    'identities': 27304,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'python-client/3.2.1',
    },
    'traits': 26,
  },
  {
    'day': '2025-08-09',
    'environment_document': 59740,
    'flags': 1609,
    'identities': 939,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': null,
    },
    'traits': 6,
  },
  {
    'day': '2025-08-09',
    'environment_document': 0,
    'flags': 609,
    'identities': 939,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'flagsmith-js-sdk/9.3.0',
    },
    'traits': 6,
  },
  {
    'day': '2025-08-09',
    'environment_document': 0,
    'flags': 2609,
    'identities': 939,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'python-client/3.2.1',
    },
    'traits': 6,
  },
  {
    'day': '2025-08-10',
    'environment_document': 61463,
    'flags': 1669,
    'identities': 3166,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': null,
    },
    'traits': null,
  },
  {
    'day': '2025-08-10',
    'environment_document': 0,
    'flags': 669,
    'identities': 2166,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'flagsmith-js-sdk/9.3.0',
    },
    'traits': null,
  },
  {
    'day': '2025-08-10',
    'environment_document': 0,
    'flags': 2669,
    'identities': 4166,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'python-client/3.2.1',
    },
    'traits': null,
  },
  {
    'day': '2025-08-11',
    'environment_document': 75394,
    'flags': 5783,
    'identities': 27593,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': null,
    },
    'traits': 19,
  },
  {
    'day': '2025-08-11',
    'environment_document': 0,
    'flags': 4783,
    'identities': 17593,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'flagsmith-js-sdk/9.3.1',
    },
    'traits': 19,
  },
  {
    'day': '2025-08-11',
    'environment_document': 0,
    'flags': 4783,
    'identities': 17593,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'flagsmith-js-sdk/9.3.0',
    },
    'traits': 19,
  },
  {
    'day': '2025-08-11',
    'environment_document': 0,
    'flags': 6783,
    'identities': 37593,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'python-client/3.2.1',
    },
    'traits': 19,
  },
  {
    'day': '2025-08-12',
    'environment_document': 81037,
    'flags': 5729,
    'identities': 26224,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': null,
    },
    'traits': 97,
  },
  {
    'day': '2025-08-12',
    'environment_document': 0,
    'flags': 4729,
    'identities': 16224,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'flagsmith-js-sdk/9.3.1',
    },
    'traits': 97,
  },
  {
    'day': '2025-08-12',
    'environment_document': 0,
    'flags': 4729,
    'identities': 16224,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'flagsmith-js-sdk/9.3.0',
    },
    'traits': 97,
  },
  {
    'day': '2025-08-12',
    'environment_document': 0,
    'flags': 6729,
    'identities': 36224,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'python-client/3.2.1',
    },
    'traits': 97,
  },
  {
    'day': '2025-08-13',
    'environment_document': 74869,
    'flags': 7912,
    'identities': 35475,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': null,
    },
    'traits': 40,
  },
  {
    'day': '2025-08-13',
    'environment_document': 0,
    'flags': 6912,
    'identities': 25475,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'flagsmith-js-sdk/9.3.0',
    },
    'traits': 40,
  },
  {
    'day': '2025-08-13',
    'environment_document': 0,
    'flags': 6912,
    'identities': 25475,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'flagsmith-js-sdk/9.3.1',
    },
    'traits': 40,
  },
  {
    'day': '2025-08-13',
    'environment_document': 0,
    'flags': 8912,
    'identities': 45475,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'python-client/3.2.1',
    },
    'traits': 40,
  },
  {
    'day': '2025-08-14',
    'environment_document': 81041,
    'flags': 4469,
    'identities': 23541,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': null,
    },
    'traits': 44,
  },
  {
    'day': '2025-08-14',
    'environment_document': 0,
    'flags': 3469,
    'identities': 13541,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'flagsmith-js-sdk/9.3.0',
    },
    'traits': 44,
  },
  {
    'day': '2025-08-14',
    'environment_document': 0,
    'flags': 5469,
    'identities': 33541,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'python-client/3.2.1',
    },
    'traits': 44,
  },
  {
    'day': '2025-08-15',
    'environment_document': 69007,
    'flags': 4242,
    'identities': 18971,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': null,
    },
    'traits': 59,
  },
  {
    'day': '2025-08-15',
    'environment_document': 0,
    'flags': 3242,
    'identities': 8971,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'flagsmith-js-sdk/9.3.1',
    },
    'traits': 59,
  },
  {
    'day': '2025-08-15',
    'environment_document': 0,
    'flags': 3242,
    'identities': 8971,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'flagsmith-js-sdk/9.3.0',
    },
    'traits': 59,
  },
  {
    'day': '2025-08-15',
    'environment_document': 0,
    'flags': 5242,
    'identities': 28971,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'python-client/3.2.1',
    },
    'traits': 59,
  },
  {
    'day': '2025-08-15',
    'environment_document': 0,
    'flags': 5242,
    'identities': 28971,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'python-client/4.2.1',
    },
    'traits': 59,
  },
  {
    'day': '2025-08-16',
    'environment_document': 56997,
    'flags': 1611,
    'identities': 3955,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': null,
    },
    'traits': 12,
  },
  {
    'day': '2025-08-16',
    'environment_document': 0,
    'flags': 611,
    'identities': 2955,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'flagsmith-js-sdk/9.3.1',
    },
    'traits': 12,
  },
  {
    'day': '2025-08-16',
    'environment_document': 0,
    'flags': 2611,
    'identities': 4955,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'python-client/3.2.1',
    },
    'traits': 12,
  },
  {
    'day': '2025-08-16',
    'environment_document': 0,
    'flags': 2611,
    'identities': 4955,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'python-client/4.2.1',
    },
    'traits': 12,
  },
  {
    'day': '2025-08-17',
    'environment_document': 53245,
    'flags': 1626,
    'identities': 3088,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': null,
    },
    'traits': null,
  },
  {
    'day': '2025-08-17',
    'environment_document': 0,
    'flags': 626,
    'identities': 2088,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'flagsmith-js-sdk/9.3.1',
    },
    'traits': null,
  },
  {
    'day': '2025-08-17',
    'environment_document': 0,
    'flags': 2626,
    'identities': 4088,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'python-client/3.2.1',
    },
    'traits': null,
  },
  {
    'day': '2025-08-17',
    'environment_document': 0,
    'flags': 2626,
    'identities': 4088,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'python-client/4.2.1',
    },
    'traits': null,
  },
  {
    'day': '2025-08-18',
    'environment_document': 63936,
    'flags': 2690,
    'identities': 17005,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': null,
    },
    'traits': 52,
  },
  {
    'day': '2025-08-18',
    'environment_document': 0,
    'flags': 1690,
    'identities': 7005,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'flagsmith-js-sdk/9.3.1',
    },
    'traits': 52,
  },
  {
    'day': '2025-08-18',
    'environment_document': 0,
    'flags': 3690,
    'identities': 27005,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'python-client/3.2.1',
    },
    'traits': 52,
  },
  {
    'day': '2025-08-19',
    'environment_document': 83474,
    'flags': 5035,
    'identities': 26127,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': null,
    },
    'traits': 102,
  },
  {
    'day': '2025-08-19',
    'environment_document': 0,
    'flags': 4035,
    'identities': 16127,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'flagsmith-js-sdk/9.3.1',
    },
    'traits': 102,
  },
  {
    'day': '2025-08-19',
    'environment_document': 0,
    'flags': 6035,
    'identities': 36127,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'python-client/3.2.1',
    },
    'traits': 102,
  },
  {
    'day': '2025-08-20',
    'environment_document': 85023,
    'flags': 11372,
    'identities': 47939,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': null,
    },
    'traits': 94,
  },
  {
    'day': '2025-08-20',
    'environment_document': 0,
    'flags': 1372,
    'identities': 37939,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'flagsmith-js-sdk/9.3.1',
    },
    'traits': 94,
  },
  {
    'day': '2025-08-20',
    'environment_document': 0,
    'flags': 21372,
    'identities': 57939,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'python-client/3.2.1',
    },
    'traits': 94,
  },
  {
    'day': '2025-08-21',
    'environment_document': 87286,
    'flags': 6016,
    'identities': 29012,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': null,
    },
    'traits': 71,
  },
  {
    'day': '2025-08-21',
    'environment_document': 0,
    'flags': 5016,
    'identities': 19012,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'flagsmith-js-sdk/9.3.1',
    },
    'traits': 71,
  },
  {
    'day': '2025-08-21',
    'environment_document': 0,
    'flags': 7016,
    'identities': 39012,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'python-client/3.2.1',
    },
    'traits': 71,
  },
  {
    'day': '2025-08-22',
    'environment_document': 66818,
    'flags': 4626,
    'identities': 22397,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': null,
    },
    'traits': 41,
  },
  {
    'day': '2025-08-22',
    'environment_document': 0,
    'flags': 3626,
    'identities': 12397,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'flagsmith-js-sdk/9.3.1',
    },
    'traits': 41,
  },
  {
    'day': '2025-08-22',
    'environment_document': 0,
    'flags': 5626,
    'identities': 32397,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'python-client/3.2.1',
    },
    'traits': 41,
  },
  {
    'day': '2025-08-23',
    'environment_document': 57317,
    'flags': 1611,
    'identities': 4402,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': null,
    },
    'traits': null,
  },
  {
    'day': '2025-08-23',
    'environment_document': 0,
    'flags': 611,
    'identities': 3402,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'flagsmith-js-sdk/9.3.1',
    },
    'traits': null,
  },
  {
    'day': '2025-08-23',
    'environment_document': 0,
    'flags': 2611,
    'identities': 5402,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'python-client/3.2.1',
    },
    'traits': null,
  },
  {
    'day': '2025-08-24',
    'environment_document': 57572,
    'flags': 1621,
    'identities': 4705,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': null,
    },
    'traits': 9,
  },
  {
    'day': '2025-08-24',
    'environment_document': 0,
    'flags': 621,
    'identities': 3705,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'flagsmith-js-sdk/9.3.1',
    },
    'traits': 9,
  },
  {
    'day': '2025-08-24',
    'environment_document': 0,
    'flags': 2621,
    'identities': 5705,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'python-client/4.2.1',
    },
    'traits': 9,
  },
  {
    'day': '2025-08-25',
    'environment_document': 70062,
    'flags': 5030,
    'identities': 25772,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': null,
    },
    'traits': 177,
  },
  {
    'day': '2025-08-25',
    'environment_document': 0,
    'flags': 4030,
    'identities': 15772,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'flagsmith-js-sdk/9.3.1',
    },
    'traits': 177,
  },
  {
    'day': '2025-08-25',
    'environment_document': 0,
    'flags': 6030,
    'identities': 35772,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'python-client/4.2.1',
    },
    'traits': 177,
  },
  {
    'day': '2025-08-26',
    'environment_document': 77477,
    'flags': 7488,
    'identities': 37001,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': null,
    },
    'traits': 122,
  },
  {
    'day': '2025-08-26',
    'environment_document': 0,
    'flags': 6488,
    'identities': 27001,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'flagsmith-js-sdk/9.3.1',
    },
    'traits': 122,
  },
  {
    'day': '2025-08-26',
    'environment_document': 0,
    'flags': 8488,
    'identities': 47001,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'python-client/4.2.1',
    },
    'traits': 122,
  },
  {
    'day': '2025-08-27',
    'environment_document': 31920,
    'flags': 2045,
    'identities': 9461,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': null,
    },
    'traits': 14,
  },
  {
    'day': '2025-08-27',
    'environment_document': 0,
    'flags': 1045,
    'identities': 8461,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'flagsmith-js-sdk/9.3.1',
    },
    'traits': 14,
  },
  {
    'day': '2025-08-27',
    'environment_document': 0,
    'flags': 3045,
    'identities': 9461,
    'labels': {
      'client_application_name': null,
      'client_application_version': null,
      'user_agent': 'python-client/4.2.1',
    },
    'traits': 14,
  },
]
