# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-09 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='related_object_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='related_object_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='environment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='environments.Environment'),
        ),
    ]
