# Generated by Django 3.2.13 on 2022-05-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auto_20200504_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='skip_signals',
            field=models.CharField(blank=True, help_text='comma separated list of signal functions to skip', max_length=500, null=True),
        ),
    ]
