# Generated by Django 3.2.13 on 2022-06-07 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0001_initial'),
        ('audit', '0005_auditlog_skip_signals'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='master_api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='api_keys.masterapikey'),
        ),
    ]
