# Generated by Django 3.2.13 on 2022-06-01 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_auditlog_master_api_key'),
        ('audit', '0005_auditlog_skip_signals'),
    ]

    operations = [
    ]
