# Generated by Django 3.2.16 on 2022-11-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_auditlog_is_system_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='history_record_class_path',
            field=models.CharField(max_length=200, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='history_record_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
