# Generated by Django 3.2.18 on 2023-02-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0010_do_nothing_on_project_or_environment_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='related_object_uuid',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
