# Generated by Django 3.2.18 on 2023-05-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0011_auditlog_related_object_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auditlog",
            old_name="skip_signals",
            new_name="skip_subscribers",
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="skip_subscribers",
            field=models.CharField(
                blank=True,
                help_text="comma separated list of signal/hooks functions/methods to skip",
                max_length=500,
                null=True,
            ),
        ),
    ]
