# Generated by Django 2.2.17 on 2021-03-12 16:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('features', '0030_merge_20210305_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultivariateFeatureOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('int', 'Integer'), ('unicode', 'String'), ('bool', 'Boolean')], default='unicode', max_length=10, null=True)),
                ('boolean_value', models.NullBooleanField()),
                ('integer_value', models.IntegerField(blank=True, null=True)),
                ('string_value', models.CharField(blank=True, max_length=2000, null=True)),
                ('default_percentage_allocation', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multivariate_options', to='features.Feature')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MultivariateFeatureStateValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_allocation', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('feature_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multivariate_feature_state_values', to='features.FeatureState')),
                ('multivariate_feature_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multivariate.MultivariateFeatureOption')),
            ],
        ),
    ]
