# Generated by Django 2.2.24 on 2021-07-30 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0032_update_feature_type"),
        ("multivariate", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="multivariatefeaturestatevalue",
            unique_together={("feature_state", "multivariate_feature_option")},
        ),
    ]
