# Generated by Django 3.2.13 on 2022-06-22 14:55

from django.db import migrations, models
import uuid

from core.migration_helpers import AddDefaultUUIDs


class Migration(migrations.Migration):

    dependencies = [
        ("multivariate", "0004_alter_multivariatefeatureoption_string_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="multivariatefeatureoption",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(
            AddDefaultUUIDs("multivariate", "multivariatefeatureoption"),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="multivariatefeatureoption",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="multivariatefeaturestatevalue",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(
            AddDefaultUUIDs("multivariate", "multivariatefeaturestatevalue"),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="multivariatefeaturestatevalue",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
