# Generated by Django 3.2.19 on 2023-06-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multivariate', '0006_add_audit_log_events_form_multivariate_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmultivariatefeatureoption',
            name='boolean_value',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='multivariatefeatureoption',
            name='boolean_value',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
