# Generated by Django 3.2.20 on 2023-10-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multivariate', '0007_alter_boolean_values'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmultivariatefeatureoption',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical multivariate feature option', 'verbose_name_plural': 'historical multivariate feature options'},
        ),
        migrations.AlterModelOptions(
            name='historicalmultivariatefeaturestatevalue',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical multivariate feature state value', 'verbose_name_plural': 'historical multivariate feature state values'},
        ),
        migrations.AlterField(
            model_name='historicalmultivariatefeatureoption',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmultivariatefeaturestatevalue',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
