# Generated by Django 3.2.25 on 2024-08-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multivariate', '0007_alter_boolean_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmultivariatefeatureoption',
            name='string_value',
            field=models.CharField(blank=True, max_length=2000000, null=True),
        ),
        migrations.AlterField(
            model_name='multivariatefeatureoption',
            name='string_value',
            field=models.CharField(blank=True, max_length=2000000, null=True),
        ),
    ]
