# Generated by Django 5.2.14 on 2026-06-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0066_constrain_feature_type"),
        ("multivariate", "0008_make_feature_value_size_configurable"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmultivariatefeatureoption",
            name="key",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="multivariatefeatureoption",
            name="key",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="multivariatefeatureoption",
            unique_together={("feature", "key")},
        ),
    ]
