# Generated by Django 5.2.14 on 2026-06-04 05:49

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0066_constrain_feature_type"),
        ("multivariate", "0008_make_feature_value_size_configurable"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmultivariatefeatureoption",
            name="key",
            field=models.CharField(
                blank=True,
                help_text="A stable, human-readable identifier for the variant.",
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-zA-Z0-9_]+\\Z"),
                        "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                        "invalid",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="multivariatefeatureoption",
            name="key",
            field=models.CharField(
                blank=True,
                help_text="A stable, human-readable identifier for the variant.",
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-zA-Z0-9_]+\\Z"),
                        "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                        "invalid",
                    )
                ],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="multivariatefeatureoption",
            unique_together={("feature", "key")},
        ),
    ]
