# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-01-29T13:53:55+00:00

from __future__ import annotations

from typing import Literal, TypedDict

from typing_extensions import NotRequired


class Json(TypedDict):
    pass


class PostAnnotationsCmd(TypedDict):
    dashboardId: NotRequired[int]
    dashboardUID: NotRequired[str]
    data: NotRequired[Json]
    panelId: NotRequired[int]
    tags: NotRequired[list[str]]
    text: str
    time: NotRequired[int]
    timeEnd: NotRequired[int]


class EmbeddedContactPoint(TypedDict):
    disableResolveMessage: NotRequired[bool]
    name: NotRequired[str]
    provenance: NotRequired[str]
    settings: Json
    type: Literal[
        "alertmanager",
        "dingding",
        "discord",
        "email",
        "googlechat",
        "kafka",
        "line",
        "opsgenie",
        "pagerduty",
        "pushover",
        "sensugo",
        "slack",
        "teams",
        "telegram",
        "threema",
        "victorops",
        "webhook",
        "wecom",
    ]
    uid: NotRequired[str]
