# Generated by Django 3.2.15 on 2022-09-13 19:18
import typing

from django.db import migrations

from environments.permissions.constants import (
    CREATE_CHANGE_REQUEST,
    APPROVE_CHANGE_REQUEST,
    UPDATE_FEATURE_STATE,
)
from permissions.models import ENVIRONMENT_PERMISSION_TYPE

from core.migration_helpers import create_new_environment_permissions


def add_change_request_permissions(apps, schema_editor):
    PermissionModel = apps.get_model("permissions", "PermissionModel")
    UserEnvironmentPermission = apps.get_model(
        "environment_permissions",
        "UserEnvironmentPermission",
    )
    UserPermissionGroupEnvironmentPermission = apps.get_model(
        "environment_permissions",
        "UserPermissionGroupEnvironmentPermission",
    )

    create_cr_permission_model, _ = PermissionModel.objects.get_or_create(
        key=CREATE_CHANGE_REQUEST,
        description="Permission to create change requests in the given environment.",
        type=ENVIRONMENT_PERMISSION_TYPE,
    )

    approve_cr_permission_model, _ = PermissionModel.objects.get_or_create(
        key=APPROVE_CHANGE_REQUEST,
        description="Permission to approve change requests in the given environment.",
        type=ENVIRONMENT_PERMISSION_TYPE,
    )

    new_permissions = [create_cr_permission_model, approve_cr_permission_model]

    create_new_environment_permissions(
        UPDATE_FEATURE_STATE,
        UserEnvironmentPermission,
        "userenvironmentpermission",
        new_permissions,
    )
    create_new_environment_permissions(
        UPDATE_FEATURE_STATE,
        UserPermissionGroupEnvironmentPermission,
        "userpermissiongroupenvironmentpermission",
        new_permissions,
    )


def remove_change_request_permissions(apps, schema_editor):
    PermissionModel = apps.get_model("permissions", "PermissionModel")

    PermissionModel.objects.filter(
        key__in=[CREATE_CHANGE_REQUEST, APPROVE_CHANGE_REQUEST]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("environment_permissions", "0003_add_manage_identities_permission"),
    ]

    operations = [
        migrations.RunPython(
            add_change_request_permissions,
            reverse_code=remove_change_request_permissions,
        )
    ]
