# Generated by Django 3.2.18 on 2023-06-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment_permissions', '0006_merge_duplicate_permissions'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userenvironmentpermission',
            constraint=models.UniqueConstraint(fields=('user', 'environment'), name='unique_user_environment_permission'),
        ),
        migrations.AddConstraint(
            model_name='userpermissiongroupenvironmentpermission',
            constraint=models.UniqueConstraint(fields=('group', 'environment'), name='unique_group_environment_permission'),
        ),
    ]
