# Generated by Django 3.2.20 on 2023-07-26 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('environment_permissions', '0007_add_unique_permission_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userenvironmentpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environment_permissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
