# Generated by Django 3.2.18 on 2023-05-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows_core", "0005_soft_delete_change_requests"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalchangerequest",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical change request",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalchangerequestapproval",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical change request approval",
            },
        ),
        migrations.AlterField(
            model_name="historicalchangerequest",
            name="history_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="historicalchangerequestapproval",
            name="history_date",
            field=models.DateTimeField(),
        ),
    ]
