# Generated by Django 3.2.24 on 2024-03-07 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflows_core', '0008_remove_redundant_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
