# Generated by Django 4.2.15 on 2024-09-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows_core", "0009_prevent_cascade_delete_from_user_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="changerequest",
            name="ignore_conflicts",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalchangerequest",
            name="ignore_conflicts",
            field=models.BooleanField(default=False),
        ),
    ]
