# Generated by Django 4.2.17 on 2024-12-16 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflows_core", "0011_add_project_to_change_requests"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="changerequest",
            options={"ordering": ("id",)},
        ),
    ]
