# Generated by Django 5.2.15 on 2026-07-31 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflows_core", "0012_alter_changerequest_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="changerequest",
            options={"ordering": ("-id",)},
        ),
    ]
