import * as fs from 'fs'
import * as path from 'path'

const BASELINES_DIR = path.resolve(__dirname, 'visual-regression-snapshots')
const SCREENSHOTS_DIR = path.resolve(__dirname, 'visual-regression-screenshots')
const COMPARE_TEST_FILE = path.resolve(__dirname, 'tests', '_visual-regression-compare.pw.ts')

/**
 * Generates a Playwright test file that compares each captured screenshot
 * against its baseline using toMatchSnapshot(). Run this AFTER E2E tests
 * complete to get a Playwright HTML report with diff viewer.
 *
 * Screenshots and baselines use the same flat naming convention:
 *   {testFileName}--{snapshotName}.png (dots replaced with dashes)
 *   e.g. flag-tests-pw-ts--features-list.png
 */

if (!fs.existsSync(SCREENSHOTS_DIR)) {
  console.log('No screenshots found — run E2E tests with VISUAL_REGRESSION=1 first.')
  process.exit(0)
}

// Collect screenshots
const screenshots = fs
  .readdirSync(SCREENSHOTS_DIR)
  .filter((f) => f.endsWith('.png'))

if (screenshots.length === 0) {
  console.log('No screenshots to compare.')
  process.exit(0)
}

if (!fs.existsSync(BASELINES_DIR)) {
  fs.mkdirSync(BASELINES_DIR, { recursive: true })
}

// Build test entries from all screenshots
const pairs: { file: string; label: string }[] = []
for (const png of screenshots) {
  const label = png
    .replace('.png', '')
    .replace(/^(.+?)--(.+)$/, (_, testFile, name) => {
      const restored = testFile.replace(/-pw-ts$/, '.pw.ts').replace(/-/g, '.')
      return `${restored} / ${name.replace(/-/g, ' ')}`
    })
  pairs.push({ file: png, label })
}

// Generate Playwright test file
const testCases = pairs
  .map(({ file, label }) => {
    const screenshotPath = path.join(SCREENSHOTS_DIR, file).replace(/\\/g, '\\\\').replace(/'/g, "\\'")
    return `
  test('${label}', async () => {
    const screenshot = fs.readFileSync('${screenshotPath}')
    expect(screenshot).toMatchSnapshot('${file}', {
      maxDiffPixels: 300,
      threshold: 0.02,
    })
  })`
  })
  .join('\n')

const testContent = `// Auto-generated by compare-visual-regression.ts — do not edit
import { test, expect } from '@playwright/test'
import * as fs from 'fs'

test.describe('Visual Regression', () => {
${testCases}
})
`

fs.writeFileSync(COMPARE_TEST_FILE, testContent)
console.log(`Generated ${pairs.length} comparison tests → ${COMPARE_TEST_FILE}`)
