# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-20 12:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name=b'DateCreated')),
                ('api_key', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name=b'DateCreated')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField()),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featurestates', to='api.Environment')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featurestates', to='api.Feature')),
            ],
        ),
        migrations.CreateModel(
            name='FFAdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=2000)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name=b'DateCreated')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='api.Environment')),
            ],
            options={
                'verbose_name_plural': 'Identities',
            },
        ),
        migrations.CreateModel(
            name='IdentityFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField()),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identityfeatures', to='api.Feature')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identityfeatures', to='api.Identity')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name=b'DateCreated')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.Organisation')),
            ],
        ),
        migrations.AddField(
            model_name='feature',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='api.Project'),
        ),
        migrations.AddField(
            model_name='environment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='api.Project'),
        ),
    ]
