# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-19 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identity',
            old_name='version',
            new_name='environment',
        ),
        migrations.AlterUniqueTogether(
            name='identityfeature',
            unique_together=set([('feature', 'identity')]),
        ),
    ]
