# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-14 14:29
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_auto_20170619_1255"),
    ]

    operations = [
        migrations.AddField(
            model_name="identity",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
