# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-14 15:57
from __future__ import unicode_literals

from django.db import migrations, models

import app


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_identity_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identity',
            name='uuid',
        ),
        migrations.AddField(
            model_name='identity',
            name='hash',
            field=models.CharField(default=app.utils.create_hash, max_length=100, unique=True),
        ),
    ]
