# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-14 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180514_1557'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='featurestate',
            unique_together=set([('feature', 'environment')]),
        ),
    ]
