# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-17 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180517_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurestate',
            name='identity',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identityfeatures', to='api.Identity'),
        ),
    ]
