# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-17 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180517_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='hash',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
