# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180517_1646'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FFAdminUser',
        ),
    ]
