# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180522_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='default_value',
            new_name='initial_value',
        ),
    ]
