# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20180524_1521'),
        ('projects', '0001_initial')
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='organisation',
        ),
        migrations.AlterField(
            model_name='environment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='projects.Project'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
