# Generated by Django 4.2.21 on 2025-05-20 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0027_add_create_project_level_change_requests_permission"),
        ("environments", "0037_add_uuid_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineStage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("order", models.IntegerField()),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline_stages",
                        to="environments.environment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReleasePipeline",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="release_pipelines",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PipelineStageTrigger",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[("ON_ENTER", "Trigger when flag enters stage")],
                        default="ON_ENTER",
                        max_length=50,
                    ),
                ),
                ("trigger_body", models.TextField(null=True)),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggers",
                        to="release_pipelines_core.pipelinestage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PipelineStageAction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("ENABLE_FEATURE", "Enable Feature for the environment"),
                            ("DISABLE_FEATURE", "Disable Feature for the environment"),
                        ],
                        default="ENABLE_FEATURE",
                        max_length=50,
                    ),
                ),
                ("action_body", models.TextField(null=True)),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="release_pipelines_core.pipelinestage",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pipelinestage",
            name="pipeline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stages",
                to="release_pipelines_core.releasepipeline",
            ),
        ),
    ]
