# Generated by Django 4.2.22 on 2025-07-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release_pipelines_core", "0001_add_release_pipelines"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelinestageaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("TOGGLE_FEATURE", "Enable/Disable Feature for the environment"),
                    (
                        "UPDATE_FEATURE_VALUE",
                        "Update Feature Value for the environment",
                    ),
                    (
                        "TOGGLE_FEATURE_FOR_SEGMENT",
                        "Enable/Disable Feature for a specific segment",
                    ),
                    (
                        "UPDATE_FEATURE_VALUE_FOR_SEGMENT",
                        "Update Feature Value for a specific segment",
                    ),
                    ("PHASED_ROLLOUT", "Create Phased Rollout"),
                ],
                default="TOGGLE_FEATURE",
                max_length=50,
            ),
        ),
    ]
