# Generated by Django 4.2.21 on 2025-05-26 07:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("release_pipelines_core", "0001_wip_release_pipeline"),
    ]

    operations = [
        migrations.AddField(
            model_name="releasepipeline",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="releasepipeline",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("ACTIVE", "Active"),
                    ("ARCHIVED", "Archived"),
                ],
                default="DRAFT",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="pipelinestage",
            name="order",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MaxValueValidator(30)]
            ),
        ),
        migrations.AlterField(
            model_name="pipelinestageaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("TOGGLE_FEATURE", "Enable/Disable Feature for the environment"),
                    (
                        "TOGGLE_FEATURE_FOR_SEGMENT",
                        "Enable/Disable Feature for a specific segment",
                    ),
                ],
                default="TOGGLE_FEATURE",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="pipelinestagetrigger",
            name="stage",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trigger",
                to="release_pipelines_core.pipelinestage",
            ),
        ),
        migrations.AlterField(
            model_name="pipelinestagetrigger",
            name="trigger_type",
            field=models.CharField(
                choices=[
                    ("ON_ENTER", "Trigger when flag enters stage"),
                    ("WAIT_FOR", "Trigger after waiting for x amount of time"),
                ],
                default="ON_ENTER",
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="pipelinestage",
            constraint=models.UniqueConstraint(
                fields=("pipeline", "order"), name="unique_pipeline_stage_order"
            ),
        ),
    ]
