# Generated by Django 4.2.22 on 2025-07-17 09:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid

from core.migration_helpers import AddDefaultUUIDs


class Migration(migrations.Migration):

    dependencies = [
        ("environments", "0037_add_uuid_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api_keys", "0003_masterapikey_is_admin"),
        ("release_pipelines_core", "0001_add_release_pipelines"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelinestage",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="pipelinestage",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(
            AddDefaultUUIDs("release_pipelines_core", "pipelinestage"),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="pipelinestage",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="pipelinestageaction",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="pipelinestageaction",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(
            AddDefaultUUIDs("release_pipelines_core", "pipelinestageaction"),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="pipelinestageaction",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="pipelinestagetrigger",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="pipelinestagetrigger",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(
            AddDefaultUUIDs("release_pipelines_core", "pipelinestagetrigger"),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="pipelinestagetrigger",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
