# Generated by Django 4.2.22 on 2025-08-06 02:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins  # type: ignore[import-untyped]


class Migration(migrations.Migration):

    dependencies = [
        ("segments", "0029_add_is_system_segment"),
        ("release_pipelines_core", "0001_add_release_pipelines"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelinestageaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("TOGGLE_FEATURE", "Enable/Disable Feature for the environment"),
                    (
                        "UPDATE_FEATURE_VALUE",
                        "Update Feature Value for the environment",
                    ),
                    (
                        "TOGGLE_FEATURE_FOR_SEGMENT",
                        "Enable/Disable Feature for a specific segment",
                    ),
                    (
                        "UPDATE_FEATURE_VALUE_FOR_SEGMENT",
                        "Update Feature Value for a specific segment",
                    ),
                    ("PHASED_ROLLOUT", "Create Phased Rollout"),
                ],
                default="TOGGLE_FEATURE",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="PhasedRolloutState",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "initial_split",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ]
                    ),
                ),
                (
                    "increase_by",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ]
                    ),
                ),
                ("increase_every", models.DurationField()),
                (
                    "current_split",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ]
                    ),
                ),
                ("is_rollout_complete", models.BooleanField(default=False)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rollout_segment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phased_rollout_state",
                        to="segments.segment",
                    ),
                ),
            ],
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
