# Generated by Django 4.2.22 on 2025-08-14 11:00

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("release_pipelines_core", "0002_add_phased_rollout"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreleasepipeline",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2025, 8, 14, 11, 0, 52, 12907, tzinfo=datetime.timezone.utc
                ),
                editable=False,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="releasepipeline",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
