# Generated by Django 4.2.21 on 2025-06-03 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("release_pipelines_core", "0002_wip_release_pipeline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="releasepipeline",
            name="status",
        ),
        migrations.AddField(
            model_name="releasepipeline",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="releasepipeline",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_release_pipelines",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pipelinestageaction",
            name="action_body",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="pipelinestageaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("TOGGLE_FEATURE", "Enable/Disable Feature for the environment"),
                    (
                        "UPDATE_FEATURE_VALUE",
                        "Update Feature Value for the environment",
                    ),
                    (
                        "TOGGLE_FEATURE_FOR_SEGMENT",
                        "Enable/Disable Feature for a specific segment",
                    ),
                    (
                        "UPDATE_FEATURE_FOR_SEGMENT",
                        "Update Feature Value for a specific segment",
                    ),
                ],
                default="TOGGLE_FEATURE",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="pipelinestagetrigger",
            name="trigger_body",
            field=models.JSONField(null=True),
        ),
    ]
