SKIP = "SKIP"
OVERWRITE_DESTRUCTIVE = "OVERWRITE_DESTRUCTIVE"
FEATURE_IMPORT_STRATEGIES = (
    (SKIP, "Skip"),
    (OVERWRITE_DESTRUCTIVE, "Overwrite Destructive"),
)

MAX_FEATURE_EXPORT_SIZE = 1000_000
MAX_FEATURE_IMPORT_SIZE = MAX_FEATURE_EXPORT_SIZE


SUCCESS = "SUCCESS"
PROCESSING = "PROCESSING"
FAILED = "FAILED"

FEATURE_EXPORT_STATUSES = FEATURE_IMPORT_STATUSES = (
    (SUCCESS, "Success"),
    (PROCESSING, "Processing"),
    (FAILED, "Failed"),
)
