ENVIRONMENTS_V2_PARTITION_KEY = "environment_id"
ENVIRONMENTS_V2_SORT_KEY = "document_key"

ENVIRONMENTS_V2_ENVIRONMENT_META_DOCUMENT_KEY = "_META"

ENVIRONMENTS_V2_SECONDARY_INDEX = "environment_api_key-index"
ENVIRONMENTS_V2_SECONDARY_INDEX_PARTITION_KEY = "environment_api_key"

DYNAMODB_MAX_BATCH_WRITE_ITEM_COUNT = 25
IDENTITIES_PAGINATION_LIMIT = 1000
