# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
