# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-20 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='has_requested_features',
            field=models.BooleanField(default=False),
        ),
    ]
