# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_organisation_has_requested_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='webhook_notification_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
