# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-05 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_organisation_webhook_notification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='DateCreated'),
            preserve_default=False,
        ),
    ]
