# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-18 10:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


forward_sql = 'INSERT INTO organisations_userorganisation (user_id, organisation_id, date_joined, "role") ' \
              'SELECT ffadminuser_id, organisation_id, NOW(), \'ADMIN\' ' \
              'FROM users_ffadminuser_organisations'

reverse_sql = 'INSERT INTO users_ffadminuser_organisations (ffadminuser_id, organisation_id) ' \
              'SELECT user_id, organisation_id ' \
              'FROM organisations_userorganisation'


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0013_organisation_alerted_over_plan_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User')], max_length=50)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunSQL(sql=forward_sql, reverse_sql=reverse_sql),
    ]
