# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-24 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0014_userorganisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='free_to_use_subscription',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='paid_subscription',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='pending_cancellation',
        ),
        migrations.AlterField(
            model_name='userorganisation',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('USER', 'USER')], max_length=50),
        ),
    ]
