# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-25 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0016_auto_20190924_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cancellation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
