# Generated by Django 2.2.12 on 2020-06-19 15:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0020_auto_20200222_1159'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userorganisation',
            unique_together={('user', 'organisation')},
        ),
    ]
