# Generated by Django 2.2.24 on 2021-08-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0025_auto_20210223_1603"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="notes",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="payment_method",
            field=models.CharField(
                choices=[("ChargeBee", "ChargeBee"), ("Xero", "Xero")],
                default="ChargeBee",
                max_length=20,
            ),
        ),
    ]
