# Generated by Django 2.2.24 on 2021-10-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0026_auto_20210907_1232"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="restrict_project_create_to_admin",
            field=models.BooleanField(default=False),
        ),
    ]
