# Generated by Django 2.2.24 on 2021-12-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0027_organisation_restrict_project_create_to_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationwebhook',
            name='secret',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
