# Generated by Django 2.2.24 on 2021-12-13 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20210223_1603'),
        ('permissions', '0004_add_create_project_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0027_organisation_restrict_project_create_to_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationPermissionModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('permissions.permissionmodel',),
        ),
        migrations.CreateModel(
            name='UserPermissionGroupOrganisationPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserPermissionGroup')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation')),
                ('permissions', models.ManyToManyField(blank=True, to='permissions.PermissionModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserOrganisationPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation')),
                ('permissions', models.ManyToManyField(blank=True, to='permissions.PermissionModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
