# Generated by Django 2.2.24 on 2021-11-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0027_organisation_restrict_project_create_to_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='max_api_calls',
            field=models.BigIntegerField(default=50000),
        ),
    ]
