# Generated by Django 2.2.25 on 2022-01-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0028_organisationwebhook_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='max_api_calls',
            field=models.BigIntegerField(default=50000),
        ),
    ]
