# Generated by Django 2.2.26 on 2022-01-28 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0028_subscription_max_api_calls'),
        ('organisations', '0028_organisationwebhook_secret'),
    ]

    operations = [
    ]
