# Generated by Django 3.2.12 on 2022-03-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0029_add_max_api_calls_to_subscription_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorganisation',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User')], max_length=50),
        ),
    ]
