# Generated by Django 3.2.12 on 2022-03-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0029_add_max_api_calls_to_subscription_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationwebhook',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
