# Generated by Django 3.2.13 on 2022-06-22 15:33

from django.db import migrations, models
import uuid

from core.migration_helpers import AddDefaultUUIDs


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0031_alter_subscription_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(
            AddDefaultUUIDs("organisations", "organisation"),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="organisation",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(
            AddDefaultUUIDs("organisations", "subscription"),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="subscription",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="organisationwebhook",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(
            AddDefaultUUIDs("organisations", "organisationwebhook"),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="organisationwebhook",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
