# Generated by Django 3.2.16 on 2022-11-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0033_allow_blank_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("CHARGEBEE", "Chargebee"), ("XERO", "Xero")],
                max_length=20,
                null=True,
            ),
        ),
    ]
