# Generated by Django 3.2.16 on 2022-11-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0035_add_organisation_subscription_information_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
    ]
