# Generated by Django 3.2.16 on 2022-12-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0036_add_default_subscription_to_existing_organisations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(blank=True, default='free', max_length=100, null=True),
        ),
    ]
