# Generated by Django 3.2.18 on 2023-02-28 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0038_soft_delete_organisations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='organisation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscription', to='organisations.organisation'),
        ),
    ]
