# Generated by Django 3.2.19 on 2023-06-21 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0040_alter_organisationwebhook_url'),
        ('organisations', '0040_organisationsubscriptioninformationcache_chargebee_email'),
    ]

    operations = [
    ]
