# Generated by Django 3.2.20 on 2023-08-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0045_auto_20230802_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationsubscriptioninformationcache',
            name='allowed_projects',
            field=models.IntegerField(default=1, blank=True, null=True),
        ),
    ]
