# Generated by Django 3.2.20 on 2023-09-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0046_allow_allowed_projects_to_be_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationsubscriptioninformationcache',
            name='plan_id',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
