# Generated by Django 3.2.23 on 2023-11-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0048_add_default_subscription_to_orphaned_organisations'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='billing_status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('DUNNING', 'Dunning')], max_length=20, null=True),
        ),
    ]
