# Generated by Django 3.2.23 on 2024-02-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0050_add_historical_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationsubscriptioninformationcache',
            name='current_billing_term_ends_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='organisationsubscriptioninformationcache',
            name='current_billing_term_starts_at',
            field=models.DateTimeField(null=True),
        ),
    ]
