# Generated by Django 3.2.25 on 2024-04-08 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0053_create_api_limit_access_block"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OranisationAPIUsageNotification",
            new_name="OrganisationAPIUsageNotification",
        ),
        migrations.CreateModel(
            name="OrganisationAPIBilling",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_overage", models.IntegerField()),
                ("immediate_invoice", models.BooleanField(default=False)),
                ("billed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_billing",
                        to="organisations.organisation",
                    ),
                ),
            ],
        ),
    ]
