# Generated by Django 3.2.25 on 2024-08-06 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0055_alter_percent_usage"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationBreachedGracePeriod",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "organisation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breached_grace_period",
                        to="organisations.organisation",
                    ),
                ),
            ],
        ),
    ]
