# Generated by Django 5.2.16 on 2026-08-07 11:54

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0058_update_audit_and_history_limits_in_sub_cache"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisationwebhook",
            name="url",
            field=core.fields.NoSSRFURLField(),
        ),
    ]
