# Generated by Django 5.2.17 on 2026-08-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0060_add_targeting_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="userorganisation",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Inactive members can still log in, but cannot access the organisation, and do not count towards its seat limit.",
            ),
        ),
    ]
