# Generated by Django 3.2.18 on 2023-02-28 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0028_add_use_mv_v2_evaluation'),
        ('heap', '0002_add_uuid_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heapconfiguration',
            name='environment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='heap_config', to='environments.environment'),
        ),
    ]
