# Generated by Django 3.2.18 on 2023-02-28 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_soft_delete_projects'),
        ('new_relic', '0003_add_uuid_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newrelicconfiguration',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='new_relic_config', to='projects.project'),
        ),
    ]
