# Generated by Django 2.2.16 on 2020-09-18 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('environments', '0015_auto_20200916_1441'),
        ('features', '0025_auto_20200918_1041'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='FeatureState',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True,
                                                serialize=False, verbose_name='ID')),
                        ('enabled', models.BooleanField(default=False)),
                        ('environment', models.ForeignKey(null=True,
                                                          on_delete=django.db.models.deletion.CASCADE,
                                                          related_name='feature_states',
                                                          to='environments.Environment')),
                        ('feature',
                         models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='feature_states',
                                           to='features.Feature')),
                        ('feature_segment',
                         models.ForeignKey(blank=True, default=None, null=True,
                                           on_delete=django.db.models.deletion.CASCADE,
                                           related_name='feature_states',
                                           to='features.FeatureSegment')),
                        ('identity',
                         models.ForeignKey(blank=True, default=None, null=True,
                                           on_delete=django.db.models.deletion.CASCADE,
                                           related_name='identity_features',
                                           to='identities.Identity')),
                    ],
                    options={
                        'db_table': 'features_featurestate',
                        'ordering': ['id'],
                        'unique_together': {('feature', 'environment', 'identity'), (
                        'feature', 'environment', 'feature_segment')},
                    },
                ),
                migrations.CreateModel(
                    name='HistoricalFeatureStateValue',
                    fields=[
                        ('id', models.IntegerField(auto_created=True, blank=True,
                                                   db_index=True, verbose_name='ID')),
                        ('type', models.CharField(blank=True,
                                                  choices=[('int', 'Integer'),
                                                           ('unicode', 'String'),
                                                           ('bool', 'Boolean')],
                                                  default='unicode', max_length=10,
                                                  null=True)),
                        ('boolean_value', models.NullBooleanField()),
                        ('integer_value', models.IntegerField(blank=True, null=True)),
                        ('string_value',
                         models.CharField(blank=True, max_length=2000, null=True)),
                        ('history_id',
                         models.AutoField(primary_key=True, serialize=False)),
                        ('history_date', models.DateTimeField()),
                        ('history_change_reason',
                         models.CharField(max_length=100, null=True)),
                        ('history_type', models.CharField(
                            choices=[('+', 'Created'), ('~', 'Changed'),
                                     ('-', 'Deleted')], max_length=1)),
                        ('feature_state',
                         models.ForeignKey(blank=True, db_constraint=False, null=True,
                                           on_delete=django.db.models.deletion.DO_NOTHING,
                                           related_name='+',
                                           to='feature_states.FeatureState')),
                        ('history_user', models.ForeignKey(null=True,
                                                           on_delete=django.db.models.deletion.SET_NULL,
                                                           related_name='+',
                                                           to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'historical feature state value',
                        'db_table': 'features_historicalfeaturestatevalue',
                        'ordering': ('-history_date', '-history_id'),
                        'get_latest_by': 'history_date',
                    },
                    bases=(simple_history.models.HistoricalChanges, models.Model),
                ),
                migrations.CreateModel(
                    name='HistoricalFeatureState',
                    fields=[
                        ('id', models.IntegerField(auto_created=True, blank=True,
                                                   db_index=True, verbose_name='ID')),
                        ('enabled', models.BooleanField(default=False)),
                        ('history_id',
                         models.AutoField(primary_key=True, serialize=False)),
                        ('history_date', models.DateTimeField()),
                        ('history_change_reason',
                         models.CharField(max_length=100, null=True)),
                        ('history_type', models.CharField(
                            choices=[('+', 'Created'), ('~', 'Changed'),
                                     ('-', 'Deleted')], max_length=1)),
                        ('environment',
                         models.ForeignKey(blank=True, db_constraint=False, null=True,
                                           on_delete=django.db.models.deletion.DO_NOTHING,
                                           related_name='+',
                                           to='environments.Environment')),
                        ('feature',
                         models.ForeignKey(blank=True, db_constraint=False, null=True,
                                           on_delete=django.db.models.deletion.DO_NOTHING,
                                           related_name='+', to='features.Feature')),
                        ('feature_segment',
                         models.ForeignKey(blank=True, db_constraint=False,
                                           default=None, null=True,
                                           on_delete=django.db.models.deletion.DO_NOTHING,
                                           related_name='+',
                                           to='features.FeatureSegment')),
                        ('history_user', models.ForeignKey(null=True,
                                                           on_delete=django.db.models.deletion.SET_NULL,
                                                           related_name='+',
                                                           to=settings.AUTH_USER_MODEL)),
                        ('identity', models.ForeignKey(blank=True, db_constraint=False,
                                                       default=None, null=True,
                                                       on_delete=django.db.models.deletion.DO_NOTHING,
                                                       related_name='+',
                                                       to='identities.Identity')),
                    ],
                    options={
                        'verbose_name': 'historical feature state',
                        'db_table': 'features_historicalfeaturestate',
                        'ordering': ('-history_date', '-history_id'),
                        'get_latest_by': 'history_date',
                    },
                    bases=(simple_history.models.HistoricalChanges, models.Model),
                ),
                migrations.CreateModel(
                    name='FeatureStateValue',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True,
                                                serialize=False, verbose_name='ID')),
                        ('type', models.CharField(blank=True,
                                                  choices=[('int', 'Integer'),
                                                           ('unicode', 'String'),
                                                           ('bool', 'Boolean')],
                                                  default='unicode', max_length=10,
                                                  null=True)),
                        ('boolean_value', models.NullBooleanField()),
                        ('integer_value', models.IntegerField(blank=True, null=True)),
                        ('string_value',
                         models.CharField(blank=True, max_length=2000, null=True)),
                        ('feature_state', models.OneToOneField(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name='feature_state_value',
                            to='feature_states.FeatureState')),
                    ],
                    options={
                        'db_table': 'features_featurestatevalue',
                    },
                ),
            ],
            database_operations=[]
        )
    ]
