# Generated by Django 5.2.14 on 2026-05-19 11:05

import django.db.models.deletion
import django_lifecycle.mixins  # type: ignore[import-untyped]
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("environments", "0037_add_uuid_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarehouseConnection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "warehouse_type",
                    models.CharField(
                        choices=[
                            ("flagsmith", "Flagsmith"),
                            ("snowflake", "Snowflake"),
                            ("clickhouse", "ClickHouse"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_connection", "Pending Connection"),
                            ("connected", "Connected"),
                            ("errored", "Errored"),
                        ],
                        default="pending_connection",
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_connections",
                        to="environments.environment",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("warehouse_type", "environment"),
                        name="unique_active_warehouse_per_type_and_env",
                    )
                ],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
