# Generated by Django 5.2.14 on 2026-05-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experimentation", "0001_introduce_warehouse_connection"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouseconnection",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="warehouseconnection",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("pending_connection", "Pending Connection"),
                    ("connected", "Connected"),
                    ("errored", "Errored"),
                ],
                default="created",
                max_length=50,
            ),
        ),
    ]
