# Generated by Django 5.2.14 on 2026-06-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experimentation", "0006_experiment_exposures"),
    ]

    operations = [
        migrations.AddField(
            model_name="experimentexposures",
            name="refresh_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
