# Generated by Django 5.2.14 on 2026-06-19 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experimentation", "0008_experiment_results"),
        ("segments", "0030_add_default_to_segment_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="experiment",
            name="rollout_segment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="experiment_rollout",
                to="segments.segment",
            ),
        ),
    ]
