# Generated by Django 5.2.16 on 2026-07-21 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experimentation", "0010_warehouse_connection_credentials_and_status_detail"),
        ("organisations", "0058_update_audit_and_history_limits_in_sub_cache"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationIngestionInfrastructure",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("created", "Created"),
                            ("errored", "Errored"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "bucket_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stream_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="ingestion_infrastructure",
                        to="organisations.organisation",
                    ),
                ),
            ],
        ),
    ]
