# Generated by Django 5.2.16 on 2026-07-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experimentation", "0010_warehouse_connection_credentials"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouseconnection",
            name="status_detail",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
