# Generated by Django 5.2.16 on 2026-07-31 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experimentation", "0011_organisation_ingestion_infrastructure"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarehouseDeliveryLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("s3_key", models.CharField(max_length=1024)),
                (
                    "outcome",
                    models.CharField(
                        choices=[("delivered", "Delivered"), ("rejected", "Rejected")],
                        max_length=50,
                    ),
                ),
                ("rows_count", models.PositiveIntegerField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_logs",
                        to="experimentation.warehouseconnection",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["connection", "created_at"],
                        name="experimenta_connect_11e6cf_idx",
                    )
                ],
            },
        ),
    ]
