# Generated by Django 5.2.17 on 2026-09-15 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("experimentation", "0013_add_experiment_audience"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warehousedeliverylog",
            name="connection",
        ),
        migrations.DeleteModel(
            name="OrganisationIngestionInfrastructure",
        ),
        migrations.DeleteModel(
            name="WarehouseDeliveryLog",
        ),
    ]
