# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-10 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('audit', '0002_auto_20190909_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ('-created_date',), 'verbose_name_plural': 'Audit Logs'},
        ),
        migrations.AddField(
            model_name='auditlog',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='projects.Project'),
        ),
    ]
