# Generated by Django 3.2.12 on 2022-03-23 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0010_auto_20211208_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynatraceConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField()),
                ('api_key', models.CharField(max_length=100)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dynatrace_config', to='projects.project')),
            ],
        ),
    ]
