# Generated by Django 4.2.18 on 2025-02-17 15:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feature_health", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="featurehealthevent",
            name="external_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalfeaturehealthevent",
            name="external_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="featurehealthevent",
            name="created_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="historicalfeaturehealthevent",
            name="created_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
