# Generated by Django 4.2.18 on 2025-02-13 20:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    # TODO remove replaced migrations before merging

    replaces = [
        ("feature_health", "0002_alter_featurehealthevent_external_id_and_more"),
        ("feature_health", "0003_alter_featurehealthevent_reason_and_more"),
    ]

    dependencies = [
        ("feature_health", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="featurehealthevent",
            name="external_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalfeaturehealthevent",
            name="external_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="featurehealthevent",
            name="created_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="historicalfeaturehealthevent",
            name="created_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="featurehealthevent",
            name="reason",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalfeaturehealthevent",
            name="reason",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
