# Generated by Django 4.2.26 on 2025-11-27 10:39
from django.apps.registry import Apps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

from django.db import migrations, models


def migrate_sample_to_webhook_forward(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    FeatureHealthProvider = apps.get_model("feature_health", "FeatureHealthProvider")
    FeatureHealthEvent = apps.get_model("feature_health", "FeatureHealthEvent")
    
    FeatureHealthProvider.objects.filter(name="Sample").update(name="Webhook")
    FeatureHealthEvent.objects.filter(provider_name="Sample").update(provider_name="Webhook")


def migrate_sample_to_webhook_reverse(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    FeatureHealthProvider = apps.get_model("feature_health", "FeatureHealthProvider")
    FeatureHealthEvent = apps.get_model("feature_health", "FeatureHealthEvent")
    
    FeatureHealthProvider.objects.filter(name="Webhook").update(name="Sample")
    FeatureHealthEvent.objects.filter(provider_name="Webhook").update(provider_name="Sample")



class Migration(migrations.Migration):

    dependencies = [
        ("feature_health", "0002_featurehealthevent_add_external_id_alter_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurehealthprovider',
            name='name',
            field=models.CharField(
                choices=[('Webhook', 'Webhook'), ('Grafana', 'Grafana')],
                max_length=50
            ),
        ),
        migrations.AlterField(
            model_name='historicalfeaturehealthprovider',
            name='name',
            field=models.CharField(
                choices=[('Webhook', 'Webhook'), ('Grafana', 'Grafana')],
                max_length=50
            ),
        ),
        migrations.RunPython(
            migrate_sample_to_webhook_forward,
            migrate_sample_to_webhook_reverse,
        ),
    ]