# Generated by Django 4.2.18 on 2025-02-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feature_health", "0002_alter_featurehealthevent_external_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featurehealthevent",
            name="reason",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalfeaturehealthevent",
            name="reason",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
