# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0006_auto_20181030_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='pending_cancellation',
            field=models.BooleanField(default=False),
        ),
    ]
