# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-12 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def prefill_subscription_data(apps, schema_editor):
    Organisation = apps.get_model('organisations', 'Organisation')
    Subscription = apps.get_model('organisations', 'Subscription')

    for org in Organisation.objects.all():
        subscription = Subscription(organisation=org)
        for field in org._meta.get_fields():
            if hasattr(subscription, field.name) and field.name != 'id':
                setattr(subscription, field.name, getattr(org, field.name))
        subscription.save()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0009_auto_20181108_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_date', models.DateField(blank=True, null=True)),
                ('paid_subscription', models.BooleanField(default=False)),
                ('free_to_use_subscription', models.BooleanField(default=True)),
                ('plan', models.CharField(blank=True, max_length=20, null=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='organisations.Organisation')),
                ('pending_cancellation', models.BooleanField(default=False))
            ],
        ),
        migrations.RunPython(prefill_subscription_data, reverse_code=reverse),
        migrations.RemoveField(
            model_name='organisation',
            name='free_to_use_subscription',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='paid_subscription',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='subscription_date',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='pending_cancellation',
        ),
    ]
