# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-12 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0011_subscription_max_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='max_seats',
            field=models.IntegerField(default=1),
        ),
    ]
