# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-03 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0014_organisation_stop_serving_flags'),
        ('organisations', '0017_subscription_cancellation_date'),
    ]

    operations = [
    ]
