# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-23 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0018_merge_20191003_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='customer_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
