# Generated by Django 2.2.15 on 2020-09-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0021_auto_20200619_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='persist_trait_data',
            field=models.BooleanField(default=True, help_text="Disable this if you don't want Bullet Train to store trait data for this org's identities."),
        ),
    ]
