# Generated by Django 2.2.14 on 2020-07-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0021_auto_20200619_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='datadog_api_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
