# Generated by Django 2.2.14 on 2020-07-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0022_organisation_datadog_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='datadog_api_base_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
