# Generated by Django 2.2.16 on 2020-09-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0022_organisation_persist_trait_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='access_blocked',
            field=models.BooleanField(default=False, help_text='Enable this to block all the access to this organisation'),
        ),
    ]
