# Generated by Django 2.2.17 on 2021-02-23 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0024_organisation_feature_analytics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisationwebhook',
            options={'ordering': ('id',)},
        ),
    ]
