name: API Add Known SDK Version

on:
  workflow_dispatch:
    inputs:
      opts:
        description: Options to pass to the script (e.g. '--sdk flagsmith-python-sdk --version 1.2.3')
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  add-sdk-version:
    runs-on: depot-ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: "poetry"

      - name: Install Dependencies
        run: make install-packages

      - name: Run `make add-known-sdk-version`
        env:
          opts: ${{ inputs.opts }}
        run: make add-known-sdk-version

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: chore/add-sdk-version-${{ github.event.inputs.sdk-key }}-${{ github.event.inputs.sdk-version }}
          title: "chore: Add known SDK version ${{ github.event.inputs.sdk-version }} for ${{ github.event.inputs.sdk-key }}"
          body: |
            This PR adds the known SDK version `${{ github.event.inputs.sdk-version }}` for the SDK key `${{ github.event.inputs.sdk-key }}`.

            If this is incorrect, please update the PR or close it and make the changes manually.
