name: Auto Rebase Feature Branch

on:
  schedule:
    - cron: '0 * * * *'  # Every hour

jobs:
  rebase-feature:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Flagsmith'
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0  # Required for rebase

      - name: Set up Git
        run: |
          git config user.name "flagsmithdev"
          git config user.email "engineering@flagsmith.com"

      - name: Fetch feature branch
        run: |
          git fetch origin docs/writechoice-dev-docs

      - name: Rebase feature on main
        run: |
          git checkout docs/writechoice-dev-docs
          git rebase main || echo "REBASE_FAILED=true" >> $GITHUB_ENV

      - name: Push rebased feature
        if: env.REBASE_FAILED != 'true'
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin docs/writechoice-dev-docs --force-with-lease

      - name: Comment on PR if rebase failed
        if: env.REBASE_FAILED == 'true'
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.number }}
          body: |
            🚨 The automatic rebase of `devops-infra/action-rebase` onto `main` failed due to conflicts.
            Please rebase manually or resolve the conflict.
