name: Docs Lint/Link Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - docs/**
      - .github/**

defaults:
  run:
    working-directory: docs

jobs:
  checks:
    runs-on: depot-ubuntu-latest
    name: Link Check Docs

    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Use Node.js 20
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'docs/package-lock.json'

      - name: npm install
        run: npm ci --include=dev --ignore-scripts

      - name: Run docusaurus build to check for broken links etc
        run: npm run build
