name: Docs - update SDK versions

on:
  workflow_dispatch:
  schedule:
    # At 12:00 on Tuesday https://crontab.guru/#0_12_*_*_2
    - cron: '0 12 * * 2'
jobs:
  vercel-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run Vercel deploy hook
        run: curl -X POST "${{ secrets.VERCEL_SDK_VERSIONS_DEPLOY_HOOKS_URL }}"
