name: 'Manual E2E tests'

on:
  workflow_dispatch:
    inputs:
      e2e-token:
        description: 'The authentication token used by the E2E process'
        required: true
      e2e-concurrency:
        description: 'The concurrency value to use when running the E2E process'
        default: 3
        type: number
      api-url:
        description: 'Which database service to use to run the API against'
        default: 'https://api.flagsmith.com/api/v1/'

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: frontend/.nvmrc
          cache-dependency-path: frontend/package-lock.json

      - name: Run tests
        working-directory: frontend
        env:
          E2E_TEST_AUTH_TOKEN: ${{ inputs.e2e-token }}
          FLAGSMITH_API_URL: ${{ inputs.api-url }}
          E2E_CONCURRENCY: ${{ inputs.e2e-concurrency }}
        run: |
          npm ci
          npm run env
          npm run test
