name: Run E2E tests against a deployed API instance

on:
  workflow_dispatch:
    inputs:
      e2e-token:
        description: The authentication token used by the E2E process
        required: true
      api-url:
        description: An API URL to run the E2E tests against
        default: 'https://api.flagsmith.com/api/v1/'
        
jobs:
  run-e2e-tests:
    runs-on: depot-ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: frontend/.nvmrc
          cache-dependency-path: frontend/package-lock.json

      - name: Run tests
        working-directory: frontend
        env:
          E2E_TEST_AUTH_TOKEN: ${{ inputs.e2e-token }}
          FLAGSMITH_API_URL: ${{ inputs.api-url }}
        run: |
          npm ci
          npm run env
          npm run test
