name: Platform Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write # for googleapis/release-please-action to create release commit
  pull-requests: write # for googleapis/release-please-action to create release PR

jobs:
  release-please:
    runs-on: depot-ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.FLAGSMITH_ENGINEERING_GH_APP_ID }}
          private-key: ${{ secrets.FLAGSMITH_ENGINEERING_GH_APP_PRIVATE_KEY }}

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ steps.app-token.outputs.token }}

    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      release_tag_name: ${{ steps.release.outputs.tag_name }}
